\section{RESEARCH AND DATA NEEDS} \label{sec:research}

There are many research projects that could improve the stock assessment for
\fishname. The following prioritized list of topics will lead to improved
biological understanding and decision-making:

<<research-research-needs-sec, child='../executive-summary/research-needs.rnw'>>=
@

<<research-research-needs-remainder-sec, child='../executive-summary/research-needs-remainder.rnw'>>=
