# Summary

## Summary (1/3)

* Based on the default harvest rule, the estimated median catch limit for
  `r min(forecast_yrs)` is `r ct_limit_quantiles["median"]`~t (with 95%
   interval from `r ct_limit_quantiles["lower"]` to
   `r ct_limit_quantiles["upper"]`~t).

* Projections strongly influenced by size of above-average 2020 and 2021
  cohorts, with 2021 being potentially large but also *highly* uncertain.

* Spawning biomass has a 50% chance of decreasing from `r assess_yr` to
  `r assess_yr + 1` for a 1-year catch of 350,000~t. At that level and higher,
  declines in spawning biomass from catch outpace increases from growth
  given recent 5-year average selectivity and population age structure.

* The decline is even more likely after two and three years of catch.

* Achieving a constant catch of 625,000~t (the 2023 TAC) gives a 4%
  chance of falling below `r b_40` in 1 year, 11% in 2 years, and
  21% in 3 years.

## Summary (2/3)

* Spawning biomass has rapidly increased from 2022--2024 after a steady decline
  from 2018--2022 (though still well above `r b_40`).

* High proportion of age 3 and 4 fish predicted in 2024 fishery
  (61% by numbers, 55% by weight).

* Older fish predicted in 2024 fishery primarily from 2014 and 2016 cohort
  (15% by numbers, 20% by weight).

* The 2021 year class currently estimated to be well above average.

* Uncertainty is large, but stock currently has only `r probs_curr_below_b40`%
  chance of being below `r b_40` and `r probs_curr_rel_fish_intens_above_1`%
  chance of relative fishing intensity being above 100%.

* The model estimates a `r joint_percent_prob_above_below`% joint
  probability of being both above the target relative fishing intensity in
  `r end_yr - 1` and below the `r b_40` relative spawning biomass level at the
  start of `r end_yr`.

## Summary (3/3)

* Despite healthy stock size and status estimates, the recent lack of survey
abundance and fishery catch in Canada suggests a population structure not
conducive to achieving harvest quotas in northern fisheries over recent years.

* Conventional wisdom of fish moving further north in warmer years potentially
no longer holding or covaries with other driving factors.

<!-- ## Assessment timeline -->

<!-- ```{r jmc-timing, fig.height = 4, out.height = "85%"} -->

<!-- plot_assessment_timeline() -->

<!-- ``` -->
