# Summary

## Summary (1/3)

* Based on the default harvest rule, the estimated median catch limit for
  `r min(forecast_yrs)` is `r ct_limit_quantiles["median"]`~t (with 95%
   interval from `r ct_limit_quantiles["lower"]` to
   `r ct_limit_quantiles["upper"]`~t).

* Projections strongly influenced by size of above-average 2020 and 2021
  cohorts, with 2021 being potentially large but also *highly* uncertain, and
  the assumption of median (average) recruitment from 2023 onward.

* Spawning biomass has a 100% chance of decreasing from `r assess_yr` to
  `r assess_yr + 1` for catch 150 kt or greater.

* Achieving a constant catch of 250,000~t (similar to 2025 catch)
  gives a 33% chance of falling below `r b_40` by the start of 2027.
  
* While the assumption of average recruitment in any one year can be considered
  risk neutral, the accumulation of several years of assumed average recruitment
  (as in this assessment) underestimates future recruitment (and thus spawning biomass).

## Summary (2/3)

* Spawning biomass has decreased from 2025--2026 after being relatively stable
  from 2023--2025.

* The median estimate of `r end_yr` relative spawning biomass is
  `r curr_depl_median`% (with 95% interval from `r curr_depl_lower`%
   to `r curr_depl_upper`%)

* High proportion of age-5 and age-6 fish predicted in 2026 fishery. Age-3 fish
  likely to also be high next year given 2025 fishery and survey age data.

* The 2021 year class currently estimated to be above average.

* Uncertainty is large, but stock currently has `r probs_curr_below_b40`%
  chance of being below `r b_40` and `r probs_curr_rel_fish_intens_above_1`%
  chance of relative fishing intensity being above 100%.

* `r joint_percent_prob_above_below`% joint
  probability of being both above the target relative fishing intensity in
  `r end_yr - 1` and below the `r b_40` relative spawning biomass level at the
  start of `r end_yr`.

## Summary (3/3)

* Despite estimates of a current stock status likely above `r b_40`, the recent lack
  of survey abundance and fishery catch in Canada suggests
  a population structure not conducive to achieving harvest quotas in
  northern fisheries over recent years.

* A better understanding of the factors affecting hake distribution and fishery performance
  were highlighted by the SRG as the top priority research recommendation.
