## Request 5 -- "Re-run the base model"

The SRG requests rerunning the base assessment model with updated weight-at-age and fecundity matrices based on day 278.  Updated harvest scenario tables if possible.


## Request 5 -- "Re-run the base model"
```{r plot-base-v-tv-maturity-ssb, out.height = "85%"}
m_names <- c("bridge step", "no unsexed weight-at-age", "new base", "old base")
old_base <- readRDS(fs::path("/srv/hake/models/2024/01-version/01-base-models/01-base/01-base.rds"))
step_before <- readRDS(fs::path("/srv/hake/models/2024/01-version/02-bridging-models/60-survey-1-t-distribution/60-survey-1-t-distribution.rds"))
first_step <- readRDS(fs::path("/srv/hake/models/2024/02-version/05-test-models/01-redo-fishery-comp/01-redo-fishery-comp.rds"))
new_base <- readRDS(fs::path("/srv/hake/models/2024/02-version/01-base-models/01-base/01-base.rds"))
plot_biomass(list(step_before, first_step, new_base, old_base), model_names = m_names)
```

## Request 5 -- "Re-run the base model"
```{r plot-base-v-tv-maturity-rel, out.height = "85%"}
plot_rel_biomass(list(step_before, first_step, new_base, old_base), model_names = m_names)
```

