\rfoot{Assessment}

# Assessment {#sec:assessment}

## Modeling history {#sec:assessment-modeling-history}

In spite of the relatively short history of fishing, `r sp` have surely been
subject to a larger number of stock assessments than any marine species off the
west coast of the U.S.A.~and Canada. These assessments have included a large
variety of age-structured models. Initially, a cohort analysis tuned to fishery
CPUE was used [@FrancisSwartzmanEtAl1982]. Later, the cohort analysis was
tuned to National Marine Fisheries Service (NMFS) triennial acoustic survey
estimates of absolute biomass at age [@HollowedAdlersteinEtAl1988].
Since 1989, Stock Synthesis models (or base versions of it) fit to
fishery catch-at-age data and acoustic survey estimates of population biomass
and age composition have been the primary assessment method.

While the general form of the age-structured assessment has remained similar
since 1991, modeling procedures have been modified in a variety of ways. There
have been alternative data choices, post-data collection processing routines,
data-weighting schemes, structural assumptions for the stock assessment model,
MCMC sampling algorithms, and control rules 
(Table~\@ref(tab:main-assessment-changes)). Analysts are constantly trying to
improve the caliber and relevance of the assessment by responding to new
scientific developments related to statistics and biological dynamics, policy
requirements, and different or new insights brought up during the peer review
process to ensure a robust stock assessment.

Data processing, filtering, and weighting choices have been modified several
times since the first assessment. For example, modifications to the
target-strength relationship used to scale acoustic data changed in 1997
[@DornSaunders1997], and kriging was implemented to account for the spatial
correlation in the acoustic data in 2010 [@StewartHamel2010]. While survey
data have been the key index for biomass since 1988, surveys that have been
used have varied considerably. The Alaska Fisheries Science Center/Northwest
Fisheries Science Center West Coast Triennial Shelf Survey was used from 1988
before being discarded from the 2009 assessment [@HamelStewart2009]. Acoustic
surveys from the years prior to 1995 were used for assessments in the early
1990s, but @StewartForrestEtAl2011 reviewed these early surveys and deemed
that sampling was insufficient to be comparable with more recent data. Several
recruitment indices have been considered but ultimately none were identified
as adding appreciable contribution to model results [@HelserDornEtAl2002;
@HelserFleischerEtAl2005; @StewartHamel2010], except for the
fishery-independent acoustic-based age-1 index which has been included in the
base model since the 2022 assessment. The process for generating
fecundity-at-age from weight-at-age data changed in 2019 from using
time-invariant to year-specific values. Even where data have been consistently
used, the weighting of these data in the statistical likelihood has changed
through the use of various emphasis factors (e.g., @Dorn1994,
@DornSaundersEtAl1999), a multinomial sample size on age compositions (e.g.,
@DornSaundersEtAl1999, @HelserDornEtAl2002, @HelserFleischerEtAl2005,
@StewartForrestEtAl2011), internal estimations of effective sample size using
the Dirichlet-multinomial distribution [@JTC2018], and assumptions regarding
year-specific survey variance. Since 2021, a more computationally efficient
Bayesian MCMC sampler (No-U-Turn Sampler; NUTS; @HoffmanGelman2014) was used
to estimate posterior distributions [@Monnahan2018; @Monnahan2019], a change
from previous assessments that used the random walk Metropolis Hastings (rwMH)
sampler (details described in @JTC2021). The list of changes discussed above
is for illustrative purposes only and represents a small fraction of the
different choices analysts have made and that reviewers have required.

The structure of the assessment models has perhaps had the largest number of
changes. In terms of spatial models, analysts have considered
spatially explicit forms [@Dorn1994; @Dorn1997], spatially implicit forms
[@HelserStewartEtAl2006], and single-area models [@JTC2012]. Predicted
recruitment has been modeled by sampling historical recruitment (e.g.,
@Dorn1994, @HelserFleischerEtAl2005), using a stock-recruitment
relationship parameterized using maximum sustainable yield ($\text{MSY}$) and
the fishing mortality rate estimated to produce the MSY ($\Fmsy$;
@Martell2010), and using several alternative steepness priors [@JTC2012;
@JTC2013]. Selectivity has also been modeled in several ways: invariant
[@JTC2012; @JTC2013], time-varying with [@HelserDornEtAl2002] and without
[@Dorn1994; @DornSaunders1997; @JTC2012; @JTC2013] a random walk,
alternative levels of allowable deviation through time [@JTC2013; @JTC2017],
age-based [@Dorn1994; @DornSaunders1997; @JTC2012; @JTC2013}, and length-based
[@HelserMartell2007].

Several harvest control rules have been explored for providing catch limits
from stock assessment output. `r sp` stock assessments have presented decision
makers with constant $\mathrm{F}$, variable $\mathrm{F}$, and the following
hybrid control rules: $\FSPRthirtyfive$, $\Fforty$, \Ffortyten,
$\FSPRfortyfive$, \Ffortyfivefortyten, and $\FSPRfifty$ (e.g., @Dorn1996,
@JTC2013). Changes to policies such as the United States' National Standards
Guidelines in 2002 and the \Ffortyten harvest control rule in the Agreement
(Appendix~\@ref(chap:glossary)) have required specific changes to control
rules.

In addition to the examples given above and changes documented in stock
assessments, there have been many more investigations conducted at review
panel meetings. Starting in 2013, the addition of the MSE [@JTC2013; 
@JacobsenEtAl2021] facilitated investigating changes to the modeling
procedure in terms of pre-specified objectives that aim for a sustainable
coast-wide fishery.

## Description of base model {#sec:assessment-base-model}

The `r assess_yr` base model has the same population dynamics structure as the
`r last_assess_yr` assessment's base model. The statistical-catch-at-age model
assumes that the `r sp` population is a single coast-wide stock subject to
one aggregated fleet with combined male and female population dynamics. Stock
Synthesis [@MethotWetzel2013] version `r ss_version` was the modeling platform
used. The largest change between the `r last_assess_yr` and `r assess_yr`
stock assessments is the addition of another year of fishery data into the base
model.

The `r assess_yr` base model includes a time series (1995 to
`r last_survey_yr`) of acoustic age-2$+$ biomass estimates and acoustic
estimates of age-1 fish (see Section~\@ref(sec:data-acoustic-survey) for more
details on the age-1 index). Maturity is assumed to be time-invariant and the
maturity ogive updated in 2018 was retained
(see Section~\@ref(sec:data-maturity)). Fecundity is defined as weight-at-age
multiplied by the maturity ogive and is time-varying across years with
empirical weight-at-age data (`r start_yr_age_comps`--`r last_data_yr`; see
Section~\@ref(sec:data-weight-at-age)). The D-M likelihood approach
[@ThorsonEtAl2017Dirichlet] is again used to estimate the weights associated
with age-composition data, rather than iteratively tuning the sample size
multiplier as in 2017 and earlier assessments (see
Section~\@ref(sec:data-age-comp-likelihood)). Time-varying fishery
selectivity is retained in the `r assess_yr` base model with the magnitude
of the allowable deviations unchanged from the `r last_assess_yr` base model
(see Section~\@ref(sec:data-variability-selectivity)). The general
parameterization of selectivity was retained, although additional parameter
s were required to estimate an additional year of deviations. The selectivity
of the acoustic survey is assumed to be time invariant. Selectivity curves
were modeled as non-parametric functions estimating age-specific values for
each age beginning at age-2 for the index of age-2$+$ biomass and age-1 for
the fishery until a maximum age of 6, after which all ages are assumed to have
the same selectivity. Selectivity for the age-1 index was set to one for age-1
and zero for all other ages.

Prior probability distributions are used for a select few parameters and fixed
values are used for several parameters. For the base model, the instantaneous
rate of natural mortality ($M$) is estimated with a `r m_prior[1]` prior
having a median of `r f(exp(as.numeric(m_prior[2])), 2)` and a standard
deviation (in log-space) of 0.1 (see
Section~\@ref(sec:data-natural-mortality)). The stock-recruitment function is
a Beverton-Holt parameterization, with the log of the mean unexploited
recruitment (log~$R_0$) freely estimated. This assessment uses the same
beta-distributed prior for stock-recruit steepness ($h$), based on
@MyersBowenEtAl1999, that has been applied since 2011
[@StewartForrestEtAl2011]. Year-specific recruitment deviations were estimated
from `r main.recdev.early`--`r main.recdev.end + 1` as well as the years
`r assess_yr - 1`--`r assess_yr + 3` for purposes of forecasting. The standard
deviation, $\sigma_r$, of recruitment variability serves as a recruitment
deviation constraint and is fixed at `r base_model$sigma_R_in` in this
assessment. This value is based on consistency with the observed variability
in the time series of recruitment deviation estimates and is the same as
assumed in assessments from 2013 to `r last_assess_yr`
(Table~\@ref(tab:main-assessment-changes)). Catchabilities associated with the
biomass index ($q_b$) and with the age-1 index ($q_1$) were calculated
analytically as per @LudwigWalters1981 for each sample of posterior parameters,
resulting in a distribution of catchability for each.

Statistical likelihood functions used for data fitting are typical of many
stock assessments. The biomass index was fit via a lognormal likelihood
function, using the observed (and extra 2009) sampling variability, estimated
via kriging, as year-specific weighting. The age-1 index was also specified as
having lognormal error structure. An additional constant and additive standard
deviation on the log-scale component is included for both the biomass index
and the age-1 index, which were freely estimated to accommodate
unaccounted-for sources of process and observation error. A D-M likelihood was
applied to age-composition data, with input sample sizes equal to the sum of
the number of trips and hauls sampled across all fishing fleets or the number
of trawl sets in the research surveys
(see Section~\@ref(sec:data-age-comp-likelihood)).

Model results and statistical inference were based on 
`r f(num_mcmc_samples)` MCMC samples (using the \texttt{adnuts} R package;
@Monnahan2018) to describe posterior distributions for model
parameters and derived quantities. The number of samples used for bridging
models, sensitivity models, and retrospective models was also
`r f(num_mcmc_samples)`. Medians (50% quantiles) are reported together with
the bounds of 95% credibility intervals calculated as the 2.5% quantile and
the 97.5% quantile of posterior distributions from the MCMC samples, to
give equal-tailed intervals. A full explanation of the NUTS algorithm and the
\texttt{adnuts} package, including an analysis with the `r sp` stock can be found
in @Monnahan2019.

## Response to 2022 Scientific Review Group (SRG) review {#sec:assessment-response-review}

The Scientific Review Group (SRG) meeting was held virtually from February
14-17, 2022.

The following are the `SRG Recommendations and Conclusions for the Stock
Assessment' from the 2022 SRG report and the associated responses from the
JTC:

1. **The SRG notes that $\sigma_R$ is an influential parameter and that
  determining the choice of $\sigma_R$ remains a challenge and encourages the
  JTC to continue to work on the issue.**

> *Response -- Developing best practices for modeling mean unfished
> equilibrium recruitment ($R_0$) and recruitment variability ($\sigma_R$)
> remain broad topics of contemporary research. Recent recommendations
> suggest that the next generation of stock assessment modeling frameworks
> should concomitantly treat recruitment deviations as a random effect and
> estimate $\sigma_R$ [@Punt2020]. The JTC continues to conduct,
> collaborate on, and monitor ongoing research projects concerning
> approaches for advancing recruitment estimation, as applied to `r sp` and
> in general. Many of these issues are widespread in stock assessment and
> scientific-based solutions are likely to be the result of medium to
> long-term research projects. Here, we provide a few updates to our previous
> response on this topic, including specific advances in research endeavors
> where applicable.*

> *The JTC continues to participate in collaborative research to investigate
> the concurrent estimation of multiple variance parameters within stock
> assessments. For `r sp`, this includes the estimation of the variability
> associated with time-varying selectivity ($\Phi$), $\sigma_R$, extra
> standard deviation parameters on index data, and Dirichlet-multinomial
> parameters $\theta_{\text{fish}}$ and $\theta_{\text{surv}}$. In this
> assessment, $\Phi$ and $\sigma_R$ are input as fixed parameters because
> Stock Synthesis uses penalized likelihood and therefore is not formulated
> to estimate random effects. Additionally, estimation of these variance
> parameters using MCMC requires the specification of hyperpriors for which
> there has been little research. The Laplace approximation
> [@ThorsonHicksEtAl2015] was investigated as an alternative means to
> estimate these parameters. However, estimates from this method were large
> and simulation shows them to be biased high. Additional research still
> in its infancy suggests that stock assessment frameworks with the ability
> to estimate random effects internally are better at estimating
> autocorrelated processes than random processes. Next steps for the JTC
> include fitting Stock Synthesis to these same data sets to determine
> best practices when variance parameters cannot be estimated and fitting
> a wide variety of stock assessment frameworks to data when multiple random
> processes are present in the true dynamics.*

> *The Management Strategy Evaluation (MSE) framework for `r sp` creates
> considerable advantages for examining recruitment. The stock assessment
> model in the MSE is written in Template Model Builder (TMB), which
> provides efficient estimation of random effects using the Laplace
> approximation, while being parameterized to mimic many (but currently not
> all) of the pertinent features of Stock Synthesis used in this assessment.
> Thus, the performance of using restricted maximum likelihood to estimate
> $\sigma_R$ [@Thorson2019] can be investigated in terms of management as
> well as statistical performance. Research projects using the MSE framework
> are underway to evaluate the robustness of recruitment modeling
> assumptions and the advantages of including environmentally-driven
> recruitment indices on management performance and uncertainty.  Research
> (under review) by Dr.~Cathleen Vestfals and colleagues at the Northwest
> Fisheries Science Center has identified specific climate drivers associated
> with `r sp` early life-history stages and recruitment and is being used to
> select which environmental variables to fit as an index of recruitment
> within the stock assessment model. Further development of
> environmentally-driven recruitment indices using updated environmental
> predictions is also underway. The utility of fitting to a recruitment index
> will be investigated in terms of forecasting skill and management
> performance within the MSE by the MSE working group.*

> *The number of stock assessment frameworks written in TMB or other
> platforms that allow for the estimation of random effects is increasing.
> These frameworks, specifically the Woods Hole Assessment Model (WHAM;
> @StockMiller2021) and State-Space Assessment Model (SAM;
> @NielsenBerg2014) are both peer reviewed and currently being used for
> management. The JTC has fit WHAM to data on `r sp` and explored the
> estimates of several variance parameters that are currently only explored
> via sensitivity analyses in Stock Synthesis. Next steps include fitting
> data using SAM and using estimates from both frameworks as inputs to Stock
> Synthesis.*

> *The JTC is also following work being conducted by the International
> Council for the Exploration of the Sea (ICES) Methods Working Group which,
> among other things, is looking at meta-analytical approaches for
> estimating recruitment parameters. Results from this work could be used to
> develop informative prior distributions on key recruitment parameters.
> Deliverables were put on hold as a result of COVID-19 but the project
> continues to be making progress.*

2. **The SRG recommends exploring alternative methods to simulate recruitment
in the projections. Although Stock Synthesis currently does not have the
capability to characterize a different process other than the assumed lognormal
distribution, improvements such as drawing from past observations or using a
mixture distribution to simulate recruitment should be considered for modelling
platforms in the future.**

> *Response -- The JTC continues to explore approaches to make informed
> decisions about current and future recruitment in projections. The
> inclusion, and associated justification, of the age-1 index in the 2022
> and 2023 base model is one example of this (see
> Sections~\@ref(sec:data-acoustic-survey) and
> \@ref(sec:assessment-base-model)). Additionally, the JTC is working with
> Dr.~Kristin Marshall to further explore the fit of oceanographic and
> environmental variables identified by Dr.~Cathleen Vestfals as being
> informative about the early life history of `r sp` as indices of
> recruitment within Stock Synthesis. Ongoing research includes expanding
> the variables (originally only amalgamated from 1980--2010) to 2010
> onwards to create a single time series, and investigating relationships
> leading to better informed recent, current, and potential near-term
> forecast recruitment estimates.*

> *Available options in Stock Synthesis for recruitment during the
> projection period are the stock-recruitment curve, the
> stock-recruitment curve with a multiplier, and the mean across a
> user-defined time period. The MSE tool could be used to consider
> alternative recruitment distributional assumptions as future research.
> A member of the JTC is on the development team for NOAA's next
> generation stock assessment modeling platform (Fisheries Integrated
> Modeling System; FIMS), which ensures features such as recruitment
> forecast options will be taken into consideration. Plans are for the
> `r sp` stock assessment to be a test model.*

> *The JTC has requested DFO funding to collaborate with Australian, U.S.,
> and Canadian researchers on developing two potential approaches for
> developing an index of age-0 `r sp`. The first approach is based on the
> method of @SuthersWhiteEtAl2022, who proposed and simulation-tested a
> novel method for estimating growth and mortality of fish larvae based on
> size distributions. In 2022, Suthers visited NOAA's Southwest Fisheries
> Science Center to start applying the method to CalCOFI data (which
> include 1.3 million hake larvae) and compare results to estimates of
> recruitment from the last hake assessment [@JTC2022]. The second approach
> will apply a method proposed by \citet{HinchliffePepinEtAl2019} that
> relates the mortality/growth ratio of larval fish to the slope of the
> zooplankton size spectrum (which characterises the size distribution of
> zooplankton) to quantify the recruitment potential of larval `r sp`. The
> proposed work will support collaborations to work on both approaches, will
> utilise recent improvements in fitting size spectra to data
> [@EdwardsRobinsonEtAl2020], and aims to provide new information on `r sp`
> recruitment.*

> *We also include Figure~\@ref(fig:main-recruitment-scale-all) (as
> developed in the 2022 assessment) which presents a novel approach to
> visualise estimates of recruitment, to avoid misunderstanding of how large
> some recruitment events might be.*

3. `r sp` dynamics are highly variable even without fishing mortality. **The
SRG applauds the efforts of the JTC and the MSE Working Group to add
capabilities for specifying dynamic reference points within the assessment and
MSE platforms, and encourage those groups to work together and develop a
discussion of alternative reference points, including dynamic reference points,
for future SRG consideration.**

> *Response -- The JTC agrees that future reference point discussions
> stemming from simulation work, preferably through the MSE, would be
> beneficial. In particular, the JTC continues to have interest in exploring
> the utility of dynamic reference points. The MSE can now utilize dynamic
> reference points in management procedure scenarios, and Stock Synthesis
> models can now incorporate dynamic reference point capabilities into
> routine stock assessment output. In the coming year, the JTC plans to
> initiate simulations that explore alternative dynamic F-based target
> reference points coupled with static (equilibrium-based) biomass limit
> reference points in exploratory harvest control rule scenarios.*

> *Over the past year, the JTC has continued to engage in research
> activities and outreach related to dynamic reference points broadly, as
> well as specifically for `r sp`.  In particular, the JTC conducted a
> learning session at the summer JMC meeting to promote internal awareness
> and basic understanding of the key concepts, methods, and assumptions
> associated with dynamic reference point calculations. The JTC also engaged
> with external partners, the Western and Central Pacific Fisheries
> Commission science provider (Secretariat of the Pacific Community), to
> learn from their experience developing and applying dynamic reference
> points to operational highly migratory species assessments and management
> plans. Additionally, the JTC is contributing to, and following, updates to
> Canadian and United States national guidance documentation on the
> incorporation of prevailing environmental conditions into stock
> assessments and subsequent management advice (e.g., defining reference
> points).*


4. The SRG encourages work to develop a picture of the `r sp` reproductive
cycle both seasonally and at the life-time scale based on histological and
physiological measurements. In addition, the SRG notes that Canadian
samples and those from the winter research cruises should be included in the
maturity analysis. **The SRG encourages continued sampling and analysis to
improve understanding of the `r sp` reproductive cycle.**

> *Response -- `r sp` ovary samples were not collected over the past year,
> but plans include more sample collections in the coming years. Including
> Canadian samples in subsequent maturity analyses still remains a goal, but
> barriers (lab training, capacity, and moving bio-samples across the border)
> still remain. Research is in-progress by Melissa Head (NWFSC) focusing on
> temporal and spatial trends in hake reproduction. The analysis will include
> over a decade of maturity samples, spanning much of the U.S. West Coast.
> The project aims to evaluate how interannual changes affect size and age at
> maturity across a latitudinal gradient and how the timing of spawning and
> rate of skip spawning differs spatio-temporally. A presentation summarizing
> progress to date and future plans is planned for the SRG meeting.*

> *Research being led by Adam Luckenbach at the Northwest Fisheries Science
> Center looking at physiological indices of fish reproductive and metabolic
> status is expected to bolster the current practice of using gonadal
> histology alone for surveyed `r sp` and provide important data to more
> accurately determine the reproductive cycle of females. Data generated to
> date indicate that two types of lipids, triacylglycerols and
> phospholipids, in the livers of `r sp` are inversely related and
> predictive of sexual maturity in females. Levels of these lipids are also
> considerably shifted when aborted, atretic ovarian follicles are observed,
> suggesting that lipid levels may be predictive of skipped spawning, which
> can reduce the effective female spawning biomass. Data analyses will
> continue in 2023. New developments are expected to inform maturity in
> future `r sp` stock assessments.*

5. {\bf The SRG also recommends continuing to conduct the following sensitivities:
steepness, natural mortality, $\sigma_R$ , excluding the age-1 index, alternative standard
deviations for time-varying selectivity, and down-weighting fishery age-composition
data.}

\emph{Response -- The JTC has conducted all of the requested sensitivities (and many
  others) and provides summaries in written (Section~\@ref(sec:assessment-sensitivity-analyses}),
  tabular (beginning with Table~\@ref(tab:main-parameter-estimates-sens-1}), and
  graphical (beginning with Figure~\@ref(fig:main-biomass-base-alternative-1}) formats in
  this document.}

6. Based on the preliminary results shown, previous assessments have correctly predicted an
increase or decrease in recruitment and female spawning biomass in subsequent years, although
the projections are usually less definitive than the current base model results. Given that
this analysis provides some confidence in the current expectations of continued stock
decline, {\bf the SRG recommends that the JTC continue to explore and refine this
analysis for future assessments. The SRG encourages the JTC to explore, with the
JMC and AP, the value of a threshold for specifying the probability of projected
declines or increases of the stock in future assessments.}

\emph{Response -- The JTC has again updated this analysis
  to continue comparing estimates from the current base model with forecasts from
  previous assessments
  (Figures~\@ref(fig:main-historical-1}--\@ref(fig:main-historical-retro-bforty-all}).
  Related, the JTC is continuing to explore options for improving recruitment
  estimation and predictions (see Responses~1--4 and~7).}

\emph{The JTC has not had an opportunity to meet with JMC, AP, or the MSE working group
  to explicitly explore threshold values for specifying the probability of projected
  declines or increases of the stock in future assessments. This endeavor is well suited
  for upcoming MSE-related performance metrics discussions.}


7. The SRG notes that there are currently multiple strong cohorts in the stock
where previously there was only one strong cohort during the period of sample
collection for the ageing error matrix that supports the assessment model. {\bf Based
on this observation, the SRG recommends that an ageing error study using samples
collected during the past decade be conducted in conjunction with the Committee
of Age Reading Experts (CARE).}

\emph{Response -- An ageing error study in conjunction with CARE has commenced, including
  planned sample exchanges between United States and Canada ageing labs. However, a full exchange
  remains on hold due to difficulties with permits to send biological specimens across the border.}

8. {\bf The SRG recommends that historical sources of data be investigated to
determine whether they can be used to supplement the weight-at-age matrix},
including unaged otolith samples (and associated data) from the 1970s that may
be available in the Burke Museum in Seattle.

\emph{Response -- The JTC has conducted analyses previously showing that small changes to
  historical data have little relevance to current management quantities of interest. So at this time,
  the JTC does not expect small amounts of historical weight-at-age data to significantly alter
  stock assessment results used for management decisions. The JTC has not had the opportunity to
  visit the Burke Museum in Seattle to ascertain whether `r sp`\ age structures are available and
  in a usable state.}

9. Uncertainty in weight-at-age is not accounted for in the stock assessment
and a five-year average of recent observations is used for all years of the
projections. {\bf The SRG requests that the JTC explore alternative methods for
forecasting weight-at-age and evaluate whether they can improve projections.}

\emph{Response -- It is important to capture key, mechanistic, and/or stochastic population processes
  in stock assessment projections to sufficiently characterize levels of prediction uncertainty
  that are consistent with available information to adequately contextualize metrics used to aid
  management decisions. Likewise, it is as important to evaluate the basic population-dynamics
  assumptions used in such projections. Recent, current, and future recruitment are perhaps the most
  influential sources of uncertainty in stock assessment projections. As a result, the JTC has
  prioritized research on recruitment, including supporting analyses and other related analyses
  mentioned in this section. Over the next few years, the JTC plans to work with the MSE working group
  on a newly funded research project aimed at incorporating environmentally-driven growth into the
  operating model and testing consequences of climate-driven changes in recruitment, growth,
  and movement concomitantly.}

\emph{Empirical weight-at-age data indicate inter-annual variation in `r sp`\ growth, and this variation could
  be related to individual cohort effects (e.g., large cohorts have a negative growth influence on
  adjacent cohorts). The JTC has future plans to explicitly evaluate these relationships using random effects
  models to partition the variance components (year and cohort) in available weight-at-age data and to explore
  spatial patterns \citep{Indiveroetal2023}. This work could rely or build upon research currently in progress
  by a graduate student looking at variation in `r sp`\ weight-at-age data.
  The JTC also plans to explore new weight-at-age forecasting capabilities
  in Stock Synthesis (once fully tested). A simulation experiment that evaluates the influence of variable
  weight-at-age data relative to other sources of variance in stock assessment projections (e.g., recruitment)
  would also be useful. Until this work is completed, the JTC continues to use
  a recent five-year average in the projection period because it is consistent with recent data
  (Figures~\@ref(fig:main-empirical-weight-at-age} and~\@ref(fig:main-weight-at-age-lines}).
  This assumption is consistent with what is allowable within other commonly used stock assessment
  frameworks that accommodate time-varying dynamics.}


10. The parameter weighting the acoustic survey age samples was often estimated near the
upper bound of 1.0 and could not upweight the age samples. Investigations during the
SRG meeting showed that the posterior distribution of the parameter may have some
probability of upweighting the age samples from the base assessment inputs, although
likely had little difference on stock assessment outcomes. {\bf The SRG encourages the JTC
to consider methods to determine the maximum input sample size for the survey age
compositions. Previous work of \citet{StewartHamel2014} may be useful for this
purpose.}

\emph{Response -- The JTC concurs that determining maximum input sample sizes, as well as
  relative maximums across years, is a worthwhile endeavor. Determining appropriate input
  samples sizes for composition data is a long-standing issue with much debate. Progress made for
  `r sp`\ will undoubtedly provide useful for stock assessment more broadly.  The JTC has yet to
  undertake any specific analyses investigating input sample sizes. Researchers at the
  Alaska Fisheries Science Center have recently begun similar inquires, indicating that a collaborative
  approach may be mutually beneficial.}

11. The use of high-performance computing (e.g., a dedicated server or cloud computing)
allowed for the complete set of assessment results to be characterized using MCMC at a
minimal cost. {\bf The SRG recommends future use of high-performance computing to
provide complete and thorough assessment results in a timely manner.}

\emph{Response -- Resources were made available for the JTC to use a new high-performance computing
   network server with 80 processors to complete all model runs (bridging, base, sensitivity, retrospectives, and
   forecasts).
   Another high-performance server unit and two high-performance laptops have also been acquired for
   completing the `r sp`\ assessment.  These resources are used for data preparation, diagnostic examination,
   running test models, and exploring alternative model configurations.}

\emph{A new server was purchased and used to run all the models and for running the software that builds
  the document. The server has 80 Intel Xeon Gold CPUs and 128 GB of RAM and is running Ubuntu Linux
  version 22.04.1 LTS which was the newest stable version at the time of writing. The server was set
  up with user account for each JTC member, with a remote desktop server (X-Remote
  Desktop Protocol; XRDP) running for easy access. All connections were through a 4096-bit passwordless
  Secure SHell (SSH) and the server was otherwise locked down from a security standpoint. The entire server
  is automatically backed up on a mirrored RAID device once per day, with model input
  files also backed up to a Google drive. If everything were lost the models could be re-run very quickly
  and the document regenerated in full.}

\emph{Scripts were written in the Bash shell scripting language to allow operating system level control
  and monitoring over parallel model runs. Each run was also parallelized internally with 16 chains
  per model; that parallelism was controlled from within R using the {\tt future} and {\tt furrr} packages.
  With each model needing 16 CPUs, the JTC were able to run 4 models at a time, taking up 64 CPUs and
  leaving 16 available for use in writing and building the document. The total runtime for these models
  is now on the order of 1-3 hours, depending on the CPU and memory load on the server at the time.}

\emph{The server setup allowed all JTC members to work together in a way not possible before. This integrated
  setup will ensure an ideal workflow in the coming years, with a centralized system housing all model
  runs and document software.}


12. The SRG appreciates the investigation of alternative model structures, including
alternative modelling platforms. {\bf The SRG encourages the JTC to continue these types
of investigations.}

\emph{Response -- The JTC continues to explore the implementation of a hake-like assessment in WHAM
  and SAM, in addition to the
  custom TMB estimation model used in the MSE, to evaluate the impact of
  platform-specific configurations, assumptions, and capabilities.}


13. {\bf The SRG appreciates the dedication and teamwork displayed by the JTC in
producing the best available scientific information and advice on the Pacific
Hake stock during the COVID-19 pandemic.}

\emph{Response -- Teamwork and collaboration is an attribute of great interest
  and pride within the JTC, and we believe it is fundamental to successfully achieving
  the science objectives as outlined in the Agreement.}

