#!/bin/bash

rm beamer-hake-sensitivity.log 2> /dev/null
rm beamer-hake-sensitivity.out 2> /dev/null
rm beamer-hake-sensitivity.tex 2> /dev/null
rm beamer-hake-sensitivity.aux 2> /dev/null
rm beamer-hake-sensitivity.aux 2> /dev/null
rm beamer-hake-sensitivity.snm 2> /dev/null
rm beamer-hake-sensitivity.nav 2> /dev/null
rm beamer-hake-sensitivity.toc 2> /dev/null
rm *.pdf 2> /dev/null
rm -rf figures
rm -rf knitr-cache
