start Rscript -e "source('R/all.R');build(T,T,T,model.name='2019.03.00_base')"
start Rscript -e "source('R/all.R');build(T,T,F,model.name='2019.03.52_fecundity')"
start Rscript -e "source('R/all.R');build(T,T,F,model.name='2019.03.53_fecundity')"
start Rscript -e "source('R/all.R');build(T,T,F,model.name='2019.03.54_fecundity')"
start Rscript -e "source('R/all.R');build(T,T,F,model.name='2019.03.55_fecundity')"
start Rscript -e "source('R/all.R');build(T,T,F,model.name='2019.03.56_fecundity')"
start Rscript -e "source('R/all.R');build(T,T,F,model.name='2019.03.57_fecundity')"
start Rscript -e "source('R/all.R');build(T,T,F,model.name='2019.03.58_fecundity')"
