#!/bin/bash

find . -name "*.aux" -type f -exec rm {} +
find . -name "*.bbl" -type f -exec rm {} +
find . -name "*.blg" -type f -exec rm {} +
find . -name "*.dvi" -type f -exec rm {} +
find . -name "*.log" -type f -exec rm {} +
find . -name "*.lof" -type f -exec rm {} +
find . -name "*.lot" -type f -exec rm {} +
find . -name "*.ps" -type f -exec rm {} +
find . -name "*.toc" -type f -exec rm {} +
find . -name "*.out" -type f -exec rm {} +
find . -name "*.upa" -type f -exec rm {} +
find . -name "*.upb" -type f -exec rm {} +

