# Overview

## Summary -- catches

* TAC (adjusted for carryovers) for `r end_yr-1` was `r last_yr_tac` t
* Coastwide catch in `r end_yr-1` was `r last_yr_landings` t  -- near the
time series average catch
* Attainment in the U.S. was `r last_yr_us_attained`% of its quota
  (`r paste0(ifelse(last_2yr_us_attained_diff < 0, "down", "up"))`
  `r abs(as.numeric(last_2yr_us_attained_diff))`% from last year)
* Attainment in Canada was `r last_yr_can_attained`% of its quota
  (`r paste0(ifelse(last_2yr_can_attained_diff < 0, "down", "up"))`
  `r abs(as.numeric(last_2yr_can_attained_diff))`% from last year)

## `r assess_yr` base model structure

* The `r assess_yr` model is effectively equivalent to the  `r last_assess_yr` model (unchanged structure and results) to the start of 2025.
* Model parameters are effectively the same for `r assess_yr` and `r last_assess_yr`.
* The same version of Stock Synthesis was used as last year.
* The `r assess_yr` model only includes updated 2025 total coast-wide catch data.
* Often referred to as a catch-only projection style of assessment.

## Justification for `r assess_yr` base model structure
* The option of adding another year of fisheries age data, without the 2025 survey data, could lead to potentially misleading results.
\item[]
* The option of using the `r last_assess_yr` model projections as the basis for 2026 status could only be an approximation at best.
\item[]
* Thus, the catch-only projection option was deemed the most applicable for this year, because it bases 2026 management advice
on the approved `r last_assess_yr` assessment and uses the exact 2025 total catch for a projection.

## `r assess_yr` base model recruitment assumptions

* The use of a fixed recruitment assumption maintained from 2023 onwards

  * Results in three years of relatively low recruitment leading into biomass at the start of 2026
  * Four years of low recruitment leading into single year biomass forecasts for the start of 2027

* No standard set of sensitivities were completed for this year, refer to 2025 assessment

* A few alternative sensitivity runs were evaluated (separate presentation) to:

  * Explore the impact of the fixed recruitment assumption
  * Explore the tradeoffs between fishery age composition data and survey index data

## `r assess_yr` base model projections
* A single year was projected forward from the 2026 base model to get biomass at the start of 2027

* This was done because:

  * The assumption of not using recruitment deviations during the
recent and forecast periods is not a feasible long-term model assumption because the median
recruitment is too low to sustain the population in perpetuity. Forecasting further
years ahead will exacerbate this and lead to unrealistic results given past levels of
Pacific Hake recruitment.
  * The models in the 2024 and 2025 assessments both estimated a stock biomass somewhat
larger than the biomass index from the 2023 survey. Inclusion of the 2025 survey biomass
index would have helped to determine the validity of this overfitting. Without the
2025 survey biomass index, it was deemed pragmatic to not overextend the forecasts
too far ahead from 2023 survey.

## Main conclusions

* Reduction in spawning biomass from `r last_assess_yr` to `r assess_yr`
* The median estimate of `r end_yr` relative spawning biomass is
  `r curr_depl_median`% (with 95% interval from `r curr_depl_lower`%
   to `r curr_depl_upper`%)
* The 2023, 2021, and 2020 cohorts make up a large fraction of coastwide catches
  - 2014 and 2016 cohorts estimated to be above average
  - 2015, 2018, and 2019 cohorts estimated to be below average
  - 2020 cohort estimated to be slightly above average
  - 2021 cohort near the size of the 2014 cohort
  - 2022 cohort estimated to be very small
  - 2023 onwards assumed to be median cohort sizes (relatively low)
\pause
* Default harvest rule estimated median catch limit for `r min(forecast_yrs)`
  is `r ct_limit_quantiles["median"]` t (with 95% interval from
  `r ct_limit_quantiles["lower"]` to `r ct_limit_quantiles["upper"]` t)
  
## Key observations

Stock assessment model

* Catch increased from last year, now near the time series average
* Recent age composition data (up to 2022) indicates increasing biomass
* Recent acoustic survey data (up to 2023) indicates decreasing biomass
* Combined, population trend relatively stable over last few years
* Stock status is above `r b_40`, with 80% probability 

Outside the assessment model

* Indication of low overall hake biomass from preliminary 2025 survey estimates
* Indication of good recruitment for 2023 cohort, but assessment assumes median levels
* Indication of high overall hake biomass from fishery age compositions
* Combined, unknown until next full assessment
* Economics of fishing not sustainable in areas
