# Review

## `r assess_yr` base model only uses updated catch data

* The `r assess_yr` model only includes updated 2025 total coast-wide catch data.
* Will be discussed in Assessment presentation.
* Available data are presented here for information.

## Year in review
```{r catch-change}

last_yr_catch <- tail(last_5_yrs_total_ct, 1)
penult_yr_catch <- tail(last_5_yrs_total_ct, 2)[1]
pchangecatch <- percent(abs((last_yr_catch - penult_yr_catch)) / penult_yr_catch)
pchangecatch <- ifelse(last_yr_catch > penult_yr_catch,
                       paste0(pchangecatch, " increase"),
                       paste0(pchangecatch, " decrease"))

rank_catch_last_year <- rank(base_model$catch$Obs * -1) |>
  tail(1) |>
  ordinal()

# If odd year, create survey text. If even, create "No survey this year"
# text. For 2026 doing a manual bullet point below.
surv_text <- ifelse(last_data_yr %% 2,
                    paste0(last_survey_yr,
                           " acoustic survey biomass estimate was ",
                           last_survey_yr_biomass,
                           " Mt (",
                           as.numeric(last_factor_penult) * 100,
                           "% of ",
                           penult_survey_yr,
                           " estimate)."),
                    paste0("No survey was performed in ",
                           last_assess_yr,
                           "."))
```

* `r last_assess_yr` TAC, adjusted for carryovers, was `r last_yr_tac` t.
* Canadian and U.S. fisheries predominantly started in April and May,
respectively.
* `r rank_catch_last_year` highest coast-wide catch.
* `r pchangecatch` in catch from last year.
* No Canadian joint-venture fishery.
* Highest proportion at age by sector
  - Age-`r us_age_1_prop_age_cp` fish in U.S. catcher-processor sector,
  - Age-`r us_age_1_prop_age_ms` fish in U.S. mothership sector,
  - Age-`r us_age_1_prop_age_shore` fish in U.S. shoreside sector,
  - Age-`r max_freezer_trawler_age_prop_age` fish in Canadian freezer-trawler
sector, and
  - Age-`r max_shoreside_age_prop_age` fish in Canadian shoreside sector.
* 2025 acoustic survey biomass estimate was 652,000~t, but **not** used in this assessment.


## Summary of data sources used

<!-- For 2026 most of these are shifted to -2 -->
* Annual catch (`r start_yr`--`r end_yr - 1`)
* Age-1$^+$ compositions (1975--`r end_yr - 2`)
* Acoustic survey (`r survey_start_yr`--`r survey_end_yr`)
  - Biomass index of age 2$^+$ (t)
  - Age-2$^+$ age compositions
  - Recall the relative index of age-1 fish was **not** used in 2025 assessment
* Ageing imprecision and biases
  - double reads
  - blind reads
* Weight-at-age (1975--`r end_yr - 2`)
* Time-varying maturity ogives

