# Source this file to apply changes.

# Reference points needed throughout the document
# If they contain stars, they are RMarkdown versions,
# LaTeX ones are labelled as such (end in '_for_latex_table')
create_data_hake("f_35", "*F*~35%~")
create_data_hake("f_40", "*F*~40%~")
create_data_hake("f_40_for_latex_table", "\\textit{F}\\textsubscript{40\\%}")
create_data_hake("f_45", "*F*~45%~")
create_data_hake("f_40_40_10", "*F*~40%~--40:10")
create_data_hake("f_40_40_10_for_latex_table", "\\textit{F}\\textsubscript{40\\%}--40:10")
create_data_hake("f_45_40_10", "*F*~45%~--40:10")
create_data_hake("fspr_35", "*F*~SPR=35%~")
create_data_hake("fspr_40", "*F*~SPR=40%~")
create_data_hake("fspr_40_for_latex_table", "\\textit{F}\\textsubscript{SPR=40\\%}")
create_data_hake("fspr_40_bold_for_latex_table", "\\textbf{\\textit{F}}\\textsubscript{\\textbf{SPR=40\\%}}")
create_data_hake("fspr_45", "*F*~SPR=45%~")
create_data_hake("fspr_50", "*F*~SPR=50%~")
create_data_hake("fspr_40_10", "*F*~SPR=40%~--40:10")
create_data_hake("fspr_40_10_for_latex_table", "\\textit{F}\\textsubscript{SPR=40\\%}--40:10")
create_data_hake("fspr_40_10_noit", "F~SPR=40%~--40:10")
# Three stars each side of text means the text will be both bold and in italics
create_data_hake("fspr_40_bold", "***F***~**SPR=40%**~")

create_data_hake("b_10", "*B*~10%~")
create_data_hake("b_10_for_latex_table", "\\textit{B}\\textsubscript{10\\%}")
create_data_hake("b_25", "*B*~25%~")
create_data_hake("b_25_for_latex_table", "\\textit{B}\\textsubscript{25\\%}")
create_data_hake("b_40", "*B*~40%~")
create_data_hake("b_40_for_latex_table", "\\textit{B}\\textsubscript{40\\%}")
create_data_hake("b_40_bold_for_latex_table", "\\textbf{\\textit{B}}\\textsubscript{\\textbf{40\\%}}")
create_data_hake("bspr_40", "*B*~SPR=40%~")
create_data_hake("bspr_40_for_latex_table", "\\textit{B}\\textsubscript{SPR=40\\%}")
create_data_hake("bspr_40_10_noit", "B~SPR=40%~--40:10")

create_data_hake("spr_40", "SPR~40%~")
create_data_hake("fishing_rate", "(1 - SPR(*F*))/(1 - SPR~40%~)")
create_data_hake("rel_fishing_intensity_for_latex_table", "(1 - SPR)/(1 - SPR\\textsubscript{40\\%})")
create_data_hake("b_0", "*B*~0~")
create_data_hake("b_0_for_latex_table", "\\textit{B}\\textsubscript{0}")
create_data_hake("b_0_bold_for_latex_table", "\\textbf{\\textit{B}}\\textsubscript{\\textbf{0}}")
create_data_hake("r_0", "*R*~0~")
create_data_hake("r_0_for_latex_table", "\\textit{R}\\textsubscript{0}")
create_data_hake("f_msy", "*F*~MSY~")
create_data_hake("b_msy", "*B*~MSY~")
create_data_hake("b_msy_for_latex_table", "\\textit{B}\\textsubscript{MSY}")
create_data_hake("f_spr", "*F*~SPR~")
