#!/bin/bash

rm JTC-data.log 2> /dev/null
rm JTC-data.out 2> /dev/null
rm JTC-data.tex 2> /dev/null
rm JTC-data.aux 2> /dev/null
rm JTC-data.aux 2> /dev/null
rm JTC-data.snm 2> /dev/null
rm JTC-data.nav 2> /dev/null
rm JTC-data.toc 2> /dev/null
rm *.pdf 2> /dev/null
rm -rf knitr-figs
rm -rf knitr-cache
