#!/bin/bash

rm beamer-hake-data.log 2> /dev/null
rm beamer-hake-data.out 2> /dev/null
rm beamer-hake-data.tex 2> /dev/null
rm beamer-hake-data.aux 2> /dev/null
rm beamer-hake-data.aux 2> /dev/null
rm beamer-hake-data.snm 2> /dev/null
rm beamer-hake-data.nav 2> /dev/null
rm beamer-hake-data.toc 2> /dev/null
rm *.pdf 2> /dev/null
rm -rf figures
rm -rf knitr-cache
