\clearpage

\chapter{Scientific Review Group (SRG) requests from
  \Sexpr{assess_yr} meeting}
\label{chap:srg-requests}

This appendix summarizes results produced in response to
the Scientific Review Group requests made during the virtual meeting to be held
from 8th to 12th February 2023.

% Commenting these out to not encourage requests!

\section{Day 1}

{\bf Request 1:}

Provide ...

{\bf JTC Response:}

The JTC produced ...

\clearpage % Needed to make footers correct
