<<decisions-spr-table, results='asis', echo=FALSE>>=
decision_table(base_model,
               xcaption = paste0("Forecast quantiles of \\fishname\\ ",
                                 "relative fishing intensity (1-SPR)/(1-SPR\\subscr{40\\%}), ",
                                 "expressed as a proportion, ",
                                 "for the ",min(forecast_yrs),"--",max(forecast_yrs)-1," catch ",
                                 "alternatives presented in ",
                                 "Table~\\ref{tab:es-decisions-biomass}. Values greater than ",
                                 "1 indicate relative fishing intensities greater than ",
                                 "the $\\Fforty$ harvest policy calculated using baseline ",
                                 "selectivity."),
               xlabel = "tab:es-decisions-spr",
               font.size = 11,
               space.size = 12,
               type = "spr",
               placement = "tbp")
@

<<main-tv-selex-uncertainty, fig.height=8, fig.width=8, is.fig = TRUE, alt.text = "This figure shows selectivity by year plots with medians and 0.95 credible intervals">>=
plot_multiple_tv_selex_unc(base_model, n_col = 2)
@
