\RequirePackage{pdfmanagement-testphase}
\DocumentMetadata{testphase=phase-II, uncompress, pdfstandard=A-2U, lang=en-US}

\documentclass[12pt]{book}
%% Allows the numbering of figures/tables to be unique witin a section
%%  so that clicking table d in the executive summary takes you there, and not
%%  to the fourth table in the main-tables section
\usepackage{chngcntr}

\usepackage{../hake}
%% title gives 'Appendix A', not
%% just 'A', but doesn't seem to work, may need article class,
%% but need to see appendix manual.
\usepackage[titletoc,title]{appendix}

%% for bold math symbols
\usepackage{bm}
\usepackage{cite}
%% need array when specifying a ragged right column:
%%  >{\raggedright\arraybackslash}{p2in}.
\usepackage{longtable,array}
%% \renewcommand{\chaptername}{Appendix}
%% \addto\captionsenglish{\renewcommand\chaptername{Part}}
%% For figures in chapter subdirectories
\usepackage{import}
%% Allow figures and tables to be controlled better (avoid the floating).
\usepackage{float}

%% Allows symbols inside a verbatim-type section
\usepackage{alltt}
%% For code listing with syntax highlighting
\usepackage{listings}
%% For inclusion of figures
\usepackage{graphicx}
%% verbatim package allows blocks with special characters to be shown easily.
\usepackage{verbatim,fancyvrb}
%% Used innecessary for decision tables
\usepackage{multicol}
%% Used in decision tables
\usepackage{multirow}
%% Used in executive summary tables
\usepackage{booktabs}
%% Allows the citation to reflect the number of pages in the document.
\usepackage{lastpage}
%% So paragraphs will have a blank line between them.
\usepackage[parfill]{parskip}
\setlength{\parskip}{12pt}

\usepackage[yyyymmdd]{datetime}
\renewcommand{\dateseparator}{--}
\newdateformat{usvardate}{\monthname[\THEMONTH] \ordinal{DAY}, \THEYEAR}

%% For fitting the backscatter plot
\usepackage{graphicx}
\usepackage[export]{adjustbox}

%% Use the following codes for references within the document.
%% Example of label format - fig:catch
%%   chap: chapter - for Appendices
%%    sec: section
%% subsec: subsection
%%   fig: figure
%%    tab: table
%%     eq: equation
%%    lst: code listing
%%    itm: enumerated list item
%%    app: appendix subsection
%% Something to do with spaces after macros.
\usepackage{xspace}
%% So links will anchor at figure, not caption
\usepackage{hypcap}
%% For two-panel plots
\usepackage{subfig}
%% For display of pseudocode
\usepackage{algorithm}
%% For display of pseudocode
\usepackage{algpseudocode}
%% For display of pseudocode
\usepackage{linegoal}
\newcommand*{\TitleFont}{
      \usefont{\encodingdefault}{\rmdefault}{b}{n}
      \fontsize{20}{24}
      \selectfont}

%% A \Let command for defining assignments within the algorithmic environment
%%  which supports automatic indentation when the second argument is too long
%%  to fit on one line
\newcommand*{\Let}[2]{\State #1 $\gets$
\parbox[t]{\linegoal}{#2\strut}}
%% A \State command that supports automatic indentation when the argument's
%%  content is too long to fit on one line
\newcommand*{\LongState}[1]{\State
\parbox[t]{\linegoal}{#1\strut}}

%% To remove spacing between list items [noitemsep,nolistsep]
\usepackage{enumitem}
\newlist{longitem}{enumerate}{5}
\setlist[longitem,1]{label=\arabic*)}
\setlist[longitem,2]{label=\alph*)}
\setlist[longitem,3]{label=\roman*)}
\setlist[longitem,4]{label=\arabic*)}
\setlist[longitem,5]{label=\alph*)}

\definecolor{rowclr}{RGB}{255, 192, 203}
%% For centering with fixed width column or right cell values in a tabular
\newcommand{\PreserveBackslash}[1]{\let\temp=\\#1\let\\=\temp}
\newcolumntype{C}[1]{>{\PreserveBackslash\centering}p{#1}}
\newcolumntype{R}[1]{>{\PreserveBackslash\raggedleft}p{#1}}
\newcolumntype{L}[1]{>{\PreserveBackslash\raggedright}p{#1}}

\newcommand{\sQuote}[1]{`#1'}
\newcommand{\dQuote}[1]{``#1''}
\newcommand{\eqn}[1]{\begin{equation}#1\end{equation}}
\newcommand{\gfrac}[2]{\genfrac{}{}{}{0}{#1}{#2}}

\newenvironment{codefont}{\fontfamily{pcr}\selectfont}{\par}

\lstset{
  language=R,
  numbers=left,
  frame=single,
  commentstyle=\color{dkgreen},
  basicstyle={\scriptsize\ttfamily},
  keywordstyle=\color{blue},
  %identifierstyle=\color{blue},
  stringstyle=\color{mauve},
  captionpos=t,
  showstringspaces=false,
  breaklines=true,
  breakatwhitespace=true,
  tabsize=3,
  caption=\getlstname,
}

%% Multi-line-cell in an xtable
%% syntax is \mlc{first line\\secondline}
\newcommand{\mlc}[2][c]{\begin{tabular}[#1]{@{}c@{}}#2\end{tabular}}
\newcommand{\fishname}{Pacific Hake}
\newcommand{\commonname}{Pacific whiting}
\newcommand{\sciencename}{Merluccius productus}
\newcommand{\simplename}{hake}
\newcommand{\surveyname}{Joint U.S. and Canadian Integrated Acoustic and Trawl Survey}
%% Needs to be done as $\Fforty$
\newcommand{\Fforty}{F_{\text{SPR}=40\%}}
\newcommand{\BSPRforty}{B_{\text{SPR}=40\%}}
%% Harvest control rule, \Ffortyten{} to have a space after
\newcommand{\Ffortyten}{$\Fforty$--40:10}
\newcommand{\Bforty}{B_{40\%}}
\newcommand{\Btwentyfive}{B_{25\%}}
\newcommand{\Bten}{B_{10\%}}
\newcommand{\Bzero}{B_{0}}
\newcommand{\Bmsy}{B_{\text{MSY}}}
\newcommand{\Fmsy}{F_{\text{MSY}}}
\newcommand{\Fspr}{F_{\text{SPR}}}

%% For subscripts and superscripts in text mode
\newcommand{\subscr}[1]{$_{\text{#1}}$}
\newcommand{\supscr}[1]{$^{\text{#1}}$}

\newcommand{\altshort}{alternative run}
\newcommand{\altlong}{alternative time-varying fecundity run}

%% Make counters so text isn't repeated
\newcounter{counter_research-needs}

%% Headers and footers
\lhead{}
\rhead{}

%% Tried to not have indent on disclaimer (but doesn't work):
%% \def\thanks#1{{\let\thefootnote\relax\footnote{#1.}\setcounter{footnote}{0}}}
\begin{document}
\emergencystretch 3em    % https://tex.stackexchange.com/questions/9107/how-can-i-make-my-text-never-go-over-the-right-margin-by-always-hyphenating-or-b
\counterwithin{figure}{section}
\counterwithin{table}{section}

<<load-everything, echo=FALSE,  message=FALSE, results='hide', warning=FALSE>>=
knitr::render_latex()
fig_width <- 7.5
fig_dpi <- 200
fig_align <- "center"
fig_pos <- "htb"
library(knitr)   # Needed else next line gives hidden error for the first run
                 # using knitr::knit("hake-assessment.rnw")
opts_chunk$set(dev = 'png',
               dpi = fig_dpi,
               fig.width = fig_width,
               fig.pos = fig_pos,
               collapse = TRUE,
               echo = FALSE,
               results = FALSE,
               message = FALSE,
               warning = FALSE,
               comment = "#>",
               results = 'hide',
               fig.path = 'knitr-cache/',
               cache.path = 'knitr-cache/',
               cache = TRUE)

# Data frame of alternative figure text to be populated by a knitr hook
alt_fig_text <- tibble::tibble()
# This is called every time a chunk is evaluated with alt.text in the chunk options
knit_hooks$set(alt.text = function(before, options, envir){
  if(before && options$is.fig){
    # Add first line of non-comment code and the alt text to a data frame
    code_chunk <- options$code
    # Remove leading whitespace from all lines
    code_chunk <- gsub("^[[:space:]]+", "\\1", code_chunk)
    # Remove all comment lines
    code_chunk <- code_chunk[!grepl("^#", code_chunk)]
    # Select the first line that is a function call
    code_chunk <- code_chunk[grepl("^[:a-zA-Z0-9_\\.]+\\(", code_chunk)]
    # Remove all instances of par() as they always comes before the function call
    code_chunk <- code_chunk[!grepl("^par\\(", code_chunk)]
    if(length(code_chunk)){
      alt_text <- ifelse(is.null(options$alt.text),
                         "Alt text not provided",
                         options$alt.text)
      alt_fig_text <<- bind_rows(alt_fig_text,
                                 c(code = code_chunk[1],
                                   text = alt_text))
    }
  }
  # Return NULL because anything else output here will be written into the TEX output
  NULL
})

# Default chunk options
opts_chunk$set(is.fig = FALSE)
opts_chunk$set(alt.text = "")

options(xtable.comment = FALSE)

source(here::here("R/all.R"))
if(!exists("base_model"))
  base_model <- readRDS("/srv/hake/models/2023/01-version/01-base-models/01-base/01-base.rds")
#source(file.path(rootd_doc, "load-models.R"))
#source(file.path(rootd_r, "custom-knitr-variables.R"))
@

%% Title page and author references page
\thispagestyle{empty}

\title{\TitleFont Status of the \fishname\ (whiting) stock in U.S. and Canadian
  waters in \Sexpr{assess_yr}
%% Uncomment for DRAFT:
\\ ~\\ DRAFT for submission to Scientific Review Group\thanks{\noindent \disclaimer}
\\ ~\\ ~\\ \pdftooltip{\includegraphics[width=4in]{../main-figures/hake-picture}}{Drawing of a \fishname}}

\author{Joint Technical Committee of the \fishname/Whiting Agreement \\ Between
  the Governments of the United States and Canada}

\date{\usvardate \today}

\maketitle

\newpage

\pagenumbering{arabic}
\setcounter{page}{2}

%% Authors page
This document reports the collaborative efforts of the official U.S. and
Canadian members of the Joint Technical Committee, and others that
contributed significantly.

Authors of this document are (all authors contribute extensively so the order rotates annually):\\
\hspace{4ex}Aaron M. Berger\supscr{1} \\
\hspace{4ex}Chris J. Grandin\supscr{2} \\
\hspace{4ex}Kelli F. Johnson\supscr{3} \\
\hspace{4ex}Andrew M. Edwards\supscr{2} \\
\bigskip

\emph{\supscr{1}Northwest Fisheries Science Center, National Marine
  Fisheries Service, National Oceanic and Atmospheric Administration,
  U.S. Department of Commerce, 2032 SE OSU Dr. Bldg. 955, Newport, OR
  97365-5275, USA}

\emph{\supscr{2}Pacific Biological Station, Fisheries and Oceans Canada,
  3190 Hammond Bay Road, Nanaimo, B.C. V9T 6N7, Canada}

\emph{\supscr{3}Northwest Fisheries Science Center, National Marine Fisheries
  Service, National Oceanic and Atmospheric Administration, U.S. Department of
  Commerce, 2725 Montlake Blvd. East, Seattle, WA 98112-2097, USA}

%% Draft version
This DRAFT document is non-citable.

\newpage

%% Table of contents, etc.
\input{../preamble}
\setcounter{secnumdepth}{5} %% To number subsubheadings-ish

%% Executive summary number Tables a,b,c.
\renewcommand{\thetable}{\alph{table}}

\renewcommand{\thefigure}{\alph{figure}}
\renewcommand{\thesection}{\arabic{section}}
\renewcommand{\theequation}{\arabic{equation}}

\renewcommand{\bibsection}{\section{REFERENCES}\label{sec:references}}

\lfoot{
       DRAFT -- \fishname\ assessment \Sexpr{assess_yr}
       }
\rfoot{Section~\ref{sec:figures} -- Figures}
<<tester, child='tester.rnw'>>=
@
\clearpage

\end{document}
