\newpage

\rfoot{Tables}

# Tables {#sec:tables}

```{r catches-us, results = "asis", echo = FALSE}
table_catch(
  ct,
  inc_foreign_jv = TRUE,
  start_yr = start_yr,
  end_yr = end_yr - 1,
  country = "us",
  caption = paste0(
    "Annual catches of ", sp, " (t) in U.S. waters by fleet, ", start_yr,
    "-", last_data_yr, ". Tribal catches are included in the fleet totals. ",
    "Research catch includes landed catch associated with research-related ",
    "activities. Catch associated with surveys and discarded bycatch in ",
    "fisheries not targeting hake is not currently included in the table or ",
    "model."),
  font_size = 12,
  longtable = TRUE)
```

\clearpage

```{r catches-can, results = "asis", echo = FALSE}
table_catch(
  ct,
  inc_foreign_jv = TRUE,
  start_yr = start_yr,
  end_yr = end_yr - 1,
  country = "can",
  caption = paste0(
    "Annual catches of ", sp, " (t) in Canadian  waters by fleet, ",
    start_yr, "-", last_data_yr, "."),
  font_size = 12,
  header_font_size = 10,
  longtable = TRUE)
```


```{r main-landings-tac-table, results = "asis", echo = FALSE}
table_landings_tac(
  ct,
  start_yr = start_yr,
  end_yr = end_yr - 1,
  caption = paste0(
    sp,
    " landings and management decisions. A dash (--)  indicates the ",
    "management decision was either not specified or was unknown to the ",
    "authors at the time of this assessment."),
  font_size = 10,
  header_font_size = 8,
  longtable = TRUE) |> 
  landscape()
```

```{r main-sampling-history-table, results = "asis", echo = FALSE}
table_sampling_history(
  sampling_history_df,
  start_yr = start_yr_age_comps,
  end_yr = last_data_yr,
  caption = paste0(
    "Annual summary of U.S. and Canadian fishery sampling included in this ",
    "stock assessment by fleet. Majority of values are reported as number of ",
    "hauls but U.S. shore-based and Canadian shoreside fleets are reported ",
    "as the number of trips. A dash (--) indicates there was no sampled ",
    "catch. The number of fish with otoliths sampled per haul has varied ",
    "over time but is typically small."),
  font_size = 10,
  header_font_size = 8,
  longtable = TRUE)
```

\clearpage
