# SRG Requests

## Request 1 -- "Sample sizes for M, F, and U weight-at-age data"

```{r weight-at-age-sample-size, results = "asis"}
temp_waa <- weight_at_age_df |>
  dplyr::group_split(country) |>
  purrr::map_df(\(x) dplyr::group_by(x, country, year, sex, data_type) |>
    dplyr::count() |>
    tidyr::pivot_wider(
      names_sep = " ",
      values_from = n,
      names_from = c(sex, data_type),
      names_sort = TRUE,
      names_vary = "slowest",
      values_fill = 0
    ) |>
    dplyr::select(country, year, dplyr::starts_with(LETTERS))
  )
  kableExtra::kable(
    temp_waa |> dplyr::filter(country == "canada"),
    format = "latex",
    booktabs = TRUE
  ) |>
  kable_styling(font_size = 4.5)
```

## Request 1 -- "Sample sizes for M, F, and U weight-at-age data"

```{r weight-at-age-sample-size-us-1, results = "asis"}
kableExtra::kable(
  temp_waa |> dplyr::filter(country == "usa", year <= 1997),
  format = "latex",
  booktabs = TRUE
) |>
  kable_styling(font_size = 4.5)
```

## Request 1 -- "Sample sizes for M, F, and U weight-at-age data"

```{r weight-at-age-sample-size-us-2, results = "asis"}
kableExtra::kable(
  temp_waa |> dplyr::filter(country == "usa", year > 1997),
  format = "latex",
  booktabs = TRUE
) |>
  kable_styling(font_size = 4.5)
```

## Request 1 -- "Sample sizes for M, F, and U weight-at-age data"
```{r plot-weight-at-age-by-sex, out.height = "85%"}
wtaa_preds <- readRDS(fs::path("/srv/hake/other/tv", "weight-at-age-preds.rds"))
# Make figure
wtaa_preds |>
  dplyr::filter(year %in% c(last_data_yr - 5, last_data_yr)) |>
  ggplot2::ggplot(ggplot2::aes(
    x = age,
    y = est_weight,
    group = interaction(sex, year),
    colour = fyear,
    pch = sex
  )) +
  ggplot2::geom_line() +
  ggplot2::geom_point() +
  ggplot2::xlab("Age (years)") +
  ggplot2::ylab("Estimated mass (kg)")
```

## Request 1 -- "Sample sizes for M, F, and U weight-at-age data"
```{r plot-base-v-tv-maturity-ssb, out.height = "85%"}
m_names <- c("base", "sexed weight-at-age")
weight_at_age_model <- readRDS(
  fs::path(
    models_dir, "05-test-models",
    "72-tv-fecundity", "72-tv-fecundity.rds"
  )
)
plot_biomass(list(base_model, weight_at_age_model), model_names = m_names)
```