## Request 2 -- "on Figure G.11 add the data for proportion mature"

Description

* Below are two figures, one with empirical results for age 2 and another with
  empirical results for age 3. Data are included from non-ASHOP samples because
  that is what the curve is predicting. For each year (denoted on the smooth
  line) the points appear above or below the labeled point from the same year.
* We do not expect the points to overlap or lie on the line because the curve
  represents the marginal effect of temperature (e.g., predicted maturity from
  non-ASHOP samples collected from an average sample location on July 1).
* Why do the points appear to be offset by an intercept (e.g., the points for
  age 3 are above the predicted age 3 line)? This is because the marginal plot
  shown in G.11 uses July 1 as a reference day of year; and, for the non-ASHOP
  samples, the distribution of sample dates is skewed later (25% before July
  1/75% after). Changing the reference date from July 1 to a later date for
  age-3 fish would have the effect of shifting the curve up closer to the red
  points. The points are also affected by variable sampling effort year to year.
* In conclusion, we would never really expect the empirical estimates to
  perfectly match the model-based ones. Sampling varies across space and time,
  and the empirical estimates do not account for any of this variation.

