## Request 6 -- "Down weight the age-composition sample sizes"

A lambda value of 0.05 was multiplied by the age-composition likelihood
component to calculate the overall negative log likelihood to be minimized.

* DM fishery: 0.341 (base); 0.035 (lambda)
* DM survey: 0.942; 0.271
* DM ratio: 0.362; 0.129
* Extra SD survey: 0.313; 0.202
* Extra SD age-1 index: 0.385; 0.371
* Age Likelihood: 2144; 131
* Approximate run time: 2 hours; 17 hours

```{r plot-sur-fit-base-v-lambda-ssb, eval = TRUE}
m_names <- c("base", "lambda 0.05")
lambda_model <- readRDS(
  fs::path(
    models_dir, "05-test-models",
    "30-lambda-comps", "30-lambda-comps.rds"
  )
)
plot_survey_index_fits(base_model,
                         model_lst=list(base_model, lambda_model),
                         model_names = m_names,
                         survey_type = "age2",
                         rev_colors = TRUE,
                         leg_pos = c(0.75, 0.15),
                         xlim = c(1995, end_yr))
```
```{r plot-age1-fit-base-v-lambda-ssb, eval = FALSE}
plot_survey_index_fits(base_model,
                         model_lst=list(base_model, lambda_model),
                         model_names = m_names,
                         survey_type = "age1",
                         xlim = c(1995, end_yr),
                         ylim = c(0, 11),
                         leg_ncol = 2,
                         leg_font_size = 10,
                         leg_pos = c(0.25, 0.9),
                         y_breaks = seq(0, 11, by = 2),
                         rev_colors = TRUE)
```

```{r plot-base-v-lambda-ssb, eval = FALSE}
plot_biomass(list(base_model, lambda_model),
             model_names = m_names,
             ylim = c(0, 12),
             point_shape = ts_single_model_pointshape,
             leg_pos = c(0.75, 0.9))
```

```{r plot-rel-base-v-lambda-ssb, eval = FALSE}
plot_rel_biomass(list(base_model, lambda_model),
                 model_names = m_names,
                 ylim = c(0, 2.5),
                 alpha = 0.2,
                 point_shape = ts_single_model_pointshape,
             leg_pos = c(0.75, 0.9)) |>
  suppressWarnings()
```

```{r plot-rec-base-v-lambda-ssb, eval = FALSE}
plot_recdevs(list(base_model, lambda_model),
             model_names = m_names,
             line_color = ts_single_line_color,
             leg_pos = c(0.25, 0.95))
```

```{r plot-recabs-base-v-lambda-ssb, eval = FALSE}
plot_recruitment(list(base_model, lambda_model),
                 model_names = m_names,
                 inc_means = TRUE,
                 leg_pos = c(0.25, 0.95)) |>
  suppressWarnings()
```