## Request 4
**Create and present the plot showing the amount of each cohort in the catch over time (age on the x-axis). This plot has been created in the past. Please include the 1999, 2010, 2014, 2016, 2017, 2020, and 2021 cohorts.**

**Justification:** This plot shows the rate of removals of a cohort over time and how it compares across cohorts, which is helpful to understand the importance of a cohort to the fishery.

## Request 4 results

:::::: {.columns}
::: {.column width="50%"}
\
\

Estimated total catch from each cohort

* 1999 cohort (ages 1--`r last_data_yr - 1999`): `r f(max(cohort_cum_sum_1999))` t
* 2010 cohort (ages 1--`r last_data_yr - 2010`): `r f(max(cohort_cum_sum_2010))` t
* 2014 cohort (ages 1--`r last_data_yr - 2014`): `r f(max(cohort_cum_sum_2014))` t
* 2016 cohort (ages 1--`r last_data_yr - 2016`): `r f(max(cohort_cum_sum_2016))` t
* 2017 cohort (ages 1--`r last_data_yr - 2017`): `r f(max(cohort_cum_sum_2017))` t
* 2020 cohort (ages 1--`r last_data_yr - 2020`): `r f(max(cohort_cum_sum_2020))` t
* 2021 cohort (ages 1--`r last_data_yr - 2021`): `r f(max(cohort_cum_sum_2021))` t
:::

::: {.column width="50%"}
```{r jmc-cumulative-catch-cohorts, fig.height = 4, fig.width = 4, out.height = "85%"}

plot_cumulative_catch_cohorts(base_model)
```

:::
::::::

