# Request 7
**Extend the assessment model to incorporate data through 2025 and fit to fishery age compositions, acoustic survey biomass index, and acoustic survey age compositions. If this is not possible, or not preferable, please provide an explanation.**

**Justification:** This will provide insight into the likely outcomes from an assessment incorporating all of the 2025 data. 

## Explanation for not Extending

A catch-only projection is appropriate for the 2026 stock assessment for several reasons that complement the Introduction of the draft assessment document.

* The 2025 IWCPS acoustic survey biomass and age composition estimates were finalized only days before the assessment deadline (i.e., shortly before the SRG meeting) due to a 7-week delay caused by and external time constraint (U.S. federal government shutdown). Consequently, these data have not had the necessary review by the JTC or SRG. The 2025 IWCPS survey had significant survey design changes. Incorporating these data without proper review may result in assumptions that result in biased management advice. 

## Explanation for not Extending
* Including the 2025 fishery age compositions without including the 2025 survey biomass estimate (and age compositions) risks introducing significant biases that can reduce the efficacy of management advice. In recent years, a tension has been observed between age composition data (suggesting high recruitment from shifts to large proportions of young fish) and the acoustic survey biomass index (suggesting decreasing overall biomass).
\item[]
* The next full stock assessment should include the full complement of properly scrutinized data informing both cohort strengths and absolute biomass.

Therefore, it is not appropriate to run new base case models for management advice during the SRG that include 2025 age composition and 2025 IWCPS biomass estimates for several reasons:

## Explanation for not Extending
* There is insufficient time to properly review changes in new survey and trawl net designs (including selectivity and other nuances specific to the 2025 IWCPS) and then also evaluate how results from that review should be incorporated into the stock assessment.
\item[]
* There is insufficient time for proper implementation of review suggestions that often require comparing alternative approaches and identifying robust options.  
\item[]
* There is insufficient time to properly process all of the survey-dependent data products used in a full stock assessment (including maturity-at-age, weight-at-age, and appropriately catch-weighted fishery age compositions).
\item[]
* There is insufficient time to conduct the suite of sensitivities and all other diagnostic model evaluations required for a full stock assessment.


