\newpage

\rfoot{Introduction}

# Introduction {#sec:introduction}

The Joint U.S.-Canada Agreement for `r sp` (called the Agreement) was signed
in 2003, went into force in 2008, and was implemented in 2010.  The committees
defined by the Agreement were first formed in 2011, and 2012 was the first year
for which the process defined by the Agreement was followed. This is the
`r number_to_word(assess_yr - 2011, th = TRUE)` annual stock assessment
conducted under the Agreement process.

Under the Agreement, `r sp` (*`r science_name`*, also referred to as
`r common_name`) stock assessments are to be prepared by the Joint Technical
Committee (JTC) comprised of both U.S. and Canadian scientists and reviewed by
the Scientific Review Group (SRG) that consists of representatives from both
nations. Additionally, the Agreement calls for both of these bodies to include
scientists nominated by an Advisory Panel (AP) of fishery stakeholders.

The primary data sources for this assessment include an acoustic survey, annual
fishery catch, mean weight-at-age data, maturity-at-age data, as well as survey
and fishery age-composition data. The assessment depends primarily upon an
index of biomass from the acoustic survey for information on the scale of the
current population. Age-composition data provide additional information
allowing the model to resolve strong and weak cohorts. The catch is an
important source of information regarding changes in abundance and places a
lower bound on the available population biomass in each year.

This assessment is fully Bayesian, with the base model incorporating prior
information on several key parameters (including informative priors
on natural mortality, $M$, and steepness of the stock--recruitment relationship,
$h$) and integrating over parameter uncertainty to provide results that can be
probabilistically interpreted. From a range of alternate models investigated
by the JTC, a subset of sensitivity analyses are also reported to provide a
broad qualitative comparison of structural uncertainty with respect to the
base model (Section~\@ref(sec:assessment-sensitivity-analyses)). The model is implemented using
version `r ss_version` of the Stock Synthesis software [@MethotWetzel2013].
The `r assess_yr` base model is structurally similar to last year's model,
except the `r assess_yr` base model does not include estimates of annual
recruitment deviations in the final two years of the model
(i.e., `r last_data_yr - 1` and `r last_data_yr`) and the age-1 index has been excluded.
All model runs reported in this document are performed in a Bayesian
context. Responses to `r last_assess_yr` SRG
requests are in Section~\@ref(sec:assessment-response-review) and a Glossary
of terms appears in Appendix~\@ref(sec:app-glossary).

## Stock structure and life history {#sec:intro-stock-structure}

`r sp` is a semi-pelagic, schooling species distributed along the west coast of
North America, generally ranging in latitude from 25° to 55° North Latitude (N.~Lat.);
Figure~\@ref(fig:main-overview-map-fig). It is among 18 species of `r sp` from
four genera (being the majority of the family *Merluccidae*), which are found
in both hemispheres of the Atlantic and Pacific Oceans [@AlheitPitcher1995;
@LlorisMatallanasEtAl2005]. The coastal population of `r sp` is currently the
most abundant groundfish population in the California Current system. Smaller
populations of this species occur in the major inlets of the Northeast Pacific
Ocean, including the Strait of Georgia, the Puget Sound, and the Gulf of
California. Each of these smaller populations are genetically distinct from the
coastal population [@VroomanPaloma1977; @IwamotoFordEtAl2004;
@KingMcFarlaneEtAl2012; @GarciaEtAl2018; @LongoEtAl2024]. The coastal
population is also distinguished from the inshore populations by larger size at
age and seasonal migratory behavior and from fish off the west coast of Baja
California by smaller size at age and later spawning [@Zamora-Garcia2020].

The coastal population of `r sp` typically ranges from the waters off southern
California to northern British Columbia and rarely into southern Alaska, with
the northern boundary related to fluctuations in annual migration
[@HamelEtAl2015] depending, in part, on water temperature
[@MalickHunsickerEtAl2020; @MalickSiedleckiEtAl2020]. In spring, adult
`r sp` migrate onshore and northward to feed along the continental shelf and
slope from Northern California to Vancouver Island. In summer, `r sp` often
form extensive mid-water aggregations in association with the continental
shelf break, with the highest densities located over bottom depths of
200--300~m [@DornMethot1991; @DornMethot1992].

Older `r sp` exhibit the greatest northern migration each season, with two-
and three-year old fish rarely being observed in Canadian waters north of Southern
Vancouver Island. During El Niño events (warm ocean conditions such as in
1998 and 2016), a larger proportion of the population migrates into Canadian
waters (Figure~\@ref(fig:main-acoustic-age2-bs-fig)), due to temperature effects
[@MalickHunsickerEtAl2020] and possibly intensified northward transport
during the period of active migration [@Dorn1995b; @AgostiniFrancisEtAl2006].
In contrast, La Niña conditions (colder water, such as in 2001, 2011, and
2021) result in a southward shift in the distribution of `r sp`, with a much
smaller proportion of the population found in Canadian waters compared to
during El Niño years, a trend evident from the acoustic surveys
(Figure~\@ref(fig:main-acoustic-age2-bs-fig)). In general, warmer than average
thermal habitat conditions for mature `r sp` lead to relatively higher biomass
further north and relatively lower biomass around the U.S.--Canadian border,
while cooler than average conditions lead to relatively higher biomass of
immature `r sp` generally spread evenly across their distribution
[@MalickHunsickerEtAl2020]. The distribution of age-1 fish also changes between
years (Figure~\@ref(fig:main-acoustic-age1-bs-fig)).

## Ecosystem considerations {#sec:intro-ecosystem-considerations}

`r sp` are important to ecosystem dynamics in the Eastern Pacific Ocean due
to their relatively large total biomass and potentially large role as both prey
and predator [@JTC2013]. Ongoing research investigating abiotic (i.e.,
environmental conditions) and biotic (e.g., maturity and diet) drivers of the
distribution, recruitment, growth, and survival of `r sp` could provide
insight into how the population is linked with broader ecosystem
considerations. For example, @TurleyRykaczewski2019 found decreased
survival of larval `r sp` as storm events increased, contrary to many other
species in the Southern California Current Ecosystem. An analysis of drivers of
recruitment across the maternal preconditioning, egg, and larval phases of
`r sp` recruitment indicated recruitment is associated with eddy kinetic
energy, the location of the North Pacific Current bifurcation, and upwelling
during maternal preconditioning, as well as with northward long-shore transport
and the number of days between storm events during larval stages
[@VestfalsEtAl2023]. @Phillips2022 suggest temperature
dynamically influences the co-occurrence of `r sp` and krill (i.e.,
euphausiids; *Euphausiacea*), which can influence annual `r sp` growth
and recruitment as the availability of key prey species shifts. Temperature
was also found to impact the co-occurrence of `r sp` and Shortbelly Rockfish
(*Sebastes jordani*, Sebastidae) during the 2014--2016 marine heatwave
[@FreeEtAl2023]. An index of abundance for Humboldt Squid (*Dosidicus
gigas*) suggests that the abundance of `r sp` decreases with increasing squid
abundance [@StewartHazenEtAl2014; @JTC2015]. Many additional research topics
relevant to `r sp` distribution, recruitment, and growth patterns in relation
to oceanographic conditions have been investigated [@ResslerHolmesEtAl2007;
@HamelEtAl2015; @MalickHunsickerEtAl2020; @MalickSiedleckiEtAl2020] and provide
a foundation for further research on these topics.

Motivated by such research, focusing on @VestfalsEtAl2023 in particular, we
include a new Pacific Hake-specific ecosystem summary
in Appendix~\@ref(sec:app-ecosystem-report). We collate time series of relevant ecosystem
processes that are believed to influence `r sp` recruitment. These include prey/competitors (Pacific Herring, \emph{Clupea pallasii}, off
Vancouver Island) and predators (age-1 `r sp`), basin-scale oceanography, and
local calculations of sea-surface temperature, alongshore transport, sea-surface
height, mixed layer depths, and the strength of poleward undercurrent. These are
calculated for specific areas and time periods corresponding to different
life-history stages of `r sp` [@VestfalsEtAl2023]. While not
comprehensive or definitive, this is a start to including such Pacific Hake-relevant
ecosystem information in the annual stock assessment.

Recent oceanographic trends and large-scale ecosystem conditions,
as summarized in the National Oceanic and Atmospheric Administration’s (NOAA)
annual [California Current Ecosystem Status Reports](https://www.pcouncil.org/annual-california-current-ecosystem-status-report/)
(Leising et al. in prep, for 2024)
provide insight into potential drivers of `r sp` population dynamics and fleet
operations. Periods of high productivity are often marked by strong winter
and spring upwelling which brings nutrients to coastal waters, cooler temperatures, an
energy-rich copepod community, and high productivity of krill, a key food source for `r sp`
[@BuckleyLivingston1997; @CCIEA2021].

During 2024 (Leising et al. in prep), basin-scale climate patterns suggest below average to
average conditions in the California Current Ecosystem (CCE). A strong El Niño
in 2023-24 resulted in warm temperatures during winter and spring and delayed
upwelling. The responses of lower trophic level communities to these conditions
were typical of those observed during previous El Niño events. For example, the
biomass of lipid-rich northern copepods and adult krill were below average in
the northern region of the CCE in winter and spring. However, the El Niño
conditions dissipated quickly and the ecosystem transitioned to cooler and more
productive conditions following a strong spring upwelling. The northern copepods
and krill recovered to near average abundances in summer and fall, and the
forage community throughout the CCE was relatively diverse and
productive. Observations of forage communities in the central and southern
regions of the CCE indicate that the abundances of larval and juvenile `r sp` in
these regions are above average and have been increasing over the past five
years. At the same time, consumption of `r sp` by Bluefin Tuna and
Swordfish has been well above average in recent years (2022-23) and the spawning
stock biomass of these predators has been increasing over this same period as
well. See Appendix~\@ref(sec:app-ecosystem-report) for more details and a
'risk table' documenting ecosystem and climate factors potentially affecting `r sp`
stock productivity and uncertainty.

Using empirical weight-at-age data in the model allows for
time-varying growth without needing a mechanistic relationship or environmental
data, which facilitates an `Ecosystem Approach to Fisheries Management'
(a priority for Department of Fisheries and Oceans [DFO] and NOAA; see Section~\@ref(sec:data-weight-at-age)).
Furthermore, the year-specific maturity-at-age specifically includes a
temperature effect from a spatiotemporal model (Section~\@ref(sec:data-maturity)).
Related ongoing research should provide more insights into the specific mechanisms
affecting changes in growth and fecundity, which will enable further condition-specific prediction
capabilities (e.g., assumptions of growth, or weight at age, and fecundity during forecast
years). It is hypothesized that temporal changes in weight-at-age data may be
due to ecosystem effects such as prey availability, predator abundance, and
ocean temperature [@ChittaroGrandinetal2022].

## Management of `r sp` {#sec:intro-management}

Since the implementation of the Magnuson--Stevens Fishery Conservation and
Management Act in the U.S. and the declaration of a 200-mile
fishery-conservation zone in the U.S. and Canada in the late 1970s, annual
quotas (or catch targets) have been used to limit the catch of `r sp` in
both countries' zones. Scientists from both countries historically
collaborated through the Technical Subcommittee of the Canada--U.S.
Groundfish Committee (TSC), and there were informal agreements on the adoption
of annual fishing policies. During the 1990s, however, disagreements between
the U.S. and Canada on the allotment of the catch limits between U.S. and
Canadian fisheries led to quota overruns; the 1991--1992 national quotas
summed to `r tot_9192_attainment`% of the coast-wide limit, while the
1993--1999 combined quotas were an average of `r tot_9399_attainment`% of the
limit. The Agreement establishes U.S. and Canadian shares of the coast-wide
total allowable catch (TAC) at `r us_allotment_percent`% and
`r can_allotment_percent`%, respectively, and this distribution has largely
been adhered to since 2005. A bilateral agreement on the coast-wide
TAC could not be reached in 2020 and 2021; so, catch targets were set
unilaterally during these years for the first time since the inception of the
Agreement. Catch allocations as specified in the Agreement have since been
applied.

Since 1999, an upper limit on catch has been calculated using an `r fspr_40`
default harvest rate with a 40:10 adjustment. This decreases the catch
linearly from the catch at a relative spawning biomass of 40% to zero catch
at a relative spawning biomass values of 10% or less (called the default
harvest policy in the Agreement); relative spawning biomass is the female
spawning biomass divided by that at unfished equilibrium. Further
considerations have almost always resulted in catch targets being set
lower than the recommended catch limit. Total catch has not exceeded the
coast-wide quota since 2002, and harvest rates are likely to have never
exceeded the `r fspr_40` target.

### Management of `r sp` in the United States {#sec:intro-management-us}

In the U.S. zone, participants in the directed fishery are required to use
pelagic trawls with a codend mesh of at least 7.5~cm. Regulations have also
restricted the area and season of fishing to reduce the bycatch of Chinook
Salmon (*Oncorhynchus tshawytscha*), depleted rockfish populations, and other
species as related to their specific harvest specifications. The current
allocation agreement, effective since 1997, divides the U.S. harvest into
tribal (17.5%) and non-tribal (82.5%, including a small amount set aside for
research) components. Starting in 1996, the Makah Tribe has conducted a fishery
with the tribal allocation in its usual and accustomed fishing area. The
non-tribal harvest allocation is divided among catcher-processors (34%),
motherships (24%), and shoreside vessels (42%). Since 2011, the non-tribal
U.S. fishery has been fully rationalized with allocations in the form of
Individual Fishing Quotas (IFQs) to the shoreside sector and group shares to
cooperatives in the at-sea mothership (MS) and catcher-processor (CP) sectors.
The At-Sea Hake Observer Program (A-SHOP) has been monitoring fishing vessel activity
since 1975, originally monitoring foreign and joint-venture vessels. All domestic vessels have full observer
coverage since 1991, including the 2020
and 2021 fishing seasons, despite the COVID-19 pandemic.

Shortly after the 1997 allocation agreement was approved by the Pacific Marine
Fisheries Commission, fishing companies owning catcher-processor
vessels with U.S. West Coast groundfish permits established the `r common_name`
Conservation Cooperative (PWCC). The primary role of the PWCC is to distribute
the catcher-processor allocation among its members to achieve greater efficiency and
product quality, as well as promoting reductions in waste and bycatch rates
relative to the former 'derby' fishery in which all vessels competed for a
fleet-wide quota. The mothership fleet has also formed a cooperative where
bycatch allocations are pooled and shared among the vessels. The individual
cooperatives have internal systems of in-season monitoring and spatial closures
to avoid and reduce bycatch of salmon and rockfish.

### Management of `r sp` in Canada {#sec:intro-management-canada}

Canadian groundfish managers distribute their portion of the coast-wide TAC
as quota to individual license holders. In `r last_data_yr`, Canadian `r sp`
fishermen were allocated a TAC of `r last_yr_can_tac`~t, which did not
include any carryover quota. Canadian priority lies with the domestic fishery.
However, when there is determined to be an excess of fish for which there is not
enough domestic processing capacity, fisheries managers give consideration to
a Joint-Venture fishery in which foreign processor vessels are allowed to
accept codends from Canadian catcher vessels while at sea. The last year
there was Joint-Venture quota allocation was in `r latest_yr_can_jv`.

In `r last_data_yr`, all Canadian `r sp` trips were subject to 100%
observer coverage by electronic monitoring for both the shoreside component
of the domestic fishery and the freezer-trawler component. There is no
in-person observer program for the Canadian `r sp` fisheries.

Retention of all catch, with the exception of prohibited species, was
mandatory. The retention of groundfish other than Sablefish, Mackerel,
Walleye Pollock, and Pacific Halibut on dedicated `r sp` trips using
electronic monitoring was not allowed to exceed 10% of the landed catch
weight. The bycatch allowance for Walleye Pollock was 30% of the total landed
weight.

## Fisheries {#sec:intro-fisheries}

The fishery for the coastal population of `r sp` occurs along the coasts of
Northern California, Oregon, Washington, and British Columbia primarily during
May--November. The fishery is conducted with mid-water trawls and
has met the Marine Stewardship Council (MSC) Fisheries Standard to be
certified as meeting sustainable fishing benchmarks since 2009. Foreign fleets
dominated the fishery until 1991, when domestic fleets began taking the
majority of the catch. Catches were occasionally greater than 200,000~t prior
to 1986, and since then, they have been greater than 200,000~t for all except
`r catches_below_200000_since_1986` years.

In 2021, the `r sp` fishery was Canada's largest commercial wild fishery
(species with the largest catch), representing 10% of Canada's total landings
of all species
([www.dfo-mpo.gc.ca](https://www.dfo-mpo.gc.ca/stats/commercial/land-debarq/sea-maritimes/s2021pq-eng.htm)).
Over CAD \$19~million in wages was estimated to have been paid to employees of
the processing industry in British Columbia in 2021, with an exported value of
greater than CAD \$60~million in product to Ukraine (greater than CAD \$25~million),
China, South Africa, Lithuania, and other countries [@DFO2023].

In the United States, over USD \$89.2 million in labor costs is estimated to have been paid to
employees in 2022
([www.noaa.gov](https://dataexplorer.northwestscience.fisheries.noaa.gov/fisheye/PerformanceMetrics/)).
This includes wages paid to: crew and captains fishing on catcher vessels that
deliver shoreside and at-sea to motherships, workers in shore-based processing
facilities, crew, captains, and workers on catcher-processor vessels, and
workers on mothership vessels. The exported value of `r sp` was USD \$172
million in 2022, including to Netherlands, Lithuania and Spain, which make up
about 58\% of the total
([www.noaa.gov](https://foss.nmfs.noaa.gov/apexfoss/f?p=215:200:2797069701321)).
The total economic impact of the `r sp` fishery on the U.S. West Coast in 2022
was USD \$295 million in income and 4,324 jobs [@Steineretal2024].

The Joint Management Committee (JMC) determined an adjusted (for carryovers)
coast-wide TAC of `r last_yr_tac`~t for `r last_data_yr`. The U.S. catch
target was set at `r last_yr_us_tac`~t and the Canadian catch target at
`r last_yr_can_tac`~t. A brief review of the `r last_data_yr` fishery is
presented here by country
(Tables~\@ref(tab:main-catches-us-tab)--\@ref(tab:main-landings-tac-tab) and
Figure~\@ref(fig:main-catches-fig)).  Additional information is available in
annual U.S. and Canada Advisory Panel reports
(Appendices~\@ref(sec:app-us-fishery-report) and
\@ref(sec:app-canada-fishery-report)).

### Fisheries for `r sp` in the United States {#sec:intro-fisheries-us}

In `r last_data_yr`, the U.S. specified catch target (i.e., adjusted for carryovers) of
`r last_yr_us_tac`~t was further divided among the research, tribal,
catcher-processor, mothership, and shoreside sectors. After the tribal
allocation of 17.5% (`r f(last_yr_us_tribal)`~t) and a
`r f(last_yr_us_research)`~t allocation for research catch and bycatch in
non-groundfish fisheries, the `r last_data_yr` non-tribal U.S. catch limit
of `r f(last_yr_us_non_tribal)`~t was allocated to the catcher-processor
(34%), mothership (24%), and shoreside (42%) commercial sectors.
Reallocation of `r f(last_yr_us_tribal_quota_reallocated)`~t of tribal
quota to non-tribal sectors on
`r noquote(last_yr_us_tribal_reallocate_dates_f)`
 resulted in final quotas for the catcher-processor, mothership, and
 shoreside sectors of
`r f(last_yr_us_cp_quota_reallocated)`~t,
`r f(last_yr_us_ms_quota_reallocated)`~t,
and
`r f(last_yr_us_shore_quota_reallocated)`~t, respectively.

Prior to 2015, the shoreside sector was allowed to fish starting June 15 north
of 42° N.~Lat. (the Oregon--California border) and April 1 between
40°~30' N.~Lat. and 42° N.~Lat., whereas the at-sea sectors were allowed to fish starting May 15.
Between 2015--2022, the shoreside sector was allowed to fish north of 40°~30'
N.~Lat. starting May 15 and south of 40°~30' N.~Lat. starting April 15,
although only 5% of the shoreside allocation was released for this early
period. Since 2023, all sectors have been allowed to fish starting May 1.
Regulations do not allow at-sea processing or night fishing (midnight to one
hour after official sunrise) south of 42° N.~Lat. at any time during the
year.

In `r last_data_yr`, the total catch of `r sp` in U.S. waters was ranked `r last_yr_us_rank`
over all years (Table~\@ref(tab:main-catches-us-tab)) and the U.S.
utilization rate (`r last_yr_us_attained`%) was the lowest it has ever been
(see Appendix~\@ref(sec:app-us-fishery-report) for more details). The
catcher-processor, mothership, and shoreside sectors caught
`r catcher_processor_ct`%, `r mothership_ct`%, and `r shore_based_ct`% of
their final reallocated quotas, respectively. Tribal landings, which are
included in the shoreside sector totals were `r f(last_yr_us_ti_ct)`~t (zeros
may not reflect actual catch if less than three vessels were fishing; see
appendix~\@ref(sec:app-us-fishery-report) for further details).
The median fishing depth for the at-sea sectors was slightly deeper than the last
few years (Figure~\@ref(fig:main-us-depths-fig)). The shoreside sector had the largest
monthly catches during July, August, and September. While, the at-sea sectors
had the largest monthly catches during May, September, and October.

In both U.S. at-sea sectors, age-3 and age-4 fish associated with the
2021 and 2020 year classes were common ages caught. Both ages were seen
last year in appreciable numbers as age-2 and age-3 fish.
The reported proportions at age summarize sampling efforts on
`r us_age_n_cp` catcher-processor hauls and `r us_age_n_ms` mothership hauls
(Table~\@ref(tab:main-sampling-history-tab)).
For the catcher-processor sector, the four most abundant age classes (by
numbers) seen in `r last_data_yr` were age-`r us_age_1_prop_age_cp`
(`r us_age_1_prop_cp`%), age-`r us_age_2_prop_age_cp` (`r us_age_2_prop_cp`%),
age-`r us_age_3_prop_age_cp` (`r us_age_3_prop_cp`%), and
age-`r us_age_4_prop_age_cp` (`r us_age_4_prop_cp`%);
Table~\@ref(tab:main-us-cp-age-data-tab).
For the mothership sector, the four most abundant age classes for
`r last_data_yr` were age-`r us_age_1_prop_age_ms` (`r us_age_1_prop_ms`%),
age-`r us_age_2_prop_age_ms` (`r us_age_2_prop_ms`%),
age-`r us_age_3_prop_age_ms` (`r us_age_3_prop_ms`%), and
age-`r us_age_4_prop_age_ms` (`r us_age_4_prop_ms`%)
(Table~\@ref(tab:main-us-ms-age-data-tab)).

Age-samples from `r pull(us_sb_age_df[us_sb_age_df$year == last_data_yr, "num_samples"])`
shoreside trips in `r last_data_yr` showed similar age compositions in the catch
compared to the at-sea sectors, though not nearly as many smaller (age-2
and age-1) fish and more age-8 and age-10 fish from the 2016 and
2014 year classes.
The four most abundant age classes with the highest occurrence in
`r last_data_yr` were age-`r us_age_1_prop_age_shore`
(`r us_age_1_prop_shore`%), age-`r us_age_2_prop_age_shore`
(`r us_age_2_prop_shore`%), age-`r us_age_3_prop_age_shore`
(`r us_age_3_prop_shore`%), and age-`r us_age_4_prop_age_shore`
(`r us_age_4_prop_shore`%)
(Table~\@ref(tab:main-us-sb-age-data-tab)). Age-compositions
from the at-sea and shoreside sectors during this last year were less similar
than they were the previous year.

### Fisheries for `r sp` in Canada {#sec:intro-fisheries-can}

The `r last_data_yr` Canadian `r sp` domestic fishery removed
`r last_yr_can_landings`~t from Canadian waters
(Table~\@ref(tab:main-catches-can-tab)), which was `r last_yr_can_attained`%
of the Canadian TAC of `r last_yr_can_tac`~t. For the third year in a row,
the attainment for Canada was much lower than usual, due to the fishing
vessels having a difficult time finding fish in Canadian waters (see
Appendix~\@ref(sec:app-canada-fishery-report) and the last two years' assessments,
@JTC2023 and @JTC2024, for more details).

The shoreside vessels, which land fresh round product onshore, landed
`r last_yr_can_shore`~t in `r last_data_yr`, the lowest on record since 1990, and
less than half of the `r last_data_yr - 1` landings of
`r f(ct |> dplyr::filter(Year == last_data_yr - 1) |> pull("Canada Shoreside"))`~t.
The freezer trawlers, which freeze headed and gutted product while
at sea, landed `r last_yr_can_freezer`~t. This was the lowest amount the
freezer trawlers have landed since 2013, despite doubling the number of
vessels since then.

Fishing started in early April and ended in November. The general view of
the Canadian fleet is that abundance in Canadian waters remained below
normal levels in `r last_data_yr`, including the normally-abundant areas
outside of Southwest Vancouver Island. Reports of difficulties finding
fish in `r last_data_yr` led to most vessels not leaving the dock,
therefore amplifying the effect of low catches. The fish caught in Canada
appeared to be mostly from four age classes (see below), with very few
smaller fish (less than 500 grams) caught.

The most abundant year classes in the Canadian shoreside catch in `r last_data_yr` (by numbers;
Table~\@ref(tab:main-can-ss-age-data-tab)) were
age-`r max_shoreside_age_prop_age` (`r max_shoreside_age_prop`%),
age-`r second_shoreside_age_prop_age` (`r second_shoreside_age_prop`%),
age-`r third_shoreside_age_prop_age` (`r third_shoreside_age_prop`%), and
age-`r fourth_shoreside_age_prop_age` (`r fourth_shoreside_age_prop`%).
The most abundant year classes in the Canadian freezer-trawler catch (by
numbers; Table~\@ref(tab:main-can-ft-age-data-tab)) were
age-`r max_freezer_trawler_age_prop_age` (`r max_freezer_trawler_age_prop`%),
age-`r second_freezer_trawler_age_prop_age` (`r second_freezer_trawler_age_prop`%),
age-`r third_freezer_trawler_age_prop_age` (`r third_freezer_trawler_age_prop`%), and
age-`r fourth_freezer_trawler_age_prop_age` (`r fourth_freezer_trawler_age_prop`%).
