
\rfoot{Data}

# Data {#sec:data}

Fishery-dependent and fishery-independent data used in this assessment
(Figure~\@ref(fig:main-data-overview-fig)) include the following sources:

- Total catch from all U.S. and Canadian fisheries that targeted `r sp`
from `r start_yr` to `r last_data_yr`
(Tables \@ref(tab:main-catches-us-tab)--\@ref(tab:main-landings-tac-tab)).

- Fishery age compositions aggregated by year and country-specific sector
for the last ten years are available
(Tables~\@ref(tab:main-us-cp-age-data-tab)--\@ref(tab:main-can-ft-age-data-tab))
to investigate region-specific trends; age compositions aggregated by year,
composed of data from the U.S. fishery
(`r max_fishery_age_prop[1]`--`r max_fishery_age_prop[2]`) and the
Canadian fishery
(`r can_age_yrs_min`--`r can_age_yrs_max`),
are used to fit the model
(Table~\@ref(tab:main-input-age-data-fishery-tab) and
Figure~\@ref(fig:main-age-comp-bubbles-fig)).

- An age-2$+$ biomass index and age compositions from the `r survey_name`
(`r str_flatten_comma(survey_age_years)`;
 Tables~\@ref(tab:main-input-age-data-survey-tab),
 ~\@ref(tab:main-survey-history-tab),
 and~\@ref(tab:main-survey-by-country-tab);
 Figures~\@ref(fig:main-age-comp-bubbles-fig)
 and~\@ref(fig:main-survey-extrap-biomass-fig)).

- The relative age-1 index (billions of age-1 fish) derived from the
`r survey_name` was used in a sensitivity model exploration in this
assessment (Table~\@ref(tab:main-parameter-estimates-sens-2-tab); 
Figure~\@ref(fig:main-biomass-base-alternative-2-fig)).
<!--(`r str_flatten_comma(survey_age1_yrs)`;-->
<!-- Table~\@ref(tab:main-survey-history-tab);-->
<!-- Figure~\@ref(fig:main-survey-extrap-biomass-fig)).-->

 - An age-1$+$ relative biomass index for `r sp` based on
 environmental DNA was used in a sensitivity model exploration in this
 assessment. The index covers the years 2019, 2021, and 2023. A full
 explanation of the data and index can be found in
 Appendix~\@ref(sec:app-eDNA-index).

The following biological relationships, derived from external analysis of
auxiliary data, were input as fixed values in the assessment model:

- Ageing-error matrices based on cross-read and double-blind-read otoliths.

- Annual proportions of female `r sp` at each age that are mature
(Section~\@ref(sec:data-maturity)) from histological analyses of ovary samples
(Table~\@ref(tab:main-ovaries-tab); Figure~\@ref(fig:main-maturity-ogive-fig)).

- Weight-at-age from fishery and survey catches
(1975--`r max_fishery_age_prop[["end_yr"]]`;
Figures~\@ref(fig:main-weight-at-age-fig)--
\@ref(fig:main-weight-at-age-lines-fig)).

- Derived fecundity-at-age as the product of year-specific weight-at-age multiplied
by year-specific maturity-at-age (Figures~\@ref(fig:main-maturity-ogive-fig) and
\@ref(fig:main-fecundity-at-age-fig)).

Additional data sources not used in this assessment are discussed in Section
\@ref(sec:data-not-used).

## Fishery-dependent data {#sec:data-fishery-data}

### Total catch {#sec:data-total-catch}

The catch of `r sp` for `r start_yr`--`r last_data_yr` is summarized by
country-specific sectors
(Tables~\@ref(tab:main-catches-us-tab)--\@ref(tab:main-landings-tac-tab))
and modeled as annual coast-wide catches. Catches in U.S. waters prior to
1978 are available only by year from @BaileyFrancisEtAl1982 and
historical assessment documents. Canadian catches prior to 1989 are also
unavailable in disaggregated form. U.S. shoreside landings are from the
Pacific Fishery Information Network (PacFIN) database. Foreign and
Joint-Venture catches for 1981--`r terminal_yr_us_jv_foreign` and U.S.
domestic at-sea catches for 1991--`r last_data_yr` are calculated from the
Alaska Fisheries Science Center's North Pacific Groundfish and Halibut
Observer (NORPAC) database, which also stores A-SHOP data.
Canadian Joint-Venture catches from 1989 are from the
Groundfish Biological (GFBio) database. Canadian shoreside landings are
from the Groundfish Catch (GFCatch) database for 1989--1995, the Pacific
Harvest Trawl (PacHarvTrawl) database for 1996--March 31, 2007, and the
Fisheries Operations System (FOS) database for April 2007--present.

Minor updates to catches used in previous assessments were made based on the
best available information extracted from the aforementioned databases.
Tribal catches were available in PacFIN for the U.S. tribal fishery at the
time the data were extracted and were cross-checked with numbers based on
information provided by the Makah Tribe. The Makah Tribe is also working on
providing historical catches such that shoreside catches can be
summarized separately from tribal catches since the onset of the fishery.

Historically, the fishery for `r sp` has been well covered by observers with
slight differences in coverage by sector. Currently, U.S. shoreside vessels
carry observers and are required to retain all catch and bycatch for sampling
by plant observers. Vessels participating in the U.S. at-sea sectors are also
required to have observers on board and have since 1990. U.S. foreign and
Joint-Venture vessels had varying levels of coverage from 1975--1990 ranging
from 21--100% coverage. Canadian Joint-Venture and Canadian freezer-trawler
vessels were monitored by at-sea observers from 1996--2019. In 2020 and 2021
there were no observers on Canadian freezer trawlers due to staffing issues and
in 2022 the decision was made to stop providing observers on board all Canadian
vessels. Early in 2022 a sampling plan designed by Canadian managers,
scientists, and the sampling contractor, Archipelago Marine Research Ltd.
(AMR), was put into place to ensure the ongoing sampling of `r sp` on Canadian
vessels (see Section \@ref(sec:data-fishery-biological-data)). Canadian trawl
catches are monitored autonomously at sea by cameras onboard vessels. Catch is
recorded by dockside samplers within the Groundfish Trawl Dockside Monitoring
Program using total catch weights provided by processing plants. Discards are
negligible relative to the total fishery catch for all sectors.

### Fishery biological data {#sec:data-fishery-biological-data}

Biological information from the U.S. at-sea sectors was extracted from the
NORPAC database. This included sex, length, weight, and age information
from the foreign and Joint-Venture fisheries from
1975--`r terminal_yr_us_jv_foreign` and from the domestic at-sea fishery
since `r first_yr_us_atsea`. Observers collected data by selecting fish
randomly from each haul. The number of otoliths collected per haul has varied
over time but is currently three fish every third haul.

Since 1991, biological samples from the U.S. shoreside sector have been
sampled by port samplers located where there are substantial landings of
`r sp`, primarily Eureka, Newport, Astoria, and Westport. Port samplers took
one sample per offload (or trip) consisting of 100 randomly selected fish for
individual length and weight. From those 100 fish, typically 20 fish were
randomly subsampled for otolith extraction.

When there were observers (1996--2019) aboard Canadian freezer trawlers,
they collected 50 otoliths and 300 lengths per sample, sampling once per day
during trips that on average lasted seven days. Since 2022,
freezer-trawler employees have collected fish for sampling from two tows per
trip and delivered them to the dock as frozen specimens where they are
eventually sampled for length, weight, sex, and otoliths. Each delivery
consists of approximately 100 fish, 50 fish from one tow and 50 fish from
another tow, where each tow is bagged separately. Due to unforeseen
circumstances while at sea, some trips did not deliver any bags and
some only delivered one bag.

For electronically observed Canadian shoreside trips, port samplers obtained
biological data from the landed catch. For each sampled trip, approximately
50 ages and 300 lengths were sampled from the catch. Observed domestic
haul-level information is aggregated to the trip level to be consistent with
the unobserved trips that were sampled in ports.

In years when there was a Canadian Joint-Venture fishery, length samples
were collected every second day of fishing operations and otoliths were
collected once per week. Length and age samples were taken randomly from a
given codend. The sample weight from which biological information was collected
was inferred from length--weight relationships.

The sampling unit for shoreside samples is the trip, while the haul is
the primary unit for the at-sea samples
(Table~\@ref(tab:main-sampling-history-tab)). There is no least common
denominator for aggregating at-sea and shoreside samples because detailed
haul-level information is not recorded for shoreside trips and hauls sampled
in the at-sea sectors cannot be aggregated to a comparable trip level. As a
result, initial sample sizes are simply the summed hauls and trips for fishery
biological data.

Biological data were analyzed based on the sampling protocols used to collect
them and expanded to estimate the corresponding statistic from the entire
landed catch by fishery and year when sampling occurred. A description of the
analytical steps for expanding the age compositions can be found in earlier
stock assessment documents [@JTC2013; @JTC2014].

The aggregate fishery age-composition data
(`r max_fishery_age_prop[1]`--`r max_fishery_age_prop[2]`)
confirm the well-known pattern of large cohorts born in 1973, 1977, 1980,
1984, 1987, 1999, 2008, 2010, 2014, and 2016, and suggests large cohorts for
2020 and 2021
(Table~\@ref(tab:main-input-age-data-fishery-tab) and
Figure~\@ref(fig:main-age-comp-bubbles-fig)).
Recent age-composition data still easily track the 2010 cohort, as well as the
large cohorts born since then. Currently, the 2021 cohort is
the largest observed cohort in the U.S. at-sea sectors
(Tables~\@ref(tab:main-us-cp-age-data-tab)--\@ref(tab:main-us-ms-age-data-tab)),
and shoreside sector
(Table~\@ref(tab:main-us-sb-age-data-tab)), and the 2016 cohort is the largest
observed cohort in both Canadian fleets
(Tables~\@ref(tab:main-can-ss-age-data-tab)--
\@ref(tab:main-can-ft-age-data-tab)).
Age-1 fish were observed by the fishery this year
(Table~\@ref(tab:main-input-age-data-fishery-tab)) in the U.S. For the combined
data in `r last_data_yr`,
`r top_coh(base_model, last_data_yr, 3, cap = FALSE)`. For the combined data
in `r last_data_yr - 1`,
`r top_coh(base_model, last_data_yr - 1, 3, cap = FALSE)`.

We caution that proportion-at-age data contain information about the relative
numbers-at-age, which can be affected by changing recruitment, selectivity,
or fishing mortality, making these data difficult to interpret on their own.
For example, the above-average 2005 and 2006 year classes declined in
proportion in the 2011 fishery samples but persisted in small proportions for
years in the fishery catch. Their reductions in 2011 were due to
mortality and the overwhelming size of the more recent large cohorts. The
assessment model is fit to these data to estimate the absolute sizes of
incoming cohorts, which become more precise after they have been observed
over several years.

Both the weight-
(Figure~\@ref(fig:main-weight-at-age-lines-fig);
Section \@ref(sec:data-weight-at-age)) and length-at-age information suggest
that growth of `r sp` has fluctuated markedly over time [see Figure~7 in
@StewartForrestEtAl2011]. This is particularly evident in the frequency of
larger fish ($>55$~cm) before 1990 and a shift towards larger fish starting
again in the 2000s.

## Fishery-independent data {#sec:data-fishery-independent}

### Acoustic survey {#sec:data-acoustic-survey}

The `r survey_name` [@StewartForrestEtAl2011] has been the primary
fishery-independent tool used to assess the distribution, abundance, and
biology of coastal age-2$+$ `r sp` along the west coasts of the U.S.
and Canada. The acoustic surveys performed in
`r combine_words(survey_age_years)` were used in this assessment
(Table~\@ref(tab:main-survey-history-tab)). The acoustic survey samples
transects that represent all waters off the coasts of the U.S. and Canada
thought to contain all portions of the age-2$+$ `r sp` stock. Observations
of age-0 and age-1 `r sp` are excluded from the age-2$+$ index due to
largely different schooling behavior relative to older `r sp`, concerns
about their catchability by the trawl gear, and differences in expected
location during the summer months when the survey takes place.
Observations of age-1 `r sp` are recorded during the survey, and additional
analyses, described below, are conducted to develop a relative age-1 index that
is excluded from the base model this year in the final bridging step
(see Section~\@ref(sec:assessment-changes) and Appendix~\@ref(sec:app-srg-requests)).

The `r survey_end_yr` survey covered U.S. and Canadian waters from Point
Conception to north of Haida Gwaii using 116 transects
(Figure~\@ref(fig:main-acoustic-age2-bs-fig)). In the U.S., transects were
mostly separated by 10~nautical miles; six transects were dropped to account for available
ship days at sea. In Canada, transects were separated by 10~nautical miles along Vancouver
Island and then 20~nautical miles further north. The NOAA Ship Bell M. Shimada and the
Canadian Coast Guard's Sir John Franklin worked collaboratively to complete
the full extent of the survey in `r survey_end_yr`.

Distributions of the backscatter of `r sp` plotted for each acoustic survey
since 1995 illustrate the variable spatial patterns across time of age-2$+$ fish
(Figure~\@ref(fig:main-acoustic-age2-bs-fig)). This variability is due in
part to changes in the composition of the age-2$+$ population because older
`r sp` tend to migrate farther north and partially due to environmental and/or
climatic factors. The 1998 acoustic survey is notable because it shows an
extreme northward distribution that is thought to be related to the strong
1997--1998 El Niño. In contrast, the distribution of `r sp` during the 2001
acoustic survey was compressed into the lower latitudes off the coast of
Oregon and Northern California following the strong La Niña event in 2000.
In 2003, 2005, and 2007 the distribution of `r sp` did not show an unusual
coast-wide pattern despite 2003 and 2007 being characterized as El Niño
years. In 2011, 2012, and 2013 the majority of the biomass distribution of
`r sp` was again found in U.S. waters, which is more likely due to
age composition than the environment because 2013 had some warmer than
average sea-surface temperatures. In 2015, sea-surface temperatures were
warmer again, resulting in a northern shift in the overall distribution.
The distribution of `r sp` in 2017 was more uniform across latitudes than
observed in 2015, which is likely a result of having large proportions of both
the 2010 and 2014 cohorts (Figure~\@ref(fig:main-acoustic-age2-bs-fig)). Weak
El Niño conditions in 2019 decreased in their prevalence starting in March of
that year, leading to neutral conditions by July. Consequently, during the 2019
survey `r sp` were found on all survey transects from just north of Morro Bay,
California to the northern end of Vancouver Island, with the greatest offshore
extent found off of Cape Mendocino, California. During the 2021 survey, the majority of
`r sp` were found in U.S. waters, congruent with the continuation of La Niña
conditions in the California Current from 2020 to 2021. Despite the switch to
El Niño conditions in April of 2023, very few fish were seen in Canadian
waters during the 2023 survey. Ongoing research is looking into relationships
between environmental conditions and `r sp` distribution and recruitment that
will help to inform the mechanisms behind observations
[@MalickSiedleckiEtAl2020; @Phillips2023].

During the acoustic surveys, mid-water trawls are made opportunistically to
determine the species composition of the observed acoustic sign and to obtain
the `r sp` length data necessary to scale the acoustic backscatter into biomass (see
Table~\@ref(tab:main-survey-history-tab) for the number of trawls in each
survey year). Biological samples collected from these trawls are
post-stratified, based on similarity in size composition, and the composite
length frequency is used to characterize the size distribution of `r sp`
along each transect and to predict the expected backscattering cross
section for `r sp` based on the fish-size target-strength (TS) relationship.
Any potential biases that might be caused by factors such as alternative
TS relationships are partially accounted for in catchability. But,
variability in the estimated survey biomass due to uncertainty in TS is
not explicitly accounted for in the assessment.

Data from the acoustic survey are analyzed using kriging, which accounts for
spatial correlation, to provide an estimate of total biomass as well as an
estimate of the year-specific sampling variability due to patchiness of
schools of `r sp` and irregular transects
[@Petitgas1993; @RivoirardSimmondsEtAl2000; @MelloRose2005;
@SimmondsMacLennan2006]. Advantages to the kriging approach are discussed in
the 2013 stock assessment [@JTC2013].

For the 2016 assessment [@JTC2016], the data from all surveys since 1998 were
reanalyzed using consistent assumptions, an updated version of
the EchoPro software, and a common input-file structure because some previously
generated files had spurious off-transect zeros because of how the data were
exported. The same analytical procedure was carried out during the reanalysis
of 1995 survey data [@JTC2017] and during the preparation of survey data
collected since 2017. The assumptions are as follows:

- fixed minimum ($k_{min}=3$) and maximum ($k_{min}=10$) number of
points used to calculate the value in a cell;

- search radius is three times the length scale that is estimated from the
variogram; and

- biomass decays with distance from the end of the transect when extrapolating
biomass beyond the western end of a transect, which was refined and supported
by the SRG starting with the 2016 assessment [@JTC2016].

Starting in 2021, the EK~60 echosounders were replaced with EK~80 echosounders,
and thus, survey estimates from years using the new echosounders are scaled by a
factor of 1.06 to convert the EK~80 to EK~60 acoustic data. The survey team will
eventually be converting all pre-2021 EK~60 data to an equivalent EK~80 format.
Thus, a full time series of consistently analyzed survey biomass
(Table~\@ref(tab:main-survey-history-tab) and
Figure~\@ref(fig:main-survey-extrap-biomass-fig)) and age compositions
(Table~\@ref(tab:main-input-age-data-survey-tab) and
Figure~\@ref(fig:main-age-comp-bubbles-fig)) since 1995 are used to fit the
stock assessment model. These data contain many sources of variability [see
@StewartForrestEtAl2011] but results from research done in 2010 and 2014 on
their representativeness show that trawl sampling and post-stratification is
only a small source of variability. Specifically, repeated trawls at different
depths and spatial locations on the same aggregation of `r sp` were similar
and analyses regarding the method used to stratify the data led to similar
overall conclusions.

Estimated age-2$+$ biomass in the survey increased steadily over the four
surveys conducted in 2011--2013 and 2015
(Table~\@ref(tab:main-survey-history-tab) and
Figure~\@ref(fig:main-survey-extrap-biomass-fig)). It decreased in 2017 to
`r f(survey_biomass["2017"], 2)`~Mt, then increased to 1.72~Mt in
2019, and has since decreased to
`r last_survey_yr_biomass`~Mt in `r last_survey_yr`. The
`r last_survey_yr` survey age composition was made up of
`r combine_words(paste0(f(survey_last_yr_age[1:5], digits = 2), "\\%"))`
from the
`r combine_words(last_survey_yr - type.convert(as.is=TRUE,names(survey_last_yr_age[1:5])))`
year classes, respectively. Note that the estimate of biomass does not include age-0 or
age-1 fish and the age compositions used to estimate selectivity of the survey
also exclude age-0 and age-1 fish (Table~\@ref(tab:main-input-age-data-survey-tab)).
Estimates of country-specific age-2$+$ biomass are also provided
(Table~\@ref(tab:main-survey-by-country-tab)).

The separate relative age-1 index (numbers of fish) was excluded from the base
model this year as described in the bridging models (see
Section~\@ref(sec:assessment-changes)). This is similar to the 2013--2021 assessments
[@JTC2013; @JTC2021], where the relative age-1 index was only explored as a
sensitivity model. The index was included in the base
model from 2022--2024. For the sensitivity model, the relative index of age-1
fish was estimated similarly to previous years, including the use of a 1.06 scaling
factor to account for differences between the EK~60 and EK~80
echosounders Similar to what is done for the age-2$+$ index.
The index indicates relative changes between years, not absolute values, and confirms the
large year classes in 2008, 2010, 2014, and 2016, and suggests large cohorts for 2020 and 2022
(Table~\@ref(tab:main-survey-history-tab) and
Figure~\@ref(fig:main-acoustic-age1-bs-fig)).

Incorporating the relative age-1 index can result in estimates of recruitment
strength that are informed on average one year earlier than models without the
index [e.g., Figures~54 and~G.1 in @JTC2021]. The suite of sensitivity models
related to the relative age-1 index explored over the past decade indicate that
its use typically informs recruitment such that the direction of cohort
strength (i.e., weak, strong, or neutral) remains unchanged in subsequent
assessments even after being informed by more data. The utility of an informed
recruitment signal was deemed far greater than an uninformed recruitment assumption.
The `r survey_name` team supports exploring its use in the stock assessment and
is committed to continually evaluating and refining approaches to improve the
estimates and related uncertainty. This year the age-1 index was
excluded from the base model in the final bridging step (see
Section~\@ref(sec:assessment-changes) for more details).

## Other data not used in this assessment {#sec:data-not-used}

Some data sources were not included in the base model but have been explored
or were included in previous stock
assessments. Data sources not discussed here have either been discussed at past
`r sp` assessment review meetings or are discussed in more detail in the 2013
stock assessment document [@JTC2013]. These primarily include those listed below.

- Fishery and survey length compositions.

- Fishery and survey conditional age-at-length compositions.

- Calculation of a reliable fishery catch-per-unit-effort (CPUE) metric is
particularly problematic for `r sp`, and it has never been used as an
index for the assessment of this stock [see @JTC2013 for more details].

- Biomass indices and age compositions from the following years of the
`r survey_name`: 1977, 1980, 1983, 1986, 1989, and 1992.

- Bottom trawl surveys in the U.S. and Canada (various years and spatial
coverage from 1977--`r last_assess_yr`).

- Northwest Fisheries Science Center/Southwest Fisheries Science
Center/PWCC coast-wide juvenile `r sp` and rockfish surveys
(2001--`r last_assess_yr`). However, the JTC is analyzing the age-0 `r sp` data
from these surveys in collaboration with researchers from the Southwest Fisheries Science
Center and Australia, to investigate potential for developing an early
indication of potential cohort strength.

- California Cooperative Oceanic Fisheries Investigations (CalCOFI)
larval `r sp` production index, 1951--2006. The data source was
previously explored and rejected as a potential index of `r sp` female
spawning biomass. However, the JTC are exploring new avenues to utilize
CalCOFI data based on recently developed methods (related to previous bullet).

- Bycatch of `r sp` in the trawl fishery for Pink Shrimp off the coast of
Oregon (2004, 2005, 2007, and 2008).

- Historical biological samples collected in Canada prior to 1990 but
currently not available in electronic form.

- Historical biological samples collected in the U.S. prior to 1975 but
currently not available in electronic form or too incomplete to allow
for their analysis with methods consistent with more current sampling programs.

- Northwest Fisheries Science Center winter 2016 and 2017 acoustic
research surveys of spawning `r sp`.

## Externally analyzed data {#sec:data-externally-analyzed-data}

### Weight-at-age {#sec:data-weight-at-age}

A matrix of empirically derived population weight-at-age data by year
(Figures~\@ref(fig:main-weight-at-age-fig)--
\@ref(fig:main-weight-at-age-lines-fig)) is used in the current assessment
model to translate numbers at age to biomass at age. Annual weight-at-age data
was modelled from biological samples pooled from all fisheries and most
surveys for the years 1965 to `r max_fishery_age_prop[2]`
(Figures~\@ref(fig:main-weight-at-age-fig)--
\@ref(fig:main-weight-at-age-lines-fig)). Samples from near-shore areas, such as
the Puget Sound, were not included. The earliest samples come from the U.S.
shoreside vessels that date back to 1965. With the effort to reconstruct all
historical data, some additional historical samples were found within the U.S.
databases for this assessment, such as these early shoreside samples. Additional
effort is ongoing to ensure that all samples taken during the acoustic survey
research trips are also available.
Past investigations into calculating weight-at-age data for the fishery and
survey independently showed little impact on model results, and thus, a single
matrix is used for all fleets and beginning and middle-of-the-year population
weight-at-age.

A generalized linear mixed model (GLMM) with a
lognormal distribution has been used to model weight-at-age data external to the
assessment since the 2024 assessment, with weight relating to a smoothed effect of age between
ages zero and fifteen; random effects for cohort and year; and fixed effects for
sex. The model is similar to models investigated for Walleye Pollock off
Alaska, where models with correlations between age, cohort, and year were
found to best fit the data [@ChengEtAl2023]. Weights from fish ages
15 and above for each year were pooled, and thus, ages 15--20 are assumed to
have the same weight-at-age.
Estimated parameters from this model were used to predict weight for ages zero
to fifteen from 1975 to `r last_data_yr` for each sex. The means of annual,
age-specific estimates across both sexes were used for input into the
assessment model. The number of samples
(Figure \@ref(fig:main-sample-size-weight-at-age-fig)) is generally
proportional to the amount of catch.

The biomass at the start of a given year is based on the weight-at-age from the
same mid-year, when the majority of samples are available
(Figure~\@ref(fig:main-weight-at-age-fig)). Prior to 1975, weight-at-age input
to Stock Synthesis is assumed to be equal to the mean of all available years for
each respective age (1975-`r last_data_yr`)
(Figure~\@ref(fig:main-weight-at-age-fig)).
Forecast weight-at-age data are based on age-specific means from the most
recent five years (`r last_data_yr-4`--`r last_data_yr`), consistent with
forecast selectivity (Figure~\@ref(fig:main-weight-at-age-fig)).

The use of empirical weight-at-age data is a convenient method to capture the
variability in both the weight-at-length relationship within and among years
as well as the variability in length-at-age data, without requiring parametric
models to represent growth relationships. Previous attempts to explicitly model
year- and cohort-specific growth were not successful for `r sp` and have not
been revisited since @StewartForrestEtAl2011. The empirical weight-at-age
method requires the assumption that observed values are not biased by strong
selectivity at length or weight and that the spatial and temporal patterns of
the data sources provide a representative view of the underlying population.
Simulations show that, in general, using empirical weight-at-age data when many
observations are available results in more accurate estimates of spawning
biomass than modeling growth [@KuriyamaOnoEtAl2015].

### Maturity and fecundity {#sec:data-maturity}

Maturity-at-age has always been modelled external to the assessment but up
through the the 2023 assessment [@JTC2023] the maturity ogive was
time-invariant. Starting with the 2024 assessment [Appendix G in @JTC2024],
annual age-based maturity ogives (Figure~\@ref(fig:main-maturity-ogive-fig))
were developed using the same data, i.e., histological estimates of functional
maturity (Table~\@ref(tab:main-ovaries-tab)), but fit with a spatiotemporal
GLMM [@head-decade-2025]. These data include samples collected north
of Point Conception (34$^\circ$ 44$^\prime$ N. Lat.) and south of the
U.S./Canada border from the acoustic survey, winter and summer acoustic
research trips, U.S. catcher-processor vessels by A-SHOP observers,
and the U.S. West Coast Groundfish Bottom Trawl Survey
since 2009. Southern samples have been excluded from maturity analyses since
2018 [@JTC2018] because they are thought to mature at earlier ages and smaller
sizes. Canadian samples (n = 73) were excluded from the spatiotemporal model
because their of their lack of spatiotemporal resolution. These Canadian
samples could be included in future analyses after all of the Canadian samples
are analyzed and/or more Canadian samples are collected and analyzed.

The probability of being functionally mature was estimated using the inverse
logit of the effects of a spatial field, spatially varying coefficients for
the quadratic function of age to account for the potential for skip spawning in
older individuals, a smooth effect of calendar day modeled with penalized
(P-spline) regression [@EilersMarx1996], a linear offset for fishery-dependent
samples, and year effects as a quadratic function of modeled subsurface
(130.67 m) temperature indices in the domain of the West Coast Groundfish
Bottom Trawl Survey [@LelloucheEtAl2021]. The model is
\begin{align}
E[\bm{y}] = g^{-1} \left( \bm{X} \bm{\beta} + \bm{Z} \bm{b} + \bm{\omega}_{s} +
\bm{x}_{age} * \bm{\zeta}_{s,age} + \bm{x}_{age^{2}} * \bm{\zeta}_{s,age^{2}}
\right),
\end{align}
where $g^{-1}()$ represents the inverse-logit function, $\bm{X}$ represents
the design matrix of fixed effects with estimated parameters $\bm{\beta}$ that
include the quadratic effects of temperature, the P-spline is represented with
random effect design matrix $\bm{Z}$ and corresponding coefficients $\bm{b}$,
$\bm{\omega}_{s}$ represents a constant spatial field shared across years, and
$\bm{\zeta}_{s,age}$ and $\bm{\zeta}_{s,age^{2}}$ represent spatially varying
coefficient effects of age.
The stochastic partial differential equation approximation to Gaussian Random
Fields [@LindgrenEtAl2011] was used to approximate the spatial field with a
series of estimated random effects. The mesh representing the spatial field
used a cutoff distance of 50 km. The temperature covariate has the potential
to add mechanistic relationships to the modeling and reduce uncertainty in
years where no or few samples are collected.

Biomass-weighted averages of temperature were created using estimates of the
spatial distribution of `r sp` from West Coast Groundfish Bottom Trawl Survey
catch-per-unit-effort data. These estimates were modeled using the same
spatial-GLMM approach as was used for the maturity model with a smooth effect
of calendar day via a P-spline, a time varying intercept modeled with a random
walk, a spatial field, and spatiotemporal variation modeled as a first-order
autoregressive process. A Tweedie distribution [@Shono2008] was used to model
the catches given their skewed nature. Predictions were made to spatial cells
from the GLORYS12v1 re-analysis that were in the spatial domain of the West
Coast Groundfish Bottom Trawl Survey on July 1 (middle of the survey). These
predictions were then used to create a weighted average of temperature across
space.

Maturity-at-age was estimated to be higher in fishery-dependent samples,
medium-aged fish, and in summer months. Spatial patterning was similar across
ages. The estimated marginal effect of temperature indicated a concave
relationship between temperature and functional maturity. Temperatures in 2018
and 2020 were near the peak of this relationship, while most years were cooler.
Temperatures in 2016 and 2019 were high above the threshold corresponding to
the peak of the temperature--maturity relationship, and maturity-at-age was
estimated to decline in these years.

Annual maturity-at-age predictions were made since 2009 using
estimated coefficients for non-A-SHOP samples and day 278 (i.e., October 5th).
Projections were also made forward in time to `r last_data_yr` using available
temperature indices. This forward projection was needed because maturity
information was not sampled in 2022 and data from `r last_data_yr` have yet to
be analyzed. The same biomass estimates used to create biomass-weighted
temperatures were applied to the estimates of probabilities of being mature in
logit space. Estimate of the spatial variance was higher than the estimate of
the spatiotemporal variance for the biomass estimates suggesting that
differences in locations are more prominent than differences in locations
between years. That is, `r sp` have a patchy distribution but those patches
appear in largely the same locations year after year. The center of gravity
of the distribution was furthest to the north in years that corresponded to
high temperatures and subsequent decreases in maturity. The total weighted
average maturity for each age--year combination was converted to normal space
with an inverse-logit transformation.

Time-varying fecundity-at-age (Figure~\@ref(fig:main-fecundity-at-age-fig)) was
calculated by using year-specific weight-at-age estimates multiplied by
year-specific maturity-at-age [@JTC2019] estimates. The methods used to
estimate early (before 2009) and projection period weight at age were also used
to estimate maturity for these time periods. Additionally, samples from
age-15$+$ fish were pooled for both the maturity and weight-at-age estimation
due to limited sample sizes. Consequently, the age 15$+$ estimates were applied
to ages 15--20 in the population dynamics model
(Figure~\@ref(fig:main-maturity-ogive-fig)).

Some fish at almost every age were found to be functionally immature based
on histological criteria. Older, functionally immature fish are a combination
of 'skip spawners' that will not be spawning in the upcoming year and
senescent fish that appear to no longer have viable ovaries. Results from
ongoing research investigating the impacts of functionally immature
individuals on estimates of female spawning biomass could help refine the
fraction of fish mature at each age.

Tissue samples have been collected from many of the same fish from which
ovaries were sampled. In the future, these tissue samples may help determine
whether the fish south of 34$^\circ$ 44$^\prime$ N. Lat. are from the same
population as the rest of the coastal population via genetic analyses.

### Ageing error {#sec:data-ageing-error}

The large inventory of `r sp` age determinations includes many duplicate reads
of the same otolith, either by more than one laboratory or by more than one
age reader within a laboratory. Recent west coast groundfish and `r sp` assessments have utilized the
cross- and double-read approach to generate an ageing-error matrix describing
the imprecision and bias in the observation process as a function of fish age.
New data and analyses were used in the 2009 assessment to address an additional
process influencing the ageing of `r sp`, namely cohort-specific ageing error
related to the relative strength of a year-class. This process reflects a
tendency for uncertain age determinations to be assigned to predominant year
classes. The result is that the presence of strong year classes is inflated in
the age data while neighboring year classes are under-represented relative to
what would be observed if ageing error was consistent with age across cohorts.

To account for these observation errors in the model, year-specific
ageing-error matrices (defined via vectors of standard deviations of observed
age at true age) are applied, where the standard deviations of strong year
classes are reduced by a constant proportion. For the 2009 and 2010
assessments, this proportion was determined empirically by comparing
double-read error rates for strong year classes with rates for other year
classes. In 2010, a blind double-read study was conducted using otoliths
collected across the years 2003--2009. One read was conducted by a reader who
was aware of the year of collection, and therefore of the age of the strong
year classes in each sample, while the other read was performed by a reader
without knowledge of the year of collection, and therefore with little or no
information to indicate which ages would be more prevalent. The results were
analyzed via an optimization routine to estimate both ageing error and cohort
effect. The resultant ageing error was similar to the ageing error derived
from the 2008 analysis. Since 2011, cohort-specific ageing error has been
used to reduce the ageing-error standard deviation by a factor of 0.55 for the
following largest cohorts: 1980, 1984, 1999, 2010, and 2014. In the 2014 base
model [@JTC2014], the 2008 cohort was also included in this set but
subsequent estimates show this year class to not be as strong as previously
thought, and thus, cohort-specific ageing error has not been included for the
2008 cohort since 2015. Also, cohort-specific ageing error does not include
the reduction in ageing error for age-1 fish under the assumption that they
never represent a large enough proportion of the samples to cause measurement
error related to the cohort-effect.

Additional exchanges of otoliths between ageing labs within the U.S. and
Canada are in process but were not completed in time for this assessment.
The additional across-lab double reads will be informative for updating
the ageing-error matrix. Unfortunately, increased protocols for moving
samples across the border have led to delays.

## Estimated parameters and prior probability distributions {#sec:data-estimated-parameters}

Several prior distributions
(Table~\@ref(tab:main-parameters-estimated-summary-tab)) are
used to fit the model. The priors that are assumed to be informative are
discussed below.

### Natural mortality {#sec:data-natural-mortality}

Since the 2011 assessment, a combination of the informative prior for natural
mortality used in previous Canadian assessments and results from analyses
using Hoenig's method [@Hoenig1983] support the use of a `r m_prior[1]`
distribution with a median of `r f(exp(as.numeric(m_prior[2])), 2)` and a
standard deviation (in log space) of `r m_prior[3]`. Sensitivity to this prior
has been evaluated extensively in many previous assessments of `r sp`
(see @JTC2013 for a discussion of the historical treatment of natural
mortality and its prior) and is repeated here (see Section
\@ref(sec:assessment-sensitivity-analyses)), including increasing the prior
standard deviation and using an alternative prior distribution based on a life
history meta-analysis [@Hamel2015; @HamelCope2022]. The
Hamel--Cope prior used a lognormal prior distribution with a median of 0.22
(based on a maximum age of 25) and a standard deviation (in log space) of 0.31.
Alternative prior distributions for natural mortality typically have a
significant impact on the model results. But in the absence of new information
on natural mortality there has been little option to update the prior.

### Steepness {#sec:data-steepness}

The prior for the steepness parameter of the stock--recruitment relationship is
based on the median (0.79) and the 20th (0.67) and 80th (0.87) percentiles
from the meta-analysis of the family Gadidae [@MyersBowenEtAl1999] and has
been used in U.S. assessments since 2007. This prior has a beta distribution
with parameters 9.76 and 2.80, which translate to a mean of 0.777 and a
log-standard deviation of 0.113. Sensitivities to the variance on the prior
on steepness were evaluated in the 2012 and 2013 assessments
[@JTC2012; @JTC2013]. Sensitivities to the mean of the prior are explored in
this assessment (see Section \@ref(sec:assessment-sensitivity-analyses)).

### Variability on fishery selectivity deviations {#sec:data-variability-selectivity}

Time-varying selectivity was introduced in the 2014 assessment [@JTC2014] and
is modeled using annual deviations since 1991 applied to the selectivity-at-age
parameters for the fishery. A normal distribution with a fixed standard
deviation ($\Phi=$ `r sel_phi_val`; see @JTC2018 for justification) is used as
a penalty function to keep deviations from straying far from zero. Selectivity
for age-0 fish is fixed at 0.0 and parameters for ages that are estimated
represent the change in selectivity from the next youngest age. Beyond the age
of 6, age-specific parameters are fixed at zero giving constant selectivity
beyond the last estimated value. The condition that maximum selectivity equals
1.0 results in one fewer degrees of freedom than the number of estimated
parameters. Further testing of alternative methods for parameterizing
time-varying selectivity [e.g., @Xu2019] should be investigated in conjunction
with the estimation of additional time-varying parameters.

### Age-composition likelihood {#sec:data-age-comp-likelihood}

Since 2018, the assessment has used the linear formulation of the
Dirichlet-multinomial (D-M) likelihood [@ThorsonEtAl2017Dirichlet] to fit the
age-composition data. Estimated parameters $\theta_{\mathrm{fish}}$ and
$\theta_{\mathrm{surv}}$ serve to automatically adjust the weight given to the
fishery- and the survey-composition data, respectively. As of 2021, Stock
Synthesis includes the constant of integration in the likelihood calculation
for the D-M model such that likelihoods are comparable across weighting
methods.

Integration of weighting the composition data within the assessment increases
the efficiency of the assessment process, removes the subjective choice of how
many iterations are required, and ensures that the results of model
sensitivities, retrospective analyses, and likelihood profiles are
automatically tuned, rather than having the age compositions be given the same
weight as the base model. Note that the following description holds for both
the survey data and the fishery data, with $\theta$ equal to
$\theta_{\text{surv}}$ or $\theta_{\text{fish}}$, respectively.

The likelihood function for the linear parameterization of the D-M likelihood
(see Equation 10 of @ThorsonEtAl2017Dirichlet) is

\begin{align}
\text{L}(\bm{\pi},\theta|\bm{\tilde{\pi}},n) &= \frac{\Gamma(n+1)}{\prod\limits_{a=1}^{A_{\scriptscriptstyle{\text{max}}}} \Gamma(n\tilde{\pi}_a + 1)} \frac{\Gamma(\theta n)}{\Gamma(n + \theta n)} \prod\limits_{a=1}^{A_{\scriptscriptstyle{\text{max}}}} \frac{\Gamma(n \tilde{\pi}_a + \theta n \pi_a)}{\Gamma(\theta n\pi_a)},
\end{align}

where
$\tilde{\pi}_a$ is the observed proportion at age $a$,
$\pi_a$ is the corresponding expected proportion at age $a$ estimated
by the model,
$\bm{\tilde{\pi}}$ and $\bm{\pi}$ designate the vectors of these proportions,
$A_{\text{max}}$ is the maximum age in the model,
and $n$ is the input sample size. The parameter $\theta$ is defined as a
linear scaling parameter such that $\theta n$ is the variance-inflation
parameter of the D-M distribution. The linear parameterization has been shown
to be superior over the saturation parameterization in simulation testing
[@FischAhrensEtAl2022], and thus, corroborates our decision to continue to
use it even though the saturation parameterization is available in Stock
Synthesis.

The effective sample size ($n_{\mathrm{eff}}$) associated with this likelihood
is given by

\begin{align}
n_{\mathrm{eff}} &= \frac{1}{1 + \theta} + \frac{n \theta}{1 + \theta}.
\label{DMeff}
\end{align}

The input sample sizes used in this assessment, which are based on the number
of trips and/or hauls, are large enough that the first term is insignificant
compared to the second term. Consequently,
$\theta / (1 + \theta)$ can be compared to the sample size multipliers used in
the McAllister--Ianelli (M-I) data-weighting method
[@McAllisterIanelli1997] that was used for assessments prior to 2018
(Table~\@ref(tab:main-assessment-changes-tab)) and
as a sensitivity here (see Section~\@ref(sec:assessment-sensitivity-analyses)).
In short, the M-I method involves iteratively adjusting multipliers of the
input sample sizes passed to the multinomial likelihoods until they are roughly
equal to the harmonic mean of the effective sample sizes. The effective sample
size is dependent on how well the model expectation matches the observed
values. Typically, this process involves no more than four to five iterations.

A uniform prior between $-5$ and $20$ for
$\log \theta_{\text{fish}}$ and $\log \theta_{\text{surv}}$ tends to lead to
inefficient sampling of $\log \theta_{\text{surv}}$ because many
samples occur in a part of the parameter space where the effective sample
size multiplier, $\theta_{\text{surv}} / (1 + \theta_{\text{surv}})$, is
between 0.99 and 1.0 [@JTC2019]. In that area, the input sample sizes given
the uniform prior have full weight and the likelihood surface is almost
completely flat with respect to
$\log \theta_{\text{surv}}$. The current prior on $\log \theta_{\text{surv}}$
can be associated with an approximately uniform prior of the weight
$\theta_{\text{surv}} / (1 + \theta_{\text{surv}})$, where the parameters of
the normal distribution were back-calculated from a uniform distribution with
the bounds of 0 and 1 [@JTC2020]. The normal prior for both
$\log \theta_{\text{fish}}$ and $\log \theta_{\text{surv}}$ has a mean of
`r effn_prior[2]` and a standard deviation of `r effn_prior[3]`.

Composition data can also be weighted using the Francis method [T2.6 in Table
2 of @Francis2011], which is based on variability in the observed ages by year.
This method, like the M-I method, is iterative, where the sample sizes are
adjusted such that the fit of the expected mean age should be within the
estimated uncertainty at a rate that is consistent with the variability
expected given the effective sample sizes. The Francis method is known to be
sensitive to outliers and prone to convergence issues when selectivity varies
with time. As a result, the Francis method was not included as a sensitivity.
