
\rfoot{Assessment}

# Assessment {#sec:assessment}

## Modeling history {#sec:assessment-modeling-history}

In spite of the relatively short history of fishing, `r sp` have surely been
subject to a larger number of stock assessments than any marine species off the
west coast of the U.S.A.~and Canada. These assessments have included a large
variety of age-structured models. Initially, a cohort analysis tuned to fishery
CPUE was used [@FrancisSwartzmanEtAl1982]. Later, the cohort analysis was
tuned to National Marine Fisheries Service (NMFS) triennial acoustic survey
estimates of absolute biomass at age [@HollowedAdlersteinEtAl1988].
Since 1989, Stock Synthesis models (or base versions of it) fit to
fishery catch-at-age data and acoustic survey estimates of population biomass
and age composition have been the primary assessment method.

While the general form of the age-structured assessment has remained similar
since 1991, modeling procedures have been modified in a variety of ways. There
have been alternative data choices, post-data collection processing routines,
data-weighting schemes, structural assumptions for the stock assessment model,
MCMC sampling algorithms, and control rules
(Table~\@ref(tab:main-assessment-changes-tab)). Analysts are constantly trying to
improve the caliber and relevance of the assessment by responding to new
scientific developments related to statistics and biological dynamics, policy
requirements, and different or new insights brought up during the peer review
process to ensure a robust stock assessment.

Data processing, filtering, and weighting choices have been modified several
times since the first assessment. For example, modifications to the
target-strength relationship used to scale acoustic data changed in 1997
[@DornSaunders1997], and kriging was implemented to account for the spatial
correlation in the acoustic data in 2010 [@StewartHamel2010]. While survey
data have been the key index for biomass since 1988, surveys that have been
used have varied considerably. The Alaska Fisheries Science Center/Northwest
Fisheries Science Center West Coast Triennial Shelf Survey was used from 1988
before being discarded from the 2009 assessment [@HamelStewart2009]. Acoustic
surveys from the years prior to 1995 were used for assessments in the early
1990s, but @StewartForrestEtAl2011 reviewed these early surveys and deemed
that sampling was insufficient to be comparable with more recent data. Several
recruitment indices have been considered but ultimately none were identified
as adding appreciable contribution to model results [@HelserDornEtAl2002;
@HelserFleischerEtAl2005; @StewartHamel2010], except for the
fishery-independent acoustic-based age-1 index which has been included in the
base model since the 2022 assessment. The process for generating
fecundity-at-age from the combination of weight-at-age and maturity data changed
in 2019 from using time-invariant to year-specific weight-at-age values. In 2024,
time-varying maturity ogives were also added to the calculation of fecundity-at-age
(see Section~\@ref(sec:data-maturity) for details). Even where data have
been consistently used, the weighting of these data in the statistical likelihood
has changed through the use of various emphasis factors (e.g., @Dorn1994,
@DornSaundersEtAl1999), a multinomial sample size on age compositions (e.g.,
@DornSaundersEtAl1999, @HelserDornEtAl2002, @HelserFleischerEtAl2005,
@StewartForrestEtAl2011), internal estimations of effective sample size using
the Dirichlet-multinomial distribution [@JTC2018], and assumptions regarding
year-specific survey variance. Since 2021, a more computationally efficient
Bayesian MCMC sampler (No-U-Turn Sampler; NUTS; @HoffmanGelman2014) was used
to estimate posterior distributions [@Monnahan2018; @Monnahan2019], a change
from previous assessments that used the random walk Metropolis Hastings (rwMH)
sampler (details described in @JTC2021). The list of changes discussed above
is for illustrative purposes only and represents a small fraction of the
different choices analysts have made and that reviewers have required.

The structure of the assessment models has perhaps had the largest number of
changes. In terms of spatial models, analysts have considered
spatially explicit forms [@Dorn1994; @Dorn1997], spatially implicit forms
[@HelserStewartEtAl2006], and single-area models [@JTC2012]. Predicted
recruitment has been modeled by sampling historical recruitment (e.g.,
@Dorn1994, @HelserFleischerEtAl2005), using a stock-recruitment
relationship parameterized using maximum sustainable yield (MSY) and
the fishing mortality rate estimated to produce the MSY (`r f_msy`;
@Martell2010), and using several alternative steepness priors [@JTC2012;
@JTC2013]. Selectivity has also been modeled in several ways: invariant
[@JTC2012; @JTC2013], time-varying with [@HelserDornEtAl2002] and without
[@Dorn1994; @DornSaunders1997; @JTC2012; @JTC2013] a random walk,
alternative levels of allowable deviation through time [@JTC2013; @JTC2017],
age-based [@Dorn1994; @DornSaunders1997; @JTC2012; @JTC2013], and length-based
[@HelserMartell2007].

Several harvest control rules have been explored for providing catch limits
from stock assessment output. `r sp` stock assessments have presented decision
makers with constant *F*, variable *F*, and the following
hybrid control rules: `r fspr_35`, `r fspr_40`, `r f_40_40_10`, `r fspr_45`,
`r f_45_40_10`, and `r fspr_50` (e.g., @Dorn1996, @JTC2013). Changes to
policies such as the United States' National Standards Guidelines in
2002 and the `r f_40_40_10`` harvest control rule in the Agreement
(Appendix~\@ref(sec:app-glossary)) have required specific changes to control
rules.

In addition to the examples given above and changes documented in stock
assessments, there have been many more investigations conducted at review
panel meetings. Starting in 2013, the addition of the MSE [@JTC2013;
@JacobsenEtAl2021] facilitated investigating changes to the modeling
procedure in terms of pre-specified objectives that aim for a sustainable
coast-wide fishery.

## Description of base model {#sec:assessment-base-model}

The `r assess_yr` base model has the same general population dynamics structure as the
`r last_assess_yr` assessment's base model. The statistical-catch-at-age model
assumes that the `r sp` population is a single coast-wide stock subject to
one aggregated fleet with combined male and female population dynamics. Stock
Synthesis [@MethotWetzel2013] version `r ss_version` was the modeling platform
used. The largest change between the `r last_assess_yr` and `r assess_yr`
stock assessments is the addition of another year of fishery and survey data, an
age-1 index data point, and time-varying maturity information integrated into the
base model.

The `r assess_yr` base model includes a time series (1995 to
`r last_survey_yr`) of acoustic age-2+ biomass estimates and acoustic
estimates of age-1 fish (see Section~\@ref(sec:data-acoustic-survey) for more
details on the age-1 index). Maturity is assumed to be time-invariant prior to 2009,
and time-varying, with the integration of annual maturity ogives informed by sea
temperature at depth, since 2009 (see Section~\@ref(sec:data-maturity)).
Fecundity is time-varying as defined by annual weight-at-age
multiplied by annual maturity ogives (`r start_yr_age_comps`--`r last_data_yr`;
additionally see Section~\@ref(sec:data-weight-at-age)). The D-M likelihood approach
[@ThorsonEtAl2017Dirichlet] is used to estimate the weights associated
with age-composition data, rather than iteratively tuning the sample size
multiplier as in 2017 and earlier assessments (see
Section~\@ref(sec:data-age-comp-likelihood)). Time-varying fishery
selectivity is retained in the `r assess_yr` base model with the magnitude
of the allowable deviations unchanged from the `r last_assess_yr` base model
(see Section~\@ref(sec:data-variability-selectivity)). The general
parameterization of selectivity was retained, although additional parameters
were required to estimate an additional year of deviations. The selectivity
of the acoustic survey is assumed to be time invariant. Selectivity curves
were modeled as non-parametric functions estimating age-specific values for
each age beginning at age-2 for the index of age-2+ biomass and age-1 for
the fishery until a maximum age of 6, after which all ages are assumed to have
the same selectivity. Selectivity for the age-1 index was set to one for age-1
and zero for all other ages.

Prior probability distributions are used for a select few parameters and fixed
values are used for several parameters. For the base model, the instantaneous
rate of time-invariant natural mortality (M) is estimated with a `r m_prior[1]` prior
having a median of `r f(exp(as.numeric(m_prior[2])), 2)` and a standard
deviation (in log-space) of 0.1 (see
Section~\@ref(sec:data-natural-mortality)). The stock-recruitment function is
a Beverton-Holt parameterization, with the log of the mean unexploited
recruitment (log~`r r_0`) freely estimated. This assessment uses the same
beta-distributed prior for stock-recruit steepness (h), based on
@MyersBowenEtAl1999, that has been applied since 2011
[@StewartForrestEtAl2011]. Year-specific recruitment deviations were estimated
from `r main_recdev_early`--`r main_recdev_end + 1` as well as the years
`r assess_yr - 1`--`r assess_yr + 3` for purposes of forecasting. The standard
deviation, $\sigma_r$, of recruitment variability serves as a recruitment
deviation constraint and is fixed at `r base_model$sigma_R_in` in this
assessment. This value is based on consistency with the observed variability
in the time series of recruitment deviation estimates and is the same as
assumed in assessments from 2013 to `r last_assess_yr`
(Table~\@ref(tab:main-assessment-changes-tab)). Catchabilities associated with the
biomass index (q~b~) and with the age-1 index (q~1~) were calculated
analytically as per @LudwigWalters1981 for each sample of posterior parameters,
resulting in a distribution of catchability for each.

Statistical likelihood functions used for data fitting are typical of many
stock assessments. The biomass index was fit via a lognormal likelihood
function, using the observed (and extra 2009) sampling variability, estimated
via kriging, as year-specific weighting. The age-1 index was also specified as
having lognormal error structure. An additional constant and additive standard
deviation on the log-scale component is included for both the biomass index
and the age-1 index, which were freely estimated to accommodate
unaccounted-for sources of process and observation error. A D-M likelihood was
applied to age-composition data, with input sample sizes equal to the sum of
the number of trips and hauls sampled across all fishing fleets or the number
of trawl sets in the research surveys
(see Section~\@ref(sec:data-age-comp-likelihood)).

Model results and statistical inference were based on
`r f(num_mcmc_samples)` MCMC samples (using the \texttt{adnuts} R package;
@Monnahan2018) to describe posterior distributions for model
parameters and derived quantities. The number of samples used for bridging
models, sensitivity models, and retrospective models was also
`r f(num_mcmc_samples)`. Medians (50% quantiles) are reported together with
the bounds of 95% credibility intervals calculated as the 2.5% quantile and
the 97.5% quantile of posterior distributions from the MCMC samples, to
give equal-tailed intervals. A full explanation of the NUTS algorithm and the
\texttt{adnuts} package, including an analysis with the `r sp` stock can be found
in @Monnahan2019.

## Response to `r end_yr - 1` Scientific Review Group (SRG) review {#sec:assessment-response-review}

The Scientific Review Group (SRG) meeting was held from February
7--10th, 2023, at the Graduate Hotel, Seattle, WA, U.S.A.

The following are the 'SRG Recommendations and Conclusions for the Stock
Assessment' from the 2023 SRG report and the associated responses from the
JTC:

1. **Pacific Hake dynamics are highly variable even without fishing mortality. The SRG
applauds the efforts of the JTC and the MSE Working Group to add capabilities for
estimating dynamic reference points within the assessment and MSE, and encourage
those groups to jointly develop alternative reference points, including dynamic
reference points, for future SRG consideration.**

> TODO HERE IS WHAT WE HAD IN 2023 for the same request; note this request is quite
> closely tied to number 3.
>
> *Response -- The JTC agrees that future reference point discussions
> stemming from simulation work, preferably through the MSE, would be
> beneficial. In particular, the JTC continues to have interest in exploring
> the utility of dynamic reference points. The MSE can now utilize dynamic
> reference points in management procedure scenarios, and Stock Synthesis
> models can now incorporate dynamic reference point capabilities into
> routine stock assessment output. In the coming year, the JTC plans to
> initiate simulations that explore alternative dynamic F-based target
> reference points coupled with static (equilibrium-based) biomass limit
> reference points in exploratory harvest control rule scenarios.*

> *Over the past year [2022; so definitely needs updating], the JTC has continued to engage in research
> activities and outreach related to dynamic reference points broadly, as
> well as specifically for `r sp`.  In particular, the JTC conducted a
> learning session at the summer JMC meeting to promote internal awareness
> and basic understanding of the key concepts, methods, and assumptions
> associated with dynamic reference point calculations. The JTC also engaged
> with external partners, the Western and Central Pacific Fisheries
> Commission science provider (Secretariat of the Pacific Community), to
> learn from their experience developing and applying dynamic reference
> points to operational highly migratory species assessments and management
> plans. Additionally, the JTC is contributing to, and following, updates to
> Canadian and United States national guidance documentation on the
> incorporation of prevailing environmental conditions into stock
> assessments and subsequent management advice (e.g., defining reference
> points).*


2. **The SRG also recommends continuing sensitivities for steepness, natural mortality,
$\sigma_R$, excluding the age-1 index, alternative standard deviations for time-varying
selectivity, and using the McAllister-Ianelli method to weight fishery age-
composition data.**

> TODO CHECK THESE ONCE THEY'RE ALL DONE. Issue 1061.
> *Response -- The JTC has conducted all of the requested sensitivities
> (and many others) and provides summaries in written
> (Section~\@ref(sec:assessment-sensitivity-analyses)), tabular (beginning
> with Table~\@ref(tab:main-parameter-estimates-sens-1-tab)), and graphical
> (beginning with Figure~\@ref(fig:main-biomass-base-alternative-1-fig)) formats
> in this document.*

3. **The SRG recommends that the JTC include dynamic unfished spawning biomass in
the 2024 assessment as a comparator with the equilibrium unfished spawning
biomass used to provide management advice. The SRG also encourages the
continued outreach regarding the use of dynamic reference points to stakeholders
and managers, including identifying pros and cons of using dynamic unfished
spawning biomass**

> TODO could mostly link with 1, adding some of the outreach stuff here.
> *Response --
> *

4. **The SRG recommends that the JTC explore alternative ways of estimating natural
mortality to update the current approach in the model, which is based on methods
from more than a decade ago, since newer methods are available. Information
presented during the SRG meeting implies that natural mortality on age-2 Pacific
Hake is higher than currently assumed in the assessment model and should be
explored more fully.**

> *Response --
> *

5. **The SRG encourages an analysis of catch and CPUE distribution for Canada and
US that examines latitudinal shifts in fishing over time.**

> *Response --
> *

6. **The SRG recommends continued work to collect ovary samples and data to develop
a picture of the Pacific Hake reproductive cycle both seasonally, inter-annually and
at the life-time scale based on histological and physiological
measurements. Given the inter-annual variability in age-at-maturity, the SRG recommends that the JTC
explore ways to incorporate time-varying maturity in the stock assessment
model.**

> *Response -- Melissa Head has been working hard to continuously collect
> maturity information for `r sp` since 2009. Up until this assessment,
> maturity was included in the fecundity relationship as a single ogive.
> Maturity-at-age ogives are now estimated for each year since 2009 and used
> to calculate fecundity (i.e., maturity $*$ weight at age). Moreover, the
> relationship between age and maturity includes a coeffient for temperature
> (see Appendix~\@ref(sec:app-maturity-analysis)). This relationship could be
> enhanced in the future by including samples from Canada, samples that have
> previously been analyzed, collected samples that have yet to be analyzed, and
> samples collected during future endeavors. During the JTC meeting, it was
> also brought to our attention that is the potential for samples to be
> collected from the U.S. shoreside sector as well. The JTC, Melissa Head,
> and the Sarah Nayani are investigating the feasibility of this in attempts
> to increase the seasonal coverage of sampling, though winter months will
> still remain sparsely sampled without a decidated winter survey.
> *

7. **The SRG noted that the age-1 index did not include a value for 2001 because it was zero.
Although this decision had negligible influence on the results because the estimate for
2000 recruitment was close to zero, the SRG noted that Stock Synthesis uses a lognormal
likelihood which does not handle zero values. Given that future zero values are expected
to have a bigger influence on the results in the short-term, the SRG recommends that
the JTC explore likelihood forms that can fit to very low index values from the age-1
survey (e.g., robust likelihood). The SRG acknowledges that implementing new
likelihoods will require changes to the Stock Synthesis platform.**

> *Response -- A student-t distribution was implemented for the relative age-1
> index of abundance. The student-t distribution cannot accommodate values of
> zero but it does allow for fatter tails than the lognormal distribution.
> Secondly, the student-t distribution is known to provide more accurate
> estimates of the variability of the sample mean for small sample sizes than
> the lognormal when the standard deviation is unknown or imprecise. In the
> future, additional distributions should be investigated that can accommodate
> values of zero but this change was seen as a positive step forward until the
> survey team can estimate the variability of the survey.
> *

8. **Given the importance of the age-1 index in estimating the size of the age-classes entering
the fishery, the SRG recommends that the JTC implement updated age-1 index CVs,
when they are provided by the Survey Team, in the stock assessment model.**

> *Response -- Updated coefficients of variation were not provided by the Survey
> Team; so, the fixed values of 0.5 were retained but a student-t distribution
> was used to fit the survey instead of a lognormal (see the above response).
> *

9. **A new at-sea sampling program in the Canadian freezer-trawler fleet was implemented in
2022 involving vessel crews sampling 50 fish per tow from two tows per trip. The SRG
recommends that Canada consider sampling fewer fish from more tows to spread
the sampling out and provide a more representative sample of fishery catches.**

> *Response -- This will be implemented starting with the 2024 fishing season.
> *

10. **The SRG encourages the JTC to consider methods to determine the maximum input
sample size for the age compositions [e.g. @StewartHamel2014].**

> TODO update this response from 2023, issue 1069:
>
> *Response -- The JTC concurs that determining maximum input sample sizes,
> as well as relative maximums across years, is a worthwhile endeavor.
> Determining appropriate input samples sizes for composition data is a
> long-standing issue with much debate. Progress made for `r sp` will
> undoubtedly provide useful for stock assessment more broadly. The JTC has
> yet to undertake any specific analyses investigating input sample sizes.
> Researchers at the Alaska Fisheries Science Center have recently begun
> similar inquires, indicating that a collaborative approach may be mutually
> beneficial.*

11. **The SRG notes that there have been multiple strong cohorts in the stock recently
compared to earlier periods where there was only one strong cohort supporting the stock,
including during the period of sample collection for the ageing error matrix that supports
the assessment model. Therefore, the SRG encourages the resumption of the ageing
error study by the Committee of Age Reading Experts (CARE) using samples
collected during the past decade.**

> *Response -- An ageing error study in conjunction with CARE has commenced,
> including planned sample exchanges between United States and Canada ageing
> labs. However, a full exchange remains on hold due to difficulties with
> permits to send biological specimens across the border.*

12. **The SRG supports the investigation of alternative selectivity functions, which may
include a two-dimensional autoregressive (AR) approach, which may use
information from the previous year and from adjacent year classes to predict
selectivity.**

> *Response --
> *

**The SRG appreciates the dedication and teamwork displayed by the JTC in producing
the best available scientific information and advice on the Pacific Hake stock.**

> *Response -- Teamwork and collaboration is an attribute of great interest
> and pride within the JTC, and we believe it is fundamental to successfully
> achieving the science objectives as outlined in the Agreement.*



THESE REMAINING ONES ARE FROM 2023 ASSESSMENT -- keeping for now in case we want
to re-use (elsewhere) any of the text that is already formatted with references etc.

1. [2023 assessment text] **The SRG notes that $\sigma_R$ is an influential parameter and that
  determining the choice of $\sigma_R$ remains a challenge and encourages the
  JTC to continue to work on the issue.**

> *Response -- Developing best practices for modeling mean unfished
> equilibrium recruitment (`r r_0`) and recruitment variability ($\sigma_R$)
> remain broad topics of contemporary research. Recent recommendations
> suggest that the next generation of stock assessment modeling frameworks
> should concomitantly treat recruitment deviations as a random effect and
> estimate $\sigma_R$ [@Punt2020]. The JTC continues to conduct,
> collaborate on, and monitor ongoing research projects concerning
> approaches for advancing recruitment estimation, as applied to `r sp` and
> in general. Many of these issues are widespread in stock assessment and
> scientific-based solutions are likely to be the result of medium to
> long-term research projects. Here, we provide a few updates to our previous
> response on this topic, including specific advances in research endeavors
> where applicable.*

> *The JTC continues to participate in collaborative research to investigate
> the concurrent estimation of multiple variance parameters within stock
> assessments. For `r sp`, this includes the estimation of the variability
> associated with time-varying selectivity ($\Phi$), $\sigma_R$, extra
> standard deviation parameters on index data, and Dirichlet-multinomial
> parameters $\theta_{\text{fish}}$ and $\theta_{\text{surv}}$. In this
> assessment, $\Phi$ and $\sigma_R$ are input as fixed parameters because
> Stock Synthesis uses penalized likelihood and therefore is not formulated
> to estimate random effects. Additionally, estimation of these variance
> parameters using MCMC requires the specification of hyperpriors for which
> there has been little research. The Laplace approximation
> [@ThorsonHicksEtAl2015] was investigated as an alternative means to
> estimate these parameters. However, estimates from this method were large
> and simulation shows them to be biased high. Additional research still
> in its infancy suggests that stock assessment frameworks with the ability
> to estimate random effects internally are better at estimating
> autocorrelated processes than random processes. Next steps for the JTC
> include fitting Stock Synthesis to these same data sets to determine
> best practices when variance parameters cannot be estimated and fitting
> a wide variety of stock assessment frameworks to data when multiple random
> processes are present in the true dynamics.*

> *The Management Strategy Evaluation (MSE) framework for `r sp` creates
> considerable advantages for examining recruitment. The stock assessment
> model in the MSE is written in Template Model Builder (TMB), which
> provides efficient estimation of random effects using the Laplace
> approximation, while being parameterized to mimic many (but currently not
> all) of the pertinent features of Stock Synthesis used in this assessment.
> Thus, the performance of using restricted maximum likelihood to estimate
> $\sigma_R$ [@Thorson2019] can be investigated in terms of management as
> well as statistical performance. Research projects using the MSE framework
> are underway to evaluate the robustness of recruitment modeling
> assumptions and the advantages of including environmentally-driven
> recruitment indices on management performance and uncertainty.  Research
> (under review) by Dr.~Cathleen Vestfals and colleagues at the Northwest
> Fisheries Science Center has identified specific climate drivers associated
> with `r sp` early life-history stages and recruitment and is being used to
> select which environmental variables to fit as an index of recruitment
> within the stock assessment model. Further development of
> environmentally-driven recruitment indices using updated environmental
> predictions is also underway. The utility of fitting to a recruitment index
> will be investigated in terms of forecasting skill and management
> performance within the MSE by the MSE working group.*

> *The number of stock assessment frameworks written in TMB or other
> platforms that allow for the estimation of random effects is increasing.
> These frameworks, specifically the Woods Hole Assessment Model (WHAM;
> @StockMiller2021) and State-Space Assessment Model (SAM;
> @NielsenBerg2014) are both peer reviewed and currently being used for
> management. The JTC has fit WHAM to data on `r sp` and explored the
> estimates of several variance parameters that are currently only explored
> via sensitivity analyses in Stock Synthesis. Next steps include fitting
> data using SAM and using estimates from both frameworks as inputs to Stock
> Synthesis.*

> *The JTC is also following work being conducted by the International
> Council for the Exploration of the Sea (ICES) Methods Working Group which,
> among other things, is looking at meta-analytical approaches for
> estimating recruitment parameters. Results from this work could be used to
> develop informative prior distributions on key recruitment parameters.
> Deliverables were put on hold as a result of COVID-19 but the project
> continues to be making progress.*

2. [2023 assessment text] **The SRG recommends exploring alternative methods to simulate recruitment
in the projections. Although Stock Synthesis currently does not have the
capability to characterize a different process other than the assumed lognormal
distribution, improvements such as drawing from past observations or using a
mixture distribution to simulate recruitment should be considered for modelling
platforms in the future.**

> *Response -- The JTC continues to explore approaches to make informed
> decisions about current and future recruitment in projections. The
> inclusion, and associated justification, of the age-1 index in the 2022
> and 2023 base model is one example of this (see
> Sections~\@ref(sec:data-acoustic-survey) and
> \@ref(sec:assessment-base-model)). Additionally, the JTC is working with
> Dr.~Kristin Marshall to further explore the fit of oceanographic and
> environmental variables identified by Dr.~Cathleen Vestfals as being
> informative about the early life history of `r sp` as indices of
> recruitment within Stock Synthesis. Ongoing research includes expanding
> the variables (originally only amalgamated from 1980--2010) to 2010
> onwards to create a single time series, and investigating relationships
> leading to better informed recent, current, and potential near-term
> forecast recruitment estimates.*

> *Available options in Stock Synthesis for recruitment during the
> projection period are the stock-recruitment curve, the
> stock-recruitment curve with a multiplier, and the mean across a
> user-defined time period. The MSE tool could be used to consider
> alternative recruitment distributional assumptions as future research.
> A member of the JTC is on the development team for NOAA's next
> generation stock assessment modeling platform (Fisheries Integrated
> Modeling System; FIMS), which ensures features such as recruitment
> forecast options will be taken into consideration. Plans are for the
> `r sp` stock assessment to be a test model.*

> *The JTC has requested DFO funding to collaborate with Australian, U.S.,
> and Canadian researchers on developing two potential approaches for
> developing an index of age-0 `r sp`. The first approach is based on the
> method of @SuthersWhiteEtAl2022, who proposed and simulation-tested a
> novel method for estimating growth and mortality of fish larvae based on
> size distributions. In 2022, Suthers visited NOAA's Southwest Fisheries
> Science Center to start applying the method to CalCOFI data (which
> include 1.3 million hake larvae) and compare results to estimates of
> recruitment from the last hake assessment [@JTC2022]. The second approach
> will apply a method proposed by @HinchliffePepinEtAl2019 that
> relates the mortality/growth ratio of larval fish to the slope of the
> zooplankton size spectrum (which characterises the size distribution of
> zooplankton) to quantify the recruitment potential of larval `r sp`. The
> proposed work will support collaborations to work on both approaches, will
> utilise recent improvements in fitting size spectra to data
> [@EdwardsRobinsonEtAl2020], and aims to provide new information on `r sp`
> recruitment.*

4. [2023 assessment text] The SRG encourages work to develop a picture of the `r sp` reproductive
cycle both seasonally and at the life-time scale based on histological and
physiological measurements. In addition, the SRG notes that Canadian
samples and those from the winter research cruises should be included in the
maturity analysis. **The SRG encourages continued sampling and analysis to
improve understanding of the `r sp` reproductive cycle.**

> *Response -- `r sp` ovary samples were not collected over the past year,
> but plans include more sample collections in the coming years. Including
> Canadian samples in subsequent maturity analyses still remains a goal, but
> barriers (lab training, capacity, and moving bio-samples across the border)
> still remain. Research is in-progress by Melissa Head (NWFSC) focusing on
> temporal and spatial trends in hake reproduction. The analysis will include
> over a decade of maturity samples, spanning much of the U.S. West Coast.
> The project aims to evaluate how interannual changes affect size and age at
> maturity across a latitudinal gradient and how the timing of spawning and
> rate of skip spawning differs spatio-temporally. A presentation summarizing
> progress to date and future plans is planned for the SRG meeting.*

> *Research being led by Adam Luckenbach at the Northwest Fisheries Science
> Center looking at physiological indices of fish reproductive and metabolic
> status is expected to bolster the current practice of using gonadal
> histology alone for surveyed `r sp` and provide important data to more
> accurately determine the reproductive cycle of females. Data generated to
> date indicate that two types of lipids, triacylglycerols and
> phospholipids, in the livers of `r sp` are inversely related and
> predictive of sexual maturity in females. Levels of these lipids are also
> considerably shifted when aborted, atretic ovarian follicles are observed,
> suggesting that lipid levels may be predictive of skipped spawning, which
> can reduce the effective female spawning biomass. Data analyses will
> continue in 2023. New developments are expected to inform maturity in
> future `r sp` stock assessments.*

6. [2023 assessment text] Based on the preliminary results shown, previous assessments have
correctly predicted an increase or decrease in recruitment and female
spawning biomass in subsequent years, although the projections are usually
less definitive than the current base model results. Given that this
analysis provides some confidence in the current expectations of continued
stock decline, **the SRG recommends that the JTC continue to explore and
refine this analysis for future assessments. The SRG encourages the JTC to
explore, with the JMC and AP, the value of a threshold for specifying the
probability of projected declines or increases of the stock in future
assessments.**

> *Response -- The JTC has again updated this analysis to continue comparing
> estimates from the current base model with forecasts from previous
> assessments (Figures~\@ref(fig:main-historical-1-fig)--
> \@ref(fig:main-historical-retro-bforty-all-fig)). Related, the JTC is
> continuing to explore options for improving recruitment estimation and
> predictions (see Responses~1--4 and~7).*

> *The JTC has not had an opportunity to meet with JMC, AP, or the MSE
> working group to explicitly explore threshold values for specifying the
> probability of projected declines or increases of the stock in future
> assessments. This endeavor is well suited for upcoming MSE-related
> performance metrics discussions.*

8. [2023 assessment text] **The SRG recommends that historical sources of data be investigated to
determine whether they can be used to supplement the weight-at-age matrix**,
including unaged otolith samples (and associated data) from the 1970s that
may be available in the Burke Museum in Seattle.

> *Response -- The JTC has conducted analyses previously showing that small
> changes to historical data have little relevance to current management
> quantities of interest. So at this time, the JTC does not expect small
> amounts of historical weight-at-age data to significantly alter stock
> assessment results used for management decisions. The JTC has not had the
> opportunity to visit the Burke Museum in Seattle to ascertain whether
> `r sp` age structures are available and in a usable state.*

9. [2023 assessment text] Uncertainty in weight-at-age is not accounted for in the stock assessment
and a five-year average of recent observations is used for all years of the
projections. **The SRG requests that the JTC explore alternative methods for
forecasting weight-at-age and evaluate whether they can improve projections.**

> *Response -- It is important to capture key, mechanistic, and/or stochastic
> population processes in stock assessment projections to sufficiently
> characterize levels of prediction uncertainty that are consistent with
> available information to adequately contextualize metrics used to aid
> management decisions. Likewise, it is as important to evaluate the basic
> population-dynamics assumptions used in such projections. Recent, current,
> and future recruitment are perhaps the most influential sources of
> uncertainty in stock assessment projections. As a result, the JTC has
> prioritized research on recruitment, including supporting analyses and
> other related analyses mentioned in this section. Over the next few
> years, the JTC plans to work with the MSE working group on a newly funded
> research project aimed at incorporating environmentally-driven growth into
> the operating model and testing consequences of climate-driven changes in
> recruitment, growth, and movement concomitantly.*

> *Empirical weight-at-age data indicate inter-annual variation in `r sp`
> growth, and this variation could be related to individual cohort effects
> (e.g., large cohorts have a negative growth influence on adjacent
> cohorts). The JTC has future plans to explicitly evaluate these
> relationships using random effects models to partition the variance
> components (year and cohort) in available weight-at-age data and to
> explore spatial patterns [@Indiveroetal2023]. This work could rely or
> build upon research currently in progress by a graduate student looking
> at variation in `r sp` weight-at-age data. The JTC also plans to explore
> new weight-at-age forecasting capabilities in Stock Synthesis (once fully
> tested). A simulation experiment that evaluates the influence of variable
> weight-at-age data relative to other sources of variance in stock
> assessment projections (e.g., recruitment) would also be useful. Until
> this work is completed, the JTC continues to use a recent five-year
> average in the projection period because it is consistent with recent data
> (Figures~\@ref(fig:main-weight-at-age-fig) and
> \@ref(fig:main-weight-at-age-lines-fig)). This assumption is consistent with
> what is allowable within other commonly used stock assessment
> frameworks that accommodate time-varying dynamics.*

11. [2023 assessment text] The use of high-performance computing (e.g., a dedicated server or cloud
computing) allowed for the complete set of assessment results to be
characterized using MCMC at a minimal cost. **The SRG recommends future use
of high-performance computing to provide complete and thorough assessment
results in a timely manner.**

> *Response -- Resources were made available for the JTC to use a new
> high-performance computing network server with 80 processors to complete
> all model runs (bridging, base, sensitivity, retrospectives, and
> forecasts). Another high-performance server unit and two high-performance
> laptops have also been acquired for completing the `r sp` assessment.
> These resources are used for data preparation, diagnostic examination,
> running test models, and exploring alternative model configurations.*

> *A new server was purchased and used to run all the models and for running
> the software that builds the document. The server has 80 Intel Xeon Gold
> CPUs and 128 GB of RAM and is running Ubuntu Linux version 22.04.1 LTS
> which was the newest stable version at the time of writing. The server was
> set up with user account for each JTC member, with a remote desktop server
> (X-Remote Desktop Protocol; XRDP) running for easy access. All connections
> were through a 4096-bit passwordless Secure SHell (SSH) and the server was
> otherwise locked down from a security standpoint. The entire server is
> automatically backed up on a mirrored RAID device once per day, with model
> input files also backed up to a Google drive. If everything were lost the
> models could be re-run very quickly and the document regenerated in full.*

> *Scripts were written in the Bash shell scripting language to allow
> operating system level control and monitoring over parallel model runs.
> Each run was also parallelized internally with 16 chains per model; that
> parallelism was controlled from within R using the \texttt{future} and
> \texttt{furrr} packages. With each model needing 16 CPUs, the JTC were able to
> run 4 models at a time, taking up 64 CPUs and leaving 16 available for use
> in writing and building the document. The total runtime for these models
> is now on the order of 1-3 hours, depending on the CPU and memory load on
> the server at the time.*

> *The server setup allowed all JTC members to work together in a way not
> possible before. This integrated setup will ensure an ideal workflow in
> the coming years, with a centralized system housing all model runs and
> document software.*

12. [2023 assessment text] The SRG appreciates the investigation of alternative model structures,
including alternative modelling platforms. **The SRG encourages the JTC
to continue these types of investigations.**

> *Response -- The JTC continues to explore the implementation of a
> hake-like assessment in WHAM and SAM, in addition to the custom TMB
> estimation model used in the MSE, to evaluate the impact of
> platform-specific configurations, assumptions, and capabilities.*

## Modeling results {#sec:assessment-modeling-results}

### Changes from `r last_assess_yr` {#sec:assessment-changes}

A set of `bridging' models was constructed to evaluate the component-specific
effects of the steps to change from the `r last_assess_yr` base model to
the `r assess_yr` base model. The steps are:

- Update to the latest version of Stock Synthesis, version `r ss_version`, to
follow current best practices;
- Incrementally update catch, weight-at-age, age-1 survey, and fishery age composition data from
years previous to `r last_data_yr` (in that order);
- Incrementally add `r last_data_yr` catch, weight-at-age, biomass survey, survey
age composition, age-1 survey, and fishery age composition data (in that order);
- Change the error distribution associated with the age-1 survey index from lognormal
to Student's t-distribution;
- Use a model-based matrix of input weight-at-age data; and
- Incorporate model-based estimates of time-varying maturity ogives into the
calculation of time-varying fecundity.


Stock Synthesis version `r ss_version` includes a number of changes since the
version used by @JTC2023. However, none of the changes were specifically relevant
to this assessment, and thus the software update had no effect on assessment
results (Figure~\@ref(fig:main-bridge-summary-fig-1).

The update of pre-`r last_data_yr` data occurs because databases are
continually updated; this yielded minor adjustments to the data. For example,
samples that were recently aged but not available for the `r last_assess_yr`
assessment were included. Updates to pre-`r last_assess_yr` data were
small enough that they had little impact on the model results.

The addition of the `r last_data_yr` catch and weight-at-age data extends the
model to the start of `r assess_yr`. Recruitment estimates and historical stock
trajectory were relatively unchanged, and the new data suggest a slight decrease in female
spawning biomass from `r assess_yr - 1` to `r assess_yr`
(Figure~\@ref(fig:main-bridge-summary-fig-1)).

Including the `r last_data_yr` fishery-independent biomass estimate led to a downward shift
in the stock trajectory going back to 2017 and a similar shift in the fit to the survey
(Figure~\@ref(fig:main-bridge-summary-fig-1)). Whereas including the `r last_data_yr` survey
biomass age compositions had a negligible effect on the stock trajectory, but it did slightly
adjust estimates of recent recruitment strength. The addition of `r last_data_yr` age-1
index led to a predicted increase in stock biomass from 2023 to 2024 as a result of  small shifts in expected recruitment, particularly for the 2020 and 2022 year classes.

The final step of adding `r last_data_yr` data involved incorporating fishery age-composition
information, which shifted the ending year of the deviations in the selectivity parameters
from `r last_data_yr - 1` to `r last_data_yr`. These data had relatively
little impact on the historical biomass estimates, but did shift recent
spawning stock biomass estimates upwards (Figure~\@ref(fig:main-bridge-summary-fig-1)).
Recruitment increased in 2021 and 2022, while the 2020 cohort
was reduced. The increase in 2021 and 2022 recruitment contributes
to the increase in female spawning biomass by the start of
`r assess_yr`, as these fish are considered mostly mature at the start of
`r assess_yr`. Despite both fishery age compositions and the relative age-1
index pointing towards above average cohorts in 2020, 2021 and, to a lesser
extent, 2022, estimates of `r assess_yr` female
spawning biomass remain highly uncertain (Figure~\@ref(fig:main-bridge-summary-fig-1).

Structurally changing the error distribution for the age-1 survey index from a
lognormal to a Student's t-distribution (with a degrees of freedom of 13) had
negligible effect on assessment results (Figure~\@ref(fig:main-bridge-summary-fig-2)).
Nonetheless, the t-distribution is better suited for these data given the low sample
size (14) and broader distribution tails compared to a lognormal when sample sizes
are less than 30.

Input weight-at-age data were constructed using a model-based approach
(see Section~\@ref(sec:data-weight-at-age) for details) to better inform
changes in weight-at-age for years and ages when there is little or no
data. Model predictions were based on a smoothed fixed effect for age and
random effects by year and cohort. During periods of more consistent sampling
protocols (since the mid-1990s), there was little effect on overall stock
size or status ((Figure~\@ref(fig:main-bridge-summary-fig-2)). However, there
were refinements to stock size and status during the 1970s and 1980s, a period
when sampling protocols were not as well documented (e.g., from foreign
vessels).

Lastly, model-based estimates of time-varying maturity ogives were
were incorporated into the calculation of time-varying fecundity
(see Section~\@ref(sec:data-maturity) for details). This is
in addition to using time-varying weight-at-age, which improves the assessment
model inputs that translate total biomass to spawning biomass. The addition of
time-varying maturity resulted in annual differences in the age at which
`r sp` mature, such that there were shifts in the translation of total
biomass to spawnwing biomass by one year in some cases within the time
series ((Figure~\@ref(fig:main-bridge-summary-fig-2)). While the general
trend in spawning stock biomass and population status remained largely the
same, there were reductions in both in the most recent years (2023 and 2024).

### Assessment model results {#sec:assessment-model-results}

**Model Fit**

Stationarity of the posterior distribution for model parameters was assessed
via a suite of standard single-chain and multi-chain diagnostic tests
via graphical summaries and interactive web applications
([ShinySTAN](https://mc-stan.org/users/interfaces/shinystan)).
Key diagnostic figures are given in Appendix~\@ref(sec:app-mcmc-diagnostics) and
now discussed. All estimated parameters showed good mixing during sampling,
no evidence for lack of convergence, and acceptable autocorrelation (results
for some key parameters are shown in
Figures~\@ref(fig:app-mcmc-diag-m-r0-fig)--\@ref(fig:app-mcmc-diag-dm-fig)).
Correlation-corrected effective sample sizes were sufficient to summarize the
posterior distributions and neither the Geweke nor the Heidelberger and Welch
statistics for these parameters exceeded critical values more frequently than
expected via random chance (Figure~\@ref(fig:app-mcmc-diag-hists-fig)). The
Gelman-Rubin multi-chain diagnostic test, which compares within-chain variance
to among-chain variance, further indicated that convergence was adequately
achieved (examined via \texttt{ShinySTAN}). Correlations among key parameters were
generally low, with the exception of M and $\log R_0$
(Figure~\@ref(fig:app-mcmc-pairs-fig)). Estimates of recruitment in 2014 and
2016 were correlated with the derived quantity of catch from the default
harvest rule in `r end_yr`, as to be expected given the dependencies among
these quantities (Figure~\@ref(fig:app-mcmc-pairs-fig)). An examination of
deviations in recruitment (log-scale differences between estimated and
expected recruitment values) from recent years
(Figure~\@ref(fig:app-mcmc-pairs-recruit-devs-fig)) indicates the highest
correlation (`r f(base_model$mcmcvals$rec_cor_2014_2016, 2)`)
was between the 2014 and 2016 recruitment deviations. This is an increase in
correlation relative to the last assessment despite the fact that each cohort
has been observed for an additional year.

Regarding the Dirichlet-multinomial parameter $\theta_{\text{fish}}$,
the estimate (median and 95% credible interval) for
$\log \theta_{\text{fish}}$ is `r f(log_theta_fishery_median, 3)`
(`r f(log_theta_fishery_lower, 3)`, `r f(log_theta_fishery_upper, 3)`), giving an
effective sample size multiplier
$\theta_{\text{fish}} / (1 + \theta_{\text{fish}})$ of
`r f(dm_weight_fishery_median, 3)` (`r f(dm_weight_fishery_lower, 3)`,
`r f(dm_weight_fishery_upper, 3)`).
The related survey age-composition parameter $\theta_{\text{surv}}$ has
\protect{$\log \theta_{\text{surv}}$} estimated as
`r f(log_theta_survey_median, 3)` (`r f(log_theta_survey_lower, 3)`,
`r f(log_theta_survey_upper, 3)`), and the resulting effective sample size
multiplier $\theta_{\text{surv}} / (1 + \theta_{\text{surv}})$ of
`r f(dm_weight_survey_median, 3)` (`r f(dm_weight_survey_lower, 3)`,
`r f(dm_weight_survey_upper, 3)`).

The base model fit to the acoustic survey biomass index
(Figure~\@ref(fig:main-survey-index-fit-mcmc-fig)) remains similar to the
`r last_assess_yr` base model, which is not surprising given no new survey
information is available for this assessment. For the
`r last_assess_yr` base model the `r survey_end_yr` survey biomass estimate
resulted in a slight upward shift in the fit to the `r penult_survey_yr`
survey data points, but the result of a relatively stable biomass trend from
2013--2019 remained unchanged from the previous assessment. At the time, the
addition of the 2021 fishery data was the main reason for this change in fit
to the 2019 data point. The 2021 survey estimate was lower than in 2019
(second lowest since 2013), and the model fit indicates a slight decline in
biomass from 2019 to 2021. The 2001 survey biomass index continues to be well
below any model predictions that were evaluated, and no direct cause for this
is known.  The survey did begin earlier that year than all other surveys
between 1995 and 2009 (Table~\@ref(tab:main-survey-history-tab)), which may
explain some portion of the anomaly, along with El Nio conditions and age
structure. The underestimation of the 2009 biomass estimate is larger than
the underestimation of any other year. The uncertainty of this point (both
modeled and actual) is high because of the presence of large numbers of
Humboldt Squid during the survey. Humboldt Squid have similar target
strength to hake which could introduce bias in the biomass estimate for that
year, and which also likely influenced hake population dynamics through
predation in that year.

The median posterior density estimates from the fit to the survey were less
than the 2015 survey index, greater than the 2017 and 2019 survey indices,
and closely fit the 2021 index (Figure~\@ref(fig:main-survey-index-fit-mcmc-fig)).
This is likely due to slight differences in what the fishery composition data
and survey composition data, when considered independently, would otherwise
suggest as population trends. Additionally, the population has undergone
recent high, but declining, catch levels and produced a couple of
above-average cohorts that are now mature.

The base model fit to the index of age-1 fish highlights an overall general
confirmation of relative cohort strength
(Figure~\@ref(fig:main-age1-index-fit-mcmc-fig)). In particular, the 2008 and 2014
cohorts were estimated to be less than the index, while the 1994 and 2016
cohorts were estimated to be larger than indicated by the index. The age-1
fish in 2011 (the large 2010 cohort) was closely fit.  Age-1 fish in 2021
(2020 cohort) were estimated slightly above the index value and, being so
young, include a large amount of uncertainty. The model indicates that the
2020 cohort may be similar in size to the 2014 cohort, based on information
in the age-1 index, age-1 fish caught in the 2021 fishery, and from age-2
fish caught in the 2022 fishery. The high age-1 survey index from 2021 is
largely in concurrence with oceanographic conditions, as summarized in
NOAA's annual Ecosystem Status Report of the California Current
[@HarveyGarfieldEtAl2021]. Recruitment is generally impacted by oceanographic
conditions both during maternal preconditioning and during egg and larval
stages. During maternal preconditioning (spring-fall, 2019) upwelling
conditions were variable but near average [@HarveyGarfieldEtAl2020]. Weaker
upwelling conditions are associated with higher `r sp` recruitment during this
phase [@VestfalsEtAl2023]. During egg and larval phases (2020),
ocean conditions were broadly associated with high productivity across many
taxa [@HarveyGarfieldEtAl2021]. These conditions were marked by strong winter
upwelling which brings nutrients to coastal waters, cooler temperatures, an
energy-rich copepod community, and high productivity of krill, a key food
source for `r sp` [@BuckleyLivingston1997; @HarveyGarfieldEtAl2021].

Fits to the age-composition data continue to show close correspondence to the
dominant and small cohorts observed in the data when the data give a
consistent signal (Figure~\@ref(fig:main-age-comp-fits-fig)). Because of the
time-varying fishery selectivity, the fit to commercial age-composition data
is particularly good, although models with time-invariant selectivity used in
previous years also fit the age compositions well. In the `r last_data_yr`
fishery, `r top_coh(base_model, last_data_yr, 3, cap = FALSE)`. Age
compositions from the `r survey_end_yr` acoustic survey suggest a similar age
structure for older fish. The 2020 cohort has not yet been observed by the
acoustic survey. Combined, the 2015--`r last_data_yr` fishery age-composition
data and the 2017--`r survey_end_yr` acoustic survey age-composition data
suggest that 2014 was a strong recruitment year, and the model was able to
adequately fit to these observations (Figure~\@ref(fig:main-age-comp-fits-fig)).
The 2016 cohort, which has been observed twice by the survey, still appears
to be smaller than the 2014 cohort. The `r survey_end_yr` survey was the first
to sample the `r survey_end_yr - 2` cohort, confirming that it was not large
(`r survey_a2_prop`% of the `r survey_end_yr` survey catch). The 2020 cohort,
which has been observed twice by the fishery, once by the age-1 index, but
not the acoustic survey is currently expected to be above average in size.
Residual patterns to the fishery and survey age data do not show patterns
that would indicate systematic bias in model predictions
(Figure~\@ref(fig:main-age-comp-pearson-fig)).

The median estimates for numbers, biomass, exploitation rate, and catch (in
numbers and in biomass) for each age class in each year are given in
Tables~\@ref(tab:main-est-numbers-at-age-tab)--
\@ref(tab:main-est-catch-at-age-biomass-tab).
For the major cohorts, the resulting estimated age-specific catch, natural
mortality, and surviving biomasses are given in
Table~\@ref(tab:main-cohort-effects-tab). For example, the catch weight of the
2014 cohort at age-5 was slightly less than that of the 2010 cohort at age-5
and the resulting surviving biomass of the 2014 cohort was approximately half
of the surviving biomass of the 2010 cohort.

Posterior distributions for both steepness and natural mortality are
influenced by priors (Figures~\@ref(fig:main-prior-posterior-fig)--
\@ref(fig:main-prior-posterior-truncated-fig)). The posterior for steepness is
only slightly updated by the data, as expected given the low level of
information available to inform steepness as found in previous hake
assessments. The posterior of natural mortality, on the other hand, is shifted
to the right of the prior distribution and the prior may be constraining the
posterior distribution from shifting further. Broadening the prior
distribution by increasing the prior standard deviation for the natural
mortality parameter is examined in sensitivity runs (see
Section~\@ref(sec:assessment-sensitivity-analyses)). Other parameters showed
updating from diffuse priors to posterior distributions, including
$\theta_{\text{fish}}$ and  $\theta_{\text{surv}}$ (as outlined in
Section~\@ref(sec:data-age-comp-likelihood)).

The `r assess_yr` base model specified the same level of variation (standard
deviation of $\Phi =$ `r sel_phi_val`) associated with time-varying fishery
selectivity as the `r last_assess_yr` base model, effectively allowing the
model flexibility (i.e., a lower penalty on the overall likelihood) to fit to
data that suggests high variability among years for each age. This level of
variation led to results that remained consistent with the `r survey_end_yr`
acoustic survey biomass estimate and gave reasonable fits to the fishery
age-composition data, given that there is considerable uncertainty associated
with spatial changes in fish availability (due to movement) and recent
variability in oceanographic conditions. Estimated selectivity deviations for
age-3 and age-4 fish are larger from 2010 to 2012 than in subsequent years
until 2020 when the deviation for age-4 was large again
(Figures~\@ref(fig:main-tv-selex-fig) and
\@ref(fig:main-tv-selex-uncertainty-fig)). The median selectivity peaks at
age-4 in 2010, 2012 and 2020 and at age-3 in 2011 suggesting targeting (or
generally higher availability) of the younger cohorts in those years. This
pattern is consistent with the 2008 cohort appearing strong in the fishery age compositions initially, but decreasing in
prominence from 2013 onward (Figure~\@ref(fig:main-age-comp-fits-fig)). Fishery
selectivity on age-2 fish was at its highest in 2016. Fishery selectivity for
the most recent year was characteristic by a logistic pattern, where
selectivity generally increased smoothly from age 3 to a peak at age 6 and
older ages (Figure~\@ref(fig:main-tv-selex-uncertainty-fig)). However, age-2
selectivity was slightly higher than for other younger fish, likely as a
result of increased availability of the above-average 2020 cohort. Even
though the survey selectivity is time invariant, the posterior shows a broad
band of uncertainty between ages 2 and 5
(Figure~\@ref(fig:main-tv-selex-uncertainty-fig)). The decline in survey
selectivity between ages 3 and 4 may be an artifact of the interaction between
large cohorts and the biennial timing of recent surveys, with the 2010, 2014,
and 2016 cohorts occurring in the survey at ages 3 and 5 but not age 4.
Fishery selectivity is likewise very uncertain
(Figures~\@ref(fig:main-tv-selex-uncertainty-fig) and
\@ref(fig:main-tv-selex-posteriors-fig)), but in spite of this uncertainty,
changes in year-to-year patterns in the estimates are still evident,
particularly for age-2, age-3, and age-4 fish, though these patterns might
also reflect time-varying mortality processes.

**Stock biomass**

The base stock assessment model indicates that, since the 1960s, `r sp` female
spawning biomass has ranged from well below to above unfished equilibrium
(Figures~\@ref(fig:main-biomass-fig) and
\@ref(fig:main-relative-biomass-fig) and
Tables~\@ref(tab:main-median-posterior-tab) and
\@ref(tab:main-ci-posterior-tab). The model estimates that it was below the
unfished equilibrium in the 1960s, at the start of the assessment period, due
to lower than average recruitment. The stock is estimated to have increased
rapidly and was above unfished equilibrium in the mid-1970s and mid-1980s
(after two large recruitments in the early 1980s). It then declined steadily
to a low in 1999. This was followed by a brief increase to a peak in 2002 as
the very large 1999 year class matured. The 1999 year class largely supported
the fishery for several years due to relatively small recruitments between
2000 and 2007. With the aging 1999 year class, median female spawning biomass
declined throughout the late 2000s, reaching a time-series low of
`r median_bio_min` million~t in `r median_bio_min_yr`. The assessment model
estimates that median female spawning biomass then peaked again in 2013 and
2014 due to a very large 2010 year class and an above-average 2008 year
class. The subsequent decline from 2014 to 2016 is primarily from the 2010
year class surpassing the age at which gains in weight from growth are greater
than the loss in weight from mortality (growth-mortality transition). The
2014 year class is estimated to be large, though not as large as the 1999
and 2010 year classes, resulting in an increased biomass in 2017. The
estimated biomass was relatively steady from 2017 to 2019, and then declined
in 2020 and 2021 due to the 2014 and 2016 year classes moving through the
growth-mortality transition during a period of high catches. The increase in
female spawning biomass since 2021 is due to the expected above average 2020
cohort entering maturity and the recent declining trend in catch.

The median estimate of the `r end_yr` relative spawning biomass (spawning
biomass at the start of `r end_yr` divided by that at unfished equilibrium,
`r b_0`) is `r curr_depl_median`%. However, the uncertainty is large, with a
95% posterior credibility interval from `r curr_depl_lower`% to
`r curr_depl_upper`% (Tables~\@ref(tab:main-median-posterior-tab) and
\@ref(tab:main-ci-posterior-tab), due to remaining unknowns about the size of the
2020 cohort because the acoustic survey only provided one year of age-1
information, which is more uncertain than the 2+ estimate.

The median estimate of the `r end_yr` female spawning biomass is
`r curr_bio_median` million~t (with a 95% posterior credibility interval from
`r curr_bio_lower` to `r curr_bio_upper` million~t). The current estimate of
the `r end_yr - 1` female spawning biomass is `r prev_bio_median`
(`r prev_bio_lower`--`r prev_bio_upper`) million~t. This is a somewhat higher
median and broader credibility interval than the
`r prev_bio_median_last_assess` (`r prev_bio_lower_last_assess`--
`r prev_bio_upper_last_assess`) million~t estimated in the `r end_yr - 1`
assessment, but there is considerable overlap of the credibility intervals.
The increase appears to be due to the addition of 2022 fishery age
composition data, which suggests the 2020 cohort may be larger than the age-1
index alone was indicating in the last assessment (as outlined in
Section~\@ref(sec:assessment-changes)).

**Recruitment**

The new data for this assessment do not significantly change the pattern of
recruitment estimated in recent assessments. However, estimates of absolute
recruitment for the most recent years can change with new data. For example,
this assessment's median estimate of the 2020 recruitment is
`r f(((recruitment_med_to_compare - prev_assess_recruitment_med)["2020"]), 1)`
~billion fish higher than in the last assessment (a
`r f(((((recruitment_med_to_compare - prev_assess_recruitment_med)["2020"]) /
(prev_assess_recruitment_med)["2020"]) * 100), 0)`% increase).
Similarly, estimates for 2019 and 2021 recruitments have changed by
`r f(((((recruitment_med_to_compare - prev_assess_recruitment_med)["2019"]) /
(prev_assess_recruitment_med)["2019"]) * 100), 0)`%
(`r f((recruitment_med_to_compare - prev_assess_recruitment_med)["2019"], 1)`
~billion fish) and
`r f(((((recruitment_med_to_compare - prev_assess_recruitment_med)["2021"]) /
(prev_assess_recruitment_med)["2021"]) * 100), 0)`%
(`r f(((recruitment_med_to_compare - prev_assess_recruitment_med)["2021"]), 1)`
~billion fish), respectively, but the general notion remains that recent
recruitment is highly uncertain.

`r sp` have low average recruitment with occasional large year classes
(Figures~\@ref(fig:main-recruitment-fig) and
\@ref(fig:main-recruitment-devs-fig),
Tables~\@ref(tab:main-median-posterior-tab) and
\@ref(tab:main-ci-posterior-tab)). Very large year classes in 1980, 1984,
and 1999 supported much of the commercial catch from the 1980s to the
mid-2000s. From 2000 to 2007, estimated recruitment was at some of the
lowest values in the time series, but this was followed by an above average
2008 year class and a very strong 2010 year class. Above average year classes
occurred in 2014 and 2016, which have been sustaining the fishery until
through the end of the last decade, with a probable very large 2020 year class
entering the fishery currently.

The current assessment estimates a strong 2014 year class
(Figure~\@ref(fig:main-numbers-at-age-fig)) comprising
`r top_coh(base_model, 2016, ret_cohort = 2014)`% of the 2016 catch,
`r top_coh(base_model, 2017, ret_cohort = 2014)`% of the 2017 catch,
`r top_coh(base_model, 2018, ret_cohort = 2014)`% of the 2018 catch,
`r top_coh(base_model, 2019, ret_cohort = 2014)`% of the 2019 catch,
`r top_coh(base_model, 2020, ret_cohort = 2014)`% of the 2020 catch
`r top_coh(base_model, 2021, ret_cohort = 2014)`% of the 2021 catch, and
`r top_coh(base_model, 2022, ret_cohort = 2014)`% of the 2022 catch.
The 2016 cohort also appears to be above average, comprising
`r top_coh(base_model, 2018, ret_cohort = 2016)`% of the 2018 catch,
`r top_coh(base_model, 2019, ret_cohort = 2016)`% of the 2019 catch,
`r top_coh(base_model, 2020, ret_cohort = 2016)`% of the 2020 catch, and
`r top_coh(base_model, 2021, ret_cohort = 2016)`% of the 2021 catch, and
`r top_coh(base_model, 2022, ret_cohort = 2016)`% of the 2022 catch.
The absolute size of the 2014 year class has now stabilized after observations
across eight years of fishery observations and three acoustic surveys. The
2016 year class is estimated to be above average (similar in size to the 2008
year class) from six years of fishery data and two years of survey data.
Since 2020, the model currently estimates small 2011, 2013, 2015, 2018, 2019,
and 2021 year classes (median recruitment well below the mean of all median
recruitments) and near average 2012 and 2017 year class. With the addition of
the age-1 index, there is information beyond just fishery encounters in the
data to estimate the size of the 2020 year class. Collectively, these data
indicate that the 2020 year class is likely well above average. The much
smaller 2019 year class is informed by the `r last_survey_yr` biomass index
and fishery data, but has no age-1 index, and the 2021 year class is only
informed by fishery data. There is no information in the data to estimate the
sizes of the `r end_yr-1` and `r end_yr` year classes. Retrospective analyses
of year class strength for young fish have shown the estimates of recent
recruitment to be unreliable prior to at least model age-3 (observed at age-2)
without a survey in the most recent year and age-2 (observed at age-1) with a
survey. While the 2020 cohort was observed by the age-1 index in 2021, it
will not be observed by the acoustic survey until 2023.

From Figure~\@ref(fig:main-recruitment-fig) it looks as though the 2014
recruitment could be as large as the 2010 recruitment. However, the assessment
model estimates a `r prob_percent_2014_rec_gt_2010_rec`% chance that this
could be the case. The overlapping of the credible intervals in
Figure~\@ref(fig:main-recruitment-fig) is because large MCMC estimates of 2010
recruitment are associated with large estimates of 2014 recruitment
(presumably with large estimates of `r r_0`). The 2020 cohort is still very
uncertain but has a `r prob_percent_2020_rec_gt_2010_rec`% chance of
exceeding the 2010 cohort, while the 2021 cohort is definitely smaller
than the 2010 cohort.

The estimated recruitments with uncertainty for each year and the overall
stock recruit relationship are provided in
Figure~\@ref(fig:main-stock-recruitment-fig). Extremely large variability
about the expectation and about the joint uncertainty of individual
recruitment and female spawning biomass pairs are evident. High and low
recruitments have been produced throughout the range of observed female
spawning biomass (Figure~\@ref(fig:main-stock-recruitment-fig)). The
standard deviation of the time series of median recruitment deviation
estimates for the years 1970--`r last_data_yr - 1`, which are informed by
the age compositions and the age-1 index, is `r sd_med_recr_dev_estimates`.

**Exploitation status**

The median estimated relative fishing intensity on the stock is below
`r f_40` for all years (Figure~\@ref(fig:main-fishing-intensity-fig) and
Tables~\@ref(tab:main-median-posterior-tab) and
\@ref(tab:main-ci-posterior-tab)). It was close to `r f_40` in 2008 and 2010,
but harvest in those years did not exceed the catch limits that were specified,
based on the best available science and harvest control rules in place at the
time. Exploitation fraction (catch divided by biomass of fish of age-2 and
above) has shown relatively similar patterns
(Figure~\@ref(fig:main-exploitation-fraction-fig) and
Tables~\@ref(tab:main-median-posterior-tab) and
\@ref(tab:main-ci-posterior-tab)). Although displaying similar patterns, the exploitation fraction does not necessarily correspond to fishing intensity
because fishing intensity more directly accounts for the age-structure of
both the population and the catch. Median relative fishing intensity is
estimated to have declined from `r median_intensity_2010`% in 2010 to
`r median_intensity_2015`% in 2015, and then it leveled off around 70% from
2016 to 2019 before declining to `r median_intensity_2022`% in 2022. The
median exploitation fraction has increased from a recent low of
`r exploitation_med_2012` in 2012 to `r exploitation_med_2017` in 2017 where
it remained relatively stable before dropping back to 2012--2015 levels in
2022. Although there is a considerable amount of imprecision around these
recent estimates due to uncertainty in recruitment and spawning biomass,
the 95% posterior credibility interval of relative fishing intensity was
below `r f_40` from 2012 through 2016 and again from 2019 to 2022 (Figure~\@ref(fig:main-fishing-intensity-fig)). The median estimate for 2017
and 2018 is below `r f_40` though the 95% posterior credibility interval
does include `r f_40`.

**Management performance**

Over the last decade (`r end_yr - 10`--`r end_yr - 1`), the mean coast-wide
utilization rate (i.e., proportion of catch target removed) has been
`r tot_last_10_yrs_attainment`% and catches have been below coast-wide
targets (Table~\@ref(tab:main-landings-tac-tab)). From `r end_yr - 5` to
`r end_yr - 1`, the mean utilization rates differed between the United States
(`r us_last_5_yrs_attainment`%) and Canada (`r can_last_5_yrs_attainment`%).
In 2015, the utilization rate for the coast-wide fishery was the lowest of
the previous decade (`r tot_2015_attainment`%) due, in part, to difficulties
locating aggregations of fish and possibly economic reasons. Before 2015,
the under-utilization in the United States was mostly a result of unrealized
catch in the tribal apportionment, while reports from stakeholders in Canada
suggested that hake were less aggregated in Canada and availability had
declined. In 2016, the utilization rate increased but remained below pre-2015
levels, despite the total 2016 catch being one of the highest of the preceding
years. This is in large part due to increasing catch targets as biomass
continues to increase. While the total utilization rate between 2017--2021 was
relatively steady and close to the average over the last decade
(`r tot_last_10_yrs_attainment`%), it decreased in 2022 to
`r tot_last_yr_attainment`%. This is primarily due to the utilization rate in
Canada declining since 2020 to a time-series low of 20.3% in 2022.
Country-specific quotas (or catch targets) in 2020 and 2021 were specified
unilaterally, due to the lack of an agreement on coast-wide 2020 and 2021
TACs. The usual `r us_allotment_percent`% and `r can_allotment_percent`%
allocation of coast-wide TAC, as specified in the Joint U.S.-Canada
Agreement for `r sp`, was once again implemented in 2022.
Total landings last exceeded the coast-wide quota in 2002 when utilization
was 112%.

As noted above, the median relative fishing intensity was below `r f_40`
in all years. The median relative spawning biomass was above the `r b_40`
reference point in all years except 2007--2010
(Table~\@ref(tab:main-median-posterior-tab) and
Figure~\@ref(fig:main-relative-biomass-fig)).
These are also shown on a phase plot of the joint history of relative
spawning biomass and relative fishing intensity
(Figure~\@ref(fig:main-phase-fig)). Relative spawning biomass increased from
the lows in 2007--2010 with above average recruitment in 2008, 2010, 2014,
2016, 2017, and 2020. Correspondingly, relative fishing intensity has
remained well below `r f_40`, and total catch has been declining since the
time series high in 2017. While there is large uncertainty in the `r end_yr-1`
estimates of relative fishing intensity and relative spawning biomass,
the model estimates a `r joint_percent_prob_above_below`% joint probability
of being both above the `r f_40` relative fishing intensity in `r end_yr - 1`
and below the `r b_40` relative spawning biomass level at the start of
`r end_yr`.

## Model uncertainty {#sec:assessment-model-uncertainty}

The base assessment model integrates over the substantial uncertainty
associated with several important model parameters including: biomass
index and age-1 index catchabilities (q~b~ and q~1~, respectively), the
magnitude of the stock (via the `r r_0` parameter for equilibrium recruitment),
productivity of the stock (via the steepness parameter, h, of the
stock-recruitment relationship), the rate of natural mortality (M), annual
selectivity for key ages, recruitment deviations, and survey and fishery data
weights (via the Dirichlet-multinomial parameters
$\theta_{\text{fish}}$ and $\theta_{\text{surv}}$).

The medians of the key parameters from the posterior distribution are
similar to those in last year's base model
(Table~\@ref(tab:main-parameter-estimates-tab)). The largest change was a
doubling of the 2020 cohort size. Medians of some of the derived quantities
also change somewhat; in particular, recruitment in 2019 and 2015 decreased
(39% and 11%, respectively) from those estimated in the `r assess_yr - 1`
assessment.

The `r sp` stock displays a very high degree of recruitment variability,
perhaps the largest of any west coast groundfish stock, resulting in large and
rapid biomass changes. This volatility, coupled with a dynamic fishery that
potentially targets strong cohorts (resulting in time-varying selectivity)
will in most circumstances continue to result in highly uncertain
estimates of current stock status and even less-certain projections of the
stock trajectory. This is particularly true for female spawning biomass
estimates in `r assess_yr` and throughout the current forecast period, because
there is considerable uncertainty associated with the size of the 2020 year
class, now mostly mature, that propagates into forecasts. Further
observations of this year class, including during the 2023 acoustic survey,
will help to refine these estimates and reduce uncertainty. The addition of
the age-1 index in this assessment will, in some cases, help to reduce this
uncertainty (as it currently does in this case; see
Figure~\@ref(fig:main-recruitment-base-alternative-2-fig) discussed later).
However, further work is needed to improve upon the characterization of
uncertainty in the age-1 index itself, which is based on a time invariant
assumption about index observation error and catchability.

Uncertainty measures in the base model underestimate the total uncertainty in
the current stock status and projections, because they do not account for
alternative structural models for hake population dynamics and fishery
processes (e.g., recruitment, selectivity, or spatial fleet or population
structure), the effects of alternative data-weighting choices, survey
catchability, and the scientific basis for prior probability distributions. To
address structural uncertainties, the JTC investigated a range of alternative
models, and we present the key sensitivity analyses along with other
informative sensitivity analyses using full MCMC results
(Section~\@ref(sec:assessment-sensitivity-analyses)).

The JTC continues to be committed to advancing MSE analyses, by coordinating
research with the `r sp` MSE Working Group and other scientists in the region
engaged in similar research. Incorporating feedback from the
Working Group and stakeholders will ensure that operating models will be able
to provide insight into the important questions defined by interested parties.
Specifically, the development of MSE tools will evaluate major sources of
uncertainty relating to data, model structure and the harvest policy for this
fishery, and will compare potential methods to address them. In the coming
years, this will include a host of research evaluations (see
Section~\@ref(sec:assessment-response-review) and
Section~\@ref(sec:research)), including evaluating the utility of
incorporating environmentally-driven age-0 recruitment indices into the stock
assessment.

## Reference points {#sec:assessment-reference-points}

The term 'reference points' is used throughout this document to describe
common conceptual summary metrics. The Agreement specifically identifies
`r f_40` as the default harvest rate and `r b_40` as a point where the
40:10 TAC adjustment is triggered (see the Glossary in
Appendix~\@ref(sec:app-glossary)).

We report estimates of the base reference points (e.g., `r f_40`, `r b_40`,
`r b_msy`, and MSY) with posterior credibility intervals in
Table~\@ref(tab:main-reference-points-tab). The median of the female spawning
biomass at `r f_40` (namely the median of `r bspr_40`) and the median yield
at `r f_40` have remained about the same as estimates in the
`r last_assess_yr` assessment (Table~\@ref(tab:main-parameter-estimates-tab)).

As part of the DFO Sustainable Fisheries Framework, @DFO2009 defined a limit
reference point as being a biomass below which serious harm is believed to be
occurring to the stock, and an upper stock reference point above which the
stock is considered to be healthy. These would equate to the Agreement
reference points of `r b_10` and `r b_40` (the female spawning biomass being
10% and 40%, respectively, of the unfished equilibrium female spawning
biomass). The probabilities of the female spawning biomass at the start of
`r assess_yr` being above each of these points are
P(*B*~`r assess_yr`~ > `r b_10`) = `r probs_curr_b10`% and
P(*B*~`r assess_yr`~ > `r b_40`) = `r probs_curr_b40`%
such that the stock is estimated to be in the 'healthy zone' (above the upper
stock reference point of `r b_40`). This probability was higher than in last
year's assessment, where the equivalent calculation was
P(*B*~`r assess_yr - 1`~ > `r b_40`) = 90.5%. Note that a probability
of '100%' (or '0%') is based on the MCMC results, and is not meant to imply
that something definitely occurs (or definitely does not occur).

With respect to DFO's provisional limit reference point of 0.4`r b_msy` and
provisional upper stock reference point of 0.8`r b_msy`, the probabilities are
P(*B*~`r assess_yr`~ > 0.4`r b_msy`) = `r f(dfo_probs_curr[1, 2] |> pull(), 0)`%
and
P(*B*~`r assess_yr`~ > 0.8`r b_msy`) = `r f(dfo_probs_curr[1, 3] |> pull(), 1)`%
such that the stock is estimated to be in the provisional `healthy zone'.
For completeness, we note that
P(*B*~`r assess_yr`~ > `r b_msy`) = `r f(dfo_probs_curr[1, 1] |> pull(), 1)`%.

Reference levels of stock status that are used by the U.S. Pacific Fisheries
Management Council (PFMC) for `r sp` include `r b_40` and a Minimum Stock
Size Threshold (MSST) of `r b_25`. For `r min(forecast_yrs)`, the
estimated posterior median relative spawning biomass is
`r curr_depl_median`%, such that the female spawning biomass is well above
`r b_40` and `r b_25`. The probability that female spawning biomass
at the beginning of `r assess_yr` is above `r b_40` is
     = `r probs_curr_b40`% (as noted
above), and of being above `r b_25` is
P(*B*~`r assess_yr`~ > `r b_25`) = `r probs_curr_b25`%.

## Model projections {#sec:assessment-model-projections}

The catch limit for `r min(forecast_yrs)` based on the default `r f_40`ten
harvest policy has a median of `r ct_limit_quantiles["median"]`~t and a wide
range of uncertainty (Figure~\@ref(fig:main-projected-catch-density-fig)),
with the 95% credibility interval being `r ct_limit_quantiles["lower"]`--
`r ct_limit_quantiles["upper"]`~t.

Decision tables give projected population status (relative spawning biomass)
and relative fishing intensity under different catch alternatives for the base
model
(Tables~\@ref(tab:main-decisions-biomass-tab) and
\@ref(tab:main-decisions-spr-tab)). The tables are organized such that the
projected outcome for each potential catch level and year (each row) can be
evaluated across the quantiles (columns) of the posterior distribution. The
tables use the new format demonstrated by @JTC2021 arising from discussions
at the 2021 SRG meeting. Table~\@ref(tab:main-decisions-biomass-tab) shows
projected relative spawning biomass outcomes, and
Table~\@ref(tab:main-decisions-spr-tab) shows projected fishing intensity
outcomes relative to `r f_40` (based on SPR; see table legend).

Population dynamics and governing parameters assumed during the forecast
period include random recruitment; selectivity, weight-at-age and fecundity
averaged over the five most recent years (`r assess_yr - 5`--
`r assess_yr - 1`); and all estimated parameters constant (at their
estimates for each particular MCMC sample).

Relative fishing intensity exceeding 1 (or 100% when shown as a percentage)
indicates fishing in excess of the `r f_40` default harvest rate limit.
This can happen for the median relative fishing intensity in
`r forecast_yrs[1:(length(forecast_yrs) - 2)]` and
`r forecast_yrs[(length(forecast_yrs) - 1)]` because the `r f_40` default
harvest-rate catch limit is calculated using baseline selectivity-at-age
(1966--1990; prior to time-varying deviations), whereas the forecasted
catches under the default harvest-rate are removed using selectivity averaged
over the last five years. Recent changes in selectivity could be reflected
in the projection of over- or under-fishing relative to the desired `r f_40`
rate.

Key management metrics are presented for
`r forecast_yrs[2:(length(forecast_yrs) - 1)]` and
`r forecast_yrs[length(forecast_yrs)]`
projections (Tables~\@ref(tab:main-risk-year-1-tab)--
\@ref(tab:main-risk-year-3-tab) and
Figures~\@ref(fig:main-risk-year-1-fig)--
\@ref(fig:main-risk-year-3-fig)). These metrics summarize
the probability of various outcomes from the base model given each potential
management action. Although not linear, probabilities can be interpolated
from this table for intermediate catch values in `r assess_yr`
(Table~\@ref(tab:main-risk-year-1-tab) and
Figure~\@ref(fig:main-risk-year-1-fig)). However,
interpolation may not be applicable for all catches in `r assess_yr + 1` and
`r assess_yr + 2` because they are conditional on previous year(s) catch
levels. This explains why a few probabilities decline (rather than rise) with
increased `r assess_yr + 1` and `r assess_yr + 2` catch levels in
Tables~\@ref(tab:main-risk-year-2-tab) and~\@ref(tab:main-risk-year-3-tab) and
Figures~\@ref(fig:main-risk-year-2-fig)
and \@ref(fig:main-risk-year-3-fig).

Figure~\@ref(fig:main-depletion-comparison-fig) shows the projected
relative spawning biomass trajectory through
`r forecast_yrs[length(forecast_yrs)]` for several of these management
actions. With zero catch for the next three years, the biomass has a
`r zero_catch_prob_bio_down_1`% probability of decreasing from
`r forecast_yrs[1]` to `r forecast_yrs[2]`
(Table~\@ref(tab:main-risk-year-1-tab) and
Figure~\@ref(fig:main-risk-year-1-fig)), a
`r zero_catch_prob_bio_down_2`% probability of decreasing from
`r forecast_yrs[2]` to `r forecast_yrs[3]`
(Table~\@ref(tab:main-risk-year-2-tab) and
Figure~\@ref(fig:main-risk-year-2-fig)), and a
`r zero_catch_prob_bio_down_3`% probability of decreasing from
`r forecast_yrs[3]` to `r forecast_yrs[4]`
(Table~\@ref(tab:main-risk-year-3-tab)
and Figure~\@ref(fig:main-risk-year-3-fig)).

The probability of the female spawning biomass decreasing from `r end_yr` to
`r end_yr + 1` is above 72% for all non-zero catch levels examined
(Table~\@ref(tab:main-risk-year-1-tab) and
Figure~\@ref(fig:main-risk-year-1-fig)). It is 81% for the
`r end_yr` catch level similar to that for `r end_yr - 1`
(catch alternative~f). For all explored catches, the maximum probability of
the female spawning biomass dropping below `r b_10` at the start of
`r end_yr + 1` is near 0%, at the start of `r end_yr + 2` is 1%, and at the
start of `r end_yr + 3` is 4% (Tables~\@ref(tab:main-risk-year-1-tab)--
\@ref(tab:main-risk-year-3-tab) and
Figures~\@ref(fig:main-risk-year-1-fig)--
\@ref(fig:main-risk-year-3-fig)). The similar maximum
probability of dropping below `r b_40` at the start of `r end_yr + 1` is 10%,
at the start of `r end_yr + 2` is 24%, and at the start of `r end_yr + 3`
is 35%. As the large 2010, 2014, and 2016 cohorts continue to age, their
biomass is expected to decrease as losses from mortality continue to outweigh
increases from growth. The estimated above-average 2020 cohort has already
begun to play a large role in determining female spawning biomass during the
forecast years presented here.

It should be noted that forecasted biomass is not only influenced by catch
levels. As the large 2010 and 2014 cohorts continue to age, their biomass
will continue to decrease (Tables~\@ref(tab:main-est-biomass-at-age-tab) and
\@ref(tab:main-cohort-effects-tab)) as losses from mortality outweigh increases
from growth. The smaller above-average 2016 cohort entered this
growth-mortality transition period around 2019
(Tables~\@ref(tab:main-est-biomass-at-age-tab) and
\@ref(tab:main-cohort-effects-tab)). The below-average 2015 and 2018 cohorts
will contribute much less to forecasted spawning biomass than the larger
cohorts. During 2023, the age-3 2020 cohort will likely move through the
growth-mortality transition and thus no longer contribute to an increase
in total biomass (note that fecundity will increase which will influence
the exact change in female spawning biomass,
Figure~\@ref(fig:main-maturity-ogive-fig)).

The age composition (in numbers) of the catch in `r forecast_yrs[1]` is
projected to be (using MCMC medians)
`r fore_catch_prop[["3"]]`% age-3 fish from the `r forecast_yrs[1] - 3` cohort,
`r fore_catch_prop[["7"]]`% age-7 fish from the `r forecast_yrs[1] - 7` cohort,
`r fore_catch_prop[["6"]]`% age-6 fish from the `r forecast_yrs[1] - 6` cohort,
`r fore_catch_prop[["9"]]`% age-9 fish from the `r forecast_yrs[1] - 9` cohort,
and only
`r fore_catch_prop[["13"]]`% age-13 fish from the large `r forecast_yrs[1] - 13`
cohort (Figure~\@ref(fig:main-age-comp-forecast-fig)). However, those estimates
are highly uncertain with the 95% credibility interval for the age-3 fraction
spanning `r f(fore_catch_prop_age3_lower)`%--
`r f(fore_catch_prop_age3_upper)`%.

Due to the higher average weight of older fish compared to younger fish, the
median expected proportion of the `r forecast_yrs[1]` catch by weight
is `r f(fore_catch_prop_wt_age3_median)`% for the age-3
`r forecast_yrs[1] - 3` cohort (compared to `r fore_catch_prop[["3"]]`% by
numbers) and `r f(fore_catch_prop_wt_age7_median)`%
for the age-7 `r forecast_yrs[1] - 7` cohort
(compared to `r fore_catch_prop[["7"]]`% by numbers;
Figure~\@ref(fig:main-age-comp-forecast-fig)).

With respect to the DFO reference points, with the largest
`r assess_yr` catch of `r largest_next_catch`~t given in
Table~\@ref(tab:main-risk-year-1-tab), at the start of `r assess_yr + 1` the
stock is expected to be above the critical zone with a probability of
P(*B*~`r assess_yr + 1`~ > `r b_10`) = `r prob_next_over_b10`%
and in the healthy zone with a probability of
P(*B*~`r assess_yr + 1`~ > `r b_40`) = `r prob_next_over_b40`%.
With respect to the DFO provisional reference points (based on `r b_msy`), the
stock is expected to be above the provisional critical zone with a probability
of
P(*B*~`r assess_yr + 1`~ > 0.4`r b_msy`) = `r dfo_prob_next_over_40bmsy`%,
in the healthy zone with a probability of
P(*B*~`r assess_yr + 1`~ > 0.8`r b_msy`) = `r dfo_prob_next_over_80bmsy`%,
and above `r b_msy` with a probability of
P(*B*~`r assess_yr + 1`~ > `r b_msy`) = `r dfo_prob_next_over_bmsy`% for
this catch.

With respect to PFMC stock size reference points, a level of `r assess_yr`
catch consistent with the Agreement default harvest control rule
(`r next_treaty_catch`~t) has a `r pfmc_prob_next_yr_below_b40`% estimated
probability of resulting in the biomass going below `r b_40` at the start of
`r assess_yr + 1` (and `r pfmc_prob_next_yr_below_b25`% probability of going
below `r b_25`; Table~\@ref(tab:main-risk-year-1-tab)).
If catches in `r assess_yr` and `r assess_yr + 1` are the same as in
`r assess_yr - 1` (`r same_catch_as_last_yr`~t,
catch scenario~`r letters[ct_actual_ind]`)
then the probability of the biomass going below `r b_40` is
`r same_catch_prob_next_year_below_b40`% for the start of
`r assess_yr + 1` and
`r same_catch_prob_yr_after_next_below_b40`% for the start of
`r assess_yr + 2`.

## Sensitivity analyses {#sec:assessment-sensitivity-analyses}

Sensitivity analyses were conducted to investigate influence of data inputs
and structural uncertainty of the base model by investigating how changes to
the model affected the estimated values and derived quantities. All
sensitivity analyses compared MCMC posteriors that were created using the
\texttt{adnuts} R package [@Monnahan2018; @Monnahan2019] to implement the NUTS
algorithm with a similar number of posterior samples as the base model.
Several key underlying structural model assumptions were identified that have
persisted across many previous hake assessments, and thus warrant revisiting
annually as a set of reference sensitivity examinations to new base models.
Many additional sensitivity runs were conducted when developing and testing the
`r assess_yr` base model. Here we focus on the main sensitivities which,
relative to the base model, are:

1. Consideration of higher standard deviations on the prior distribution for
natural mortality;

1. Consideration of an alternative prior distribution (mean and standard
deviation) for natural mortality based on the @Hamel2015 and @HamelCope2022
life history meta-analytic method;

1. Consideration of an alternative prior distribution and a fixed value for
steepness, to change the resiliency of the stock;

1. Assumption of higher and lower variation about the stock-recruitment curve
($\sigma_r$);

1. Removal of the age-1 index as a data source;

1. Downweighting the fishery age-composition data; and

1. Consideration of alternative standard deviations for time-varying
selectivity.

Comparisons of the parameter estimates between the main sensitivity models
with those from the base model are shown in
Tables~\@ref(tab:main-parameter-estimates-sens-1-tab)--
\@ref(tab:main-parameter-estimates-sens-2-tab). None of the sensitivities
resulted in any substantial departure from the main population dynamics of
the base model. All sensitivity models showed large estimated increases in
female spawning biomass in the early- to mid-2010s that continues to be
driven by the 2010, 2014, and 2016 cohorts, followed by several years of
steady decline (2019--2021) before increasing again due to the strong 2020
cohort. All sensitivity models indicate that `r assess_yr` relative spawning
biomass is above `r b_40`. The overall scale of the population was impacted
by various alternative assumptions, and the highly uncertain size of the
recent cohorts were more variable across sensitivity analyses than earlier
cohorts which have been observed for more years.

Figures~\@ref(fig:main-biomass-base-alternative-2-fig) and
\@ref(fig:main-recruitment-base-alternative-2-fig). In general, the estimated
population dynamics are similar, regardless of extrapolation, throughout most
of the time series. However, there is some divergence in recent year
estimates; e.g., the estimated relative spawning biomass in `r end_yr` is
`r sens_base_bratio`% for the base model (with extrapolation) and
`r sens_grp2_2_bratio`% for the model without extrapolation. The 2016
default harvest control catch limit coming from the base model is
`r sens_base_forecatch`~t compared to `r sens_grp2_2_forecatch`~t
for the model using no extrapolation (using MLE values).

The standard deviation of the prior distribution on natural mortality was
increased from the base model value of 0.1 to 0.2 and 0.3. The median of the
MCMC posteriors for natural mortality increased from
`r f(nat_m[2], 3)` with a 95% credible interval of `r f(nat_m[1], 3)`--
`r f(nat_m[3], 3)` for the base model (prior standard deviation of 0.1) to
`r f_nat_m_03[2]` with a 95% credible interval of
`r f_nat_m_03[1]`--`r f_nat_m_03[3]` for the sensitivity run with the
prior standard deviation set to 0.3
(Table~\@ref(tab:main-parameter-estimates-sens-1-tab)). The @HamelCope2022
prior model estimated natural mortality at `r f_nat_m_hamel[2]` with
a 95% credible interval of `r f_nat_m_hamel[1]`--`r f_nat_m_hamel[3]`
(Table~\@ref(tab:main-parameter-estimates-sens-1-tab)). In addition to
allowing a higher estimated value for natural mortality, these M
sensitivity models increased the overall scale of the population, the
estimated stock status relative to `r b_0` prior to 1990, the uncertainty in
female spawning biomass on both absolute and relative scales, halved
estimated relative fishing intensity in `r end_yr - 1`, and doubled
equilibrium yield at `r bspr_40`
(Table~\@ref(tab:main-parameter-estimates-sens-1-tab) and
Figures~\@ref(fig:main-biomass-base-alternative-1-fig) and
\@ref(fig:main-status-base-alternative-1-fig)).

The mean of the prior distribution on steepness was decreased from 0.777
(base) to 0.5 and, separately, steepness was fixed at 1.0. The decrease in
the mean of the prior resulted in a decrease in the MCMC estimate of steepness
from a median of `r f(steep[2], 3)` with a 95% credible interval of
`r f(steep[1], 3)`--`r f(steep[3], 3)` to a median of
`r f_steep_prior_05[2]` with a 95% credible interval of
`r f_steep_prior_05[1]`--`r f_steep_prior_05[3]`
(Table~\@ref(tab:main-parameter-estimates-sens-1-tab)). However, neither
steepness sensitivity analysis had a large impact on the overall model
results (Figures~\@ref(fig:main-biomass-base-alternative-1-fig) and
\@ref(fig:main-status-base-alternative-1-fig)), because `r sp` female spawning
biomass has remained above levels where changes in steepness would appreciably
influence stock-recruit dynamics
(Figure~\@ref(fig:main-stock-recruitment-fig)).

The value of $\sigma_r$ was changed from a value of `r sigma_r` (base) to
alternative high (`r sigma_r_sens[2]`) and low (`r sigma_r_sens[1]`) states.
Both sensitivities were similar to the base model in that the calculated
standard deviation of recruitment deviations (from the main period) was
higher than the input $\sigma_r$, i.e., `r sigma_r_lo_main` and
`r sigma_r_hi_main` when $\sigma_r$ was `r sigma_r_sens[1]` and
`r sigma_r_sens[2]`, respectively. Where, in theory the calculated standard
deviation should match the input value used for $\sigma_r$. However, the high
$\sigma_r$ model had a larger difference between the female spawning biomass
at unfished equilibrium and the female spawning biomass at the initial year of
the model than the low $\sigma_r$ model
(Figure~\@ref(fig:main-status-base-alternative-1-fig)). Similar to previous
assessments, estimates of unfished equilibrium recruitment and relative
spawning biomass are sensitive to $\sigma_r$, whereas absolute estimates of
female spawning biomass are relatively insensitive. The method
@MethotTaylor2011 proposed to tune $\sigma_r$ was developed in the context of
maximum likelihood estimation and not Bayesian inference, where the latter
potentially allows for estimating $\sigma_r$ using random effects, and thus,
this proposed method is not used here to tune the fixed input value.

The sensitivity of the base model to the removal of the age-1 index provides
a comparative evaluation of how the base model incorporates information
about juvenile fish. Compared to the base model, estimates of female spawning
biomass throughout most of the time series are similar, but do diverge near
the end of the time series
(Table~\@ref(tab:main-parameter-estimates-sens-1-tab),
Figures~\@ref(fig:main-biomass-base-alternative-2-fig) and
\@ref(fig:main-status-base-alternative-2-fig)). The `r end_yr` estimates of
relative spawning biomass are `r f(100 * bratio_curr[2], 1)`% for the base model
(95% credible interval of `r f(100 * bratio_curr[1], 1)`--
`r f(100 * bratio_curr[3], 1)`%) and `r f(100 * bratio_age1[2], 1)`%
for the removal of the age-1 index model (95% credible interval of
`r f(100 * bratio_age1[1], 1)`--`r f(100 * bratio_age1[3], 1)`%). This
difference is due to the age-1 index providing additional information on
recruitment for cohorts associated with recent age-1 indices (i.e., 2018 and
2020 cohorts detected in the 2019 and 2021 age-1 indices). In particular, the
base model with the age-1 index suggests that the 2020 year class is estimated to
be large, but not as large as the 2021 and 2022 fishery data alone (i.e.,
removing the age-1 index) would otherwise suggest
(Figure~\@ref(fig:main-biomass-base-alternative-2-fig)). Removing the age-1
index led to minor changes in fit to the age-2+ survey biomass index, with
2019 showing a slight improvement and 2021 a deterioration compared to the
base model (Figure~\@ref(fig:main-index-base-alternative-2-fig)).

The base model includes a Dirichlet-multinomial likelihood component, which
uses two estimated parameters to automatically weight each of the fishery and
survey age compositions. The base model was compared to a sensitivity model
that downweighted the fishery age compositions relative to the survey age
compositions. The data weighting used in the sensitivity model was based on
the McAllister-Ianelli method. This method requires manual iterative
adjustments to the input sample sizes using a derived multiplier. The
McAllister-Ianelli method, which was used in assessments prior to 2018
(Table~\@ref(tab:main-assessment-changes-tab)), attempts to make the
arithmetic mean of the input sample size approximately equal to the harmonic
mean of the effective sample size. The McAllister-Ianelli method suggested
a weighting factor of 0.14 and 0.46 (ratio of 0.30) for fishery and survey
age compositions, respectively. The median estimate from Dirichlet-multinomial
method used in the base model was `r dm_weight_fishery_median` and
`r dm_weight_survey_median` (ratio of
`r f(as.numeric(dm_weight_fishery_median) / as.numeric(dm_weight_survey_median), 2)`).
Downweighting fishery composition data using the McAllister-Ianelli method
led to minor changes in relative spawning biomass, recruitment estimates, and
increased uncertainty in estimates of early recruitments compared to the base
model (Figures~\@ref(fig:main-status-base-alternative-2-fig) and
\@ref(fig:main-recruitment-base-alternative-2-fig)).

The degree of flexibility of annual variation in the fishery selectivity was
tested using three sensitivities which set alternative values of the $\Phi$
parameter (Figures~\@ref(fig:main-biomass-base-alternative-4-fig)--
\@ref(fig:main-index-base-alternative-4-fig)). The consideration of alternative
standard deviations ($\Phi$) for time-varying selectivity is discussed earlier
in Section~\@ref(sec:data-variability-selectivity). Changing the values of the
parameter $\Phi$ controlling the flexibility in time-varying selectivity from
the base model value of $\Phi = 1.40$ to alternative values of 0.21, 0.70,
and 2.10, did not appreciably influence the estimates, or precision,
associated with recruitment in 2014, but it did impact more recent
recruitments (Figure~\@ref(fig:main-recruitment-base-alternative-4-fig)). In
particular, recruitment estimates for 2016 and 2020 are linked to the choice
of $\Phi$, where the model with the smallest $\Phi$ (0.21) estimates the 2016
and 2020 recruitment deviation as the highest of the $\Phi$ sensitivity
models (Figure~\@ref(fig:main-recruitment-devs-base-alternative-4-fig)),
leading to a large increase in female spawning biomass in recent years
compared to the base model
(Figure~\@ref(fig:main-biomass-base-alternative-4-fig)).
The value $\Phi = 0.21$ also provides the worst fit to the most recent age-2+
survey biomass index (Figure~\@ref(fig:main-index-base-alternative-4-fig)).

## Retrospective analyses {#sec:assessment-retrospective-analyses}

Retrospective analyses were performed by iteratively removing the terminal
years' data (going back 10 years) and estimating the posterior distribution of
parameters under the assumptions of the base model. This year's base model
shows similar retrospective results to last year's
(Figure~\@ref(fig:main-retrospective-recruitment-fig), @JTC2022).
The addition of the age-1 index in last year's base model found estimates
of recruitment strength to come closer to the long-term stable estimate by
age-2 in some cases compared to the model without the age-1 index [@JTC2022].
However, some cohort recruitments are still over or under-estimated at age-2.
Over-estimation can be seen most clearly with the 2014, 2015, 2017, and 2018
cohorts (Figures~\@ref(fig:main-retrospective-recruitment-fig) and
\@ref(fig:main-relative-retrospective-recruitment-fig)). The 2014 cohort reached
a high deviation after two years, then even higher after three years only to
drop back down to a lower value and then stabilize at around age-4 with the
addition of more data. A similar pattern can be seen with the smaller 2017 and
2018 cohorts. Even with the addition of new data, the size of the very small
2015 cohort has not fully stabilized. Under-estimation is slight, but
apparent, for the 2016 cohort as recruitment estimates have risen since the
estimate at age-3. Cohort strength is further informed once at least one year
of age-2+ survey biomass index age-composition data are available for a
cohort, which for even-numbered recruitment years typically does not occur
until the cohort reaches age-3, due to the acoustic survey occurring in odd
years; though the age-1 index does provide some information.

The stability of the recruitment estimates seen in this plot is also evident
in the uncertainty estimates of each cohort. Uncertainty of the 2016--2019
cohorts has been substantially reduced compared to removing five years of
data (Figure~\@ref(fig:main-biomass-recruitment-retrospective-fig), bottom
figure). However, the uncertainty of the 2020 cohort has actually increased
with the addition of another year of fishery data compared to last year's
base model. Medians of various quantities of interest are given in
Table~\@ref(tab:main-parameter-estimates-retro-tab).

Overall, there is little retrospective change to the relative spawning biomass
trajectory up to the mid-2010s, and most retrospective change occurs in the
final years of the retrospective model with the most years removed
(Figure~\@ref(fig:main-biomass-recruitment-retrospective-fig)). In this
assessment, there is very little retrospective bias, with only slight
year-specific positive and negative bias in female spawning biomass, some
minor adjustments to recruitment deviates, and a slight trend in `r b_0` as the
retrospective year increases. All of these retrospective differences are well
within the range of estimation uncertainty across all retrospective years.
There is no indication from retrospective evaluations that the base model is
displaying a systematic bias.

A comparison of the actual assessment models used in each year since
`r min(assess_history_df$yr, na.rm = TRUE)` is shown in
Figure~\@ref(fig:main-historical-assessments-fig). There have been substantial
differences in the structural assumptions of the models and, thus, results
submitted each year. The variability between model results, especially
early on in the time series, is larger than the uncertainty (95%
credibility interval) reported from any single model in recent years. Prior
to 2004, survey catchability was fixed at 1.0 and this assumption was
heavily investigated between 2004 and 2007, leading to variability in model
results because of the use of several different, but fixed, values of survey
catchability. Since 2008, catchability has been freely estimated by the model
(q = `r f(median(base_model$extra_mcmc$q_vector), 2)`). The fixing
of survey catchability had the effect of driving the estimate of initial
biomass upward, which in turn scaled the entire biomass trajectory up,
leading to higher estimates of relative spawning biomass than in more recent
assessments. The median estimates of female spawning biomass for recent years
have remained similar to the previous assessment but declined relative to the
2015--2017 assessments. The difference is most likely related to the recent
under-fitting of the 2017 survey estimate of biomass despite the consistency
in the structure of the assessment model in recent years. In addition to more
information about the 2014 and 2016 cohorts, the 2018 assessment model also
included a change in the data weighting method, an update to maturity and
fecundity, and a change to selectivity parameterization
(Table~\@ref(tab:main-assessment-changes-tab)). The uncertainty interval
associated with the `r end_yr` assessment brackets the majority of the
historical estimates.

The level of uncertainty associated with each assessment's estimate of that
year's current female spawning biomass (i.e., that used to convey current
stock status and inform management advice) changes from assessment to
assessment given updates in data and `r sp` population structure and
dynamics. While uncertainty around the absolute amount of 2023 female
spawning biomass is the second largest (behind the 2017 assessment) since
2012, the relative amount of dispersion (or variability relative to the
stock size; similar to a coefficient of variation) is not inconsistent with
previous assessments (Figure~\@ref(fig:main-historical-dispersion-fig)).

## Performance of past projections {#sec:assessment-past-projections}

Without rigorous simulation experiments it can be difficult to operationally
assess the accuracy of projections in stock assessments because the truth is
never known with 100% certainty. For `r sp`, hindsight comparisons have been
conducted since 2021 [@JTC2021] to evaluate performance of projections
provided in decision tables (such as Tables~\@ref(tab:main-risk-year-1-tab) and~\@ref(tab:main-risk-year-2-tab)) of past assessments relative to updated
assessments. Overall, results indicate that assessment model projections give
a relatively good idea of general projected trends and status.

As an example, the 2019 assessment [@JTC2019] gave the estimated probability
of the female spawning biomass declining in the subsequent year,
i.e., P(*B*~2020~ < *B*~2019~), for several possible catches
in 2019, such as 0~t, 180,000~t, 350,000~t, 410,000~t etc. Now that we 'know'
the catch in 2019 was 412,015~t, we can select the 410,000~t row (close
enough to 412,015~t) in the table from the 2019 assessment to give that
assessment's
P(*B*~2020~<*B*~2019~) = `r prob_decline_from_2019_to_2020_historic`%;
Figure~\@ref(fig:main-historical-1-fig). We can also calculate this probability
from the current assessment model, which implicitly includes the
412,015~t catch from 2019, giving
P(*B*~2020~ < *B*~2019~) = `r prob_decline_from_2019_to_2020_curr`%;
Figure~\@ref(fig:main-historical-1-fig). We extracted similar probabilities
from past assessment documents going back to 2012 and calculate analogous
probabilities,
P(*B*~t+1~ < *B*~t~), from the current base model
[Figure~\@ref(fig:main-historical-1-fig); see @JTC2022 for full methods].

Each assessment correctly predicted whether the stock would most likely increase or
decrease the following year, except for 2017, 2019 (the example just given), 2023;
Figure~\@ref(fig:main-historical-1-fig). Estimates from previous assessments
are closer to 50% than those from the current base model
(Figure~\@ref(fig:main-historical-1-fig)), because the current assessment model
has more information and thus provides a more definitive probability (closer
to 0% or to 100%) than year $t$'s assessment model. It is desirable that the
probabilities from the assessment documents are not too definitive (too close
to 0% or to 100%), because they are admitting a wide range of uncertainty
given unknown recent recruitments.

TODO Last year these were 2018 and 2021 - interesting. GOT TO HERE (going to
make retro figs then come back to, as they help explain it I think).


The 2017, 2019, and 2023 assessments 'incorrectly' projected the stock would likely
decline the following year (given the catch that subsequently occurred),
because the current assessment model estimates a likely increase
(Figure~\@ref(fig:main-historical-1-fig)). In 2018..., this occurred because the
biomass trend was relatively flat
(Figure~\@ref(fig:main-biomass-fig)) so even slight changes in
biomass could influence binomial outcomes of an 'increase' or 'decrease' in
biomass, despite the overall change in biomass not being very substantial. The
2021 assessment [@JTC2021] had no information on the 2020 cohort and predicted
the biomass would probably decline in 2022 even with zero catch in 2021.
However, the current assessment estimates that the 2020 cohort was
particularly large, which highlights how impactful a realized large deviation
from average recruitment (rather than assuming average recruitment) can be
on forecasted outcomes. Similarly, the 2012 assessment had no information on
the very large 2010 recruitment, and so also over-estimated the probability
of decline the following year (Figure~\@ref(fig:main-historical-1-fig)).

A range of catch alternatives are shown for the current assessment because
realized `r assess_yr` catches are not yet known
(Figure~\@ref(fig:main-historical-1-fig)). Catching zero fish in `r assess_yr`
gives the lowest probability that the stock will decline from `r assess_yr`
to `r assess_yr + 1`, with any realistic `r assess_yr` catch leading to a
likely decline in female spawning biomass given current information.

A similar approach was used to calculate the probability of the biomass
falling below `r b_40` in the subsequent year,
i.e., P(*B*~t + 1~ < `r b_40`); Figure~\@ref(fig:main-historical-2-fig).
The 2012 assessment was the only one that gave a >50% chance of the
biomass falling below `r b_40` in the subsequent year, but later data
determined that the 2010 year class was indeed substantial and so in
hindsight the probability of going below `r b_40` was 0% (based on the
current assessment). Since the 2018 assessment, the estimated probabilities
of the biomass falling below `r b_40` were >10% and continued to rise (Figure~\@ref(fig:main-historical-2-fig)), until falling due to the
incoming 2020 cohort. Note that the biomass has been relatively high
during the time period shown, so 'correctly expecting' the biomass to
remain >`r b_40` may not be a particular high bar to attain.

Retrospective versions of Figures~\@ref(fig:main-historical-1-fig)
and \@ref(fig:main-historical-2-fig) are calculated using the current base model
but with data only up to a certain year
(Figures~\@ref(fig:main-historical-retro-1-fig)--
\@ref(fig:main-historical-retro-bforty-all-fig)). While there are some minor
exceptions, the retrospective probabilities of decline (colored squares in
Figures~\@ref(fig:main-historical-retro-1-fig)--
\@ref(fig:main-historical-retro-all-fig)) are generally close to the
probabilities currently estimated using all available data (blue triangles).
An exception is P(*B*~2016~ < *B*~2015~) which is
underestimated (compared to the current base model) until data to 2017 are
included (the 2015 values in each panel of
Figure~\@ref(fig:main-historical-retro-2-fig)). This is due to the
retrospective uncertainty of the 2014 cohort, seen as an increase and then
decrease in expected cohort size in
Figure~\@ref(fig:main-retrospective-recruitment-fig). The retrospective
calculations for P(*B*~t + 1~ < `r b_40`) show little change as more
data are added (Figure~\@ref(fig:main-historical-retro-bforty-all-fig)),
except for 2015 and 2021 as information becomes available about the strong
2014 and 2020 cohorts. Combined, these results enhance confidence in the
projected outcomes from the assessment model.

\newpage
