\newpage

\rfoot{Tables}

# Tables {#sec:tables}

```{r main-catches-us-tab, results = "asis", echo = FALSE}
table_catch(
  ct,
  inc_foreign_jv = TRUE,
  start_yr = start_yr,
  end_yr = end_yr - 1,
  country = "us",
  caption = paste0(
    "Annual catches of ", sp, " (t) in U.S. waters by fleet, ", start_yr,
    "--", last_data_yr, ". Tribal catches are included in the fleet totals. ",
    "Research catch includes landed catch associated with research-related ",
    "activities. Catch associated with surveys and discarded bycatch in ",
    "fisheries not targeting hake is not currently included in the table or ",
    "model."),
  font_size = 8,
  header_font_size = 11,
  longtable = TRUE)
```

```{r main-catches-can-tab, results = "asis", echo = FALSE}
table_catch(
  ct,
  inc_foreign_jv = TRUE,
  start_yr = start_yr,
  end_yr = end_yr - 1,
  country = "can",
  caption = paste0(
    "Annual catches of ", sp, " (t) in Canadian waters by fleet, ",
    start_yr, "--", last_data_yr, "."),
  font_size = 10,
  header_font_size = 11,
  longtable = TRUE)
```

```{r main-landings-tac-tab, results = "asis", echo = FALSE}
table_landings_tac(
  ct,
  start_yr = start_yr,
  end_yr = last_data_yr,
  caption = paste0(
    sp,
    " landings and management decisions, ", start_yr, "--", last_data_yr, ". ",
    "A dash (--)  indicates the management decision was either not ",
    "specified or was unknown to the authors at the time of this ",
    "assessment."),
  font_size = 10,
  header_font_size = 11,
  longtable = TRUE) |>
  landscape()
```

```{r main-sampling-history-tab, results = "asis", echo = FALSE}
table_sampling_history(
  start_yr = start_yr_age_comps,
  end_yr = last_data_yr,
  replace_start_yr = 2010,
  caption = paste0(
    "Annual summary of U.S. and Canadian fishery sampling included in this ",
    "stock assessment by fleet, ", start_yr_age_comps, "--", last_data_yr,
    ". The majority of values are reported as number of hauls but U.S. ",
    "shoreside and Canadian Shoreside fleets are reported as the number ",
    "of trips. A dash (--) indicates there was no sampled catch. The ",
    "number of fish with otoliths sampled per haul has varied over time but ",
    "is typically small."),
  font_size = 10,
  header_font_size = 11,
  longtable = TRUE) |>
  landscape()
```

```{r main-us-cp-age-data-tab, results = "asis", echo = FALSE}
table_age_data(
  fleet = "us_cp",
  start_yr = end_yr - num_recent_yrs,
  end_yr = last_data_yr,
  caption = paste0(
    "Recent age-proportion data used in the assessment for the U.S. ",
    "Catcher-Processor fleet. Proportions are calculated from numbers of ",
    "individuals in each age group. Age 15$+$ is an accumulator group."),
  font_size = 10,
  header_font_size = 11,
  digits = 2,
  longtable = TRUE) |>
  landscape()
```

\newpage

```{r main-us-ms-age-data-tab, results = "asis", echo = FALSE}
table_age_data(
  fleet = "us_ms",
  start_yr = end_yr - num_recent_yrs,
  end_yr = last_data_yr,
  caption = paste0(
    "Recent age-proportion data used in the assessment for the U.S. ",
    "Mothership fleet. Proportions are calculated from numbers of ",
    "individuals in each age group. Age 15$+$ is an accumulator group."),
  font_size = 10,
  header_font_size = 11,
  digits = 2,
  longtable = TRUE) |>
  landscape()
```

```{r main-us-sb-age-data-tab, results = "asis", echo = FALSE}
table_age_data(
  fleet = "us_sb",
  start_yr = end_yr - num_recent_yrs,
  end_yr = last_data_yr,
  caption = paste0(
    "Recent age-proportion data used in the assessment for the U.S. ",
    "shoreside fleet. Proportions are calculated from numbers of ",
    "individuals in each age group. Age 15$+$ is an accumulator group."),
  font_size = 10,
  header_font_size = 11,
  digits = 2,
  longtable = TRUE) |>
  landscape()
```

```{r main-can-ss-age-data-tab, results = "asis", echo = FALSE}
table_age_data(
  fleet = "can_ss",
  start_yr = end_yr - num_recent_yrs,
  end_yr = last_data_yr,
  caption = paste0(
    "Recent age-proportion data used in the assessment for the Canadian ",
    "Shoreside fleet. Proportions are calculated from numbers of individuals ",
    "in each age group. Age 15$+$ is an accumulator group."),
  font_size = 10,
  header_font_size = 11,
  digits = 2,
  longtable = TRUE) |>
  landscape()
```

```{r main-can-ft-age-data-tab, results = "asis", echo = FALSE}
table_age_data(
  fleet = "can_ft",
  start_yr = end_yr - num_recent_yrs,
  end_yr = last_data_yr,
  caption = paste0(
    "Recent age-proportion data used in the assessment for the Canadian ",
    "Freezer trawler fleet. Proportions are calculated from numbers of ",
    "individuals in each age group. Age 15$+$ is an accumulator group."),
  font_size = 10,
  header_font_size = 11,
  digits = 2,
  longtable = TRUE) |>
  landscape()
```

```{r main-input-age-data-fishery-tab, results = "asis", echo = FALSE}
table_input_age_data(
  base_model,
  fleet = "fishery",
  start_yr = start_yr_age_comps,
  end_yr = last_data_yr,
  caption = paste0(
    "Aggregated fishery age-proportion data used in the base model. ",
    "Proportions are calculated from numbers of individuals in each age ",
    "group where the contributions from each fleet are weighted by the ",
    "catch in that fleet. Sample sizes are sum of hauls and trips from ",
    "individual fleets (shown in preceding tables) as described in ",
    "Section~\\@ref(sec:data-fishery-biological-data). Age 15$+$ is an ",
    "accumulator group."),
  font_size = 10,
  header_font_size = 11,
  digits = 2,
  longtable = TRUE) |>
  landscape()
```

```{r main-input-age-data-survey-tab, results = "asis", echo = FALSE}
table_input_age_data(
  base_model,
  fleet = "survey",
  start_yr = start_yr_age_comps,
  end_yr = last_data_yr,
  caption = paste0(
    "Acoustic age 2$+$ survey age-proportion data used in the base model. ",
    "Proportions are calculated from numbers of individuals in each age ",
    "group. Age 15$+$ is an accumulator group."),
  font_size = 10,
  header_font_size = 11,
  digits = 2,
  longtable = TRUE) |>
  landscape()
```

```{r main-survey-history-tab, results = "asis", echo = FALSE}

table_survey_history(
  base_model,
  survey_history_df,
  vessel_sep_lines = FALSE,
  digits = 3,
  caption = paste0(
    "Summary of the acoustic age 2$+$ surveys from ", survey_start_yr,
    " to ", survey_end_yr, "."),
  font_size = 10,
  header_font_size = 11,
  longtable = TRUE)
```

```{r main-survey-by-country-tab, results = "asis", echo = FALSE}
table_survey_by_country(
  survey_by_country_df,
  digits = 3,
  caption = paste0(
    "Summary of the acoustic survey age-2$+$ biomass attributed to each ",
    "country."),
  font_size = 10,
  header_font_size = 11,
  longtable = TRUE)
```

<!-- This is needed to cite within a table caption, see how it is included
the caption below. Note it is OUTSIDE of a knitr chunk. -->
(ref:cite-jtc2018) @JTC2018

```{r main-ovaries-tab, results = "asis", echo = FALSE}
table_ovary_samples(
  ovary_samples_df,
  caption = paste0(
    "Number of ", sp, " ovaries collected for histological analysis and ",
    "included in the estimates of time-varying maturity."),
  font_size = 9,
  header_font_size = 8,
  longtable = TRUE)
```

```{r main-parameters-estimated-summary-tab, results = "asis", echo = FALSE}
table_param_est_bounds(
  base_model,
  start_rec_dev_yr = recruit_dev_start_yr,
  end_rec_dev_yr = main_recdev_end,
  section_sep_lines = TRUE,
  digits = 2,
  caption = paste0(
    "Summary of estimated model parameters and priors in the base model. ",
    "The beta prior is parameterized with a mean and standard deviation (SD). ",
    "The lognormal prior is parameterized with the median and SD in log space."
  ),
  font_size = 9,
  header_font_size = 9,
  longtable = TRUE)
```

```{r main-assessment-changes-tab, results = "asis", echo = FALSE}
table_assessment_changes(
  assess_changes_df,
  start_yr = 2011,
  end_yr = end_yr,
  caption = paste0(
    "Annual changes in the modeling framework used to assess ", sp, " since ",
    "2011. Methods used to weight the age-composition data (Comp Method), ",
    "i.e., McAllister-Ianelli (M-I) and Dirichlet-multinomial (D-M) ",
    "approaches, are explained in the main text. The Markov chain Monte ",
    "Carlo column gives the  number of Markov chain Monte Carlo samples ",
    "used to describe model results and produce statistical inference."),
  font_size = 10,
  header_font_size = 11,
  longtable = TRUE)
```

```{r main-est-numbers-at-age-tab, results = "asis", echo = FALSE}
table_at_age(
  base_model,
  type = "naa",
  end_yr = end_yr,
  caption = paste0(
    "Estimated numbers-at-age at the beginning of the year from the base ",
    "model (posterior medians; millions)."),
  font_size = 9,
  header_font_size = 10,
  longtable = TRUE) |>
  landscape()
```

```{r main-est-biomass-at-age-tab, results = "asis", echo = FALSE}
table_at_age(
  base_model,
  type = "baa",
  end_yr = end_yr,
  caption = paste0(
    "Estimated total biomass-at-age at the beginning of the year from the ",
    "base model (posterior medians; kilotonnes)."),
  font_size = 9,
  header_font_size = 10,
  longtable = TRUE) |>
  landscape()
```

```{r main-est-exp-rate-at-age-tab, results = "asis", echo = FALSE}
table_at_age(
  base_model,
  type = "eraa",
  end_yr = end_yr - 1,
  digits = 2,
  caption = paste0(
    "Estimated exploitation-fraction-at-age (catch-at-age divided by ",
    "biomass-at-age at the beginning of the year) presented as a percentage ",
    "for each year from the base model (posterior medians; percentage of ",
    "age class removed by fishing)."),
  font_size = 8,
  header_font_size = 10,
  longtable = TRUE) |>
  landscape()
```

```{r main-est-catch-at-age-tab, results = "asis", echo = FALSE}
table_at_age(
  base_model,
  type = "caan",
  end_yr = end_yr - 1,
  caption = paste0(
    "Estimated catch-at-age in numbers for each year from the base model ",
    "(posterior medians; thousands)."),
  font_size = 6,
  header_font_size = 10,
  longtable = TRUE) |>
  landscape()
```

```{r main-est-catch-at-age-biomass-tab, results = "asis", echo = FALSE}
table_at_age(
  base_model,
  type = "caab",
  end_yr = end_yr - 1,
  caption = paste0(
    "Estimated catch-at-age in total biomass for each year from the base ",
    "model (posterior medians; tonnes)."),
  font_size = 6,
  header_font_size = 10,
  longtable = TRUE) |>
  landscape()
```

```{r main-cohort-effects-tab, results = "asis", echo = FALSE}
table_cohort(
  base_model,
  cohorts = c(1999, 2010, 2014, 2016, 2020, 2021),
  cohort_bold = TRUE,
  cohort_italics = TRUE,
  cohort_underline = TRUE,
  cohort_line_above = TRUE,
  cohort_line_below = FALSE,
  reverse_cohorts = TRUE,
  caption = paste0(
    "Calculations showing changes in biomass at each age due to natural ",
    "mortality and fishing for recent strong cohorts. Start Biomass is the ",
    "biomass at the beginning of the year, Catch Weight is the catch for ",
    "the cohort for the year, Natural Mortality is the biomass attributed ",
    "to natural mortality, and Surviving Biomass is what survives to the ",
    "end of the year. Surviving Biomass does not equal the Start Biomass ",
    "in the following year because the empirical weights-at-age change ",
    "between years. Estimated quantities are posterior medians."),
  font_size = 9,
  header_font_size = 9,
  longtable = TRUE)
```

```{r main-median-posterior-tab, results = "asis", echo = FALSE}
table_median_posteriors(
  base_model,
  start_yr = start_yr,
  end_yr = end_yr,
  digits = 1,
  caption = paste0(
    "Time series of median posterior population estimates from the base ",
    "model. Relative spawning biomass is spawning biomass relative to the ",
    "unfished equilibrium (", b_0_for_latex_table, "). Total biomass includes
    females and males of ages 0 and above. Age-2$+$ biomass includes females ",
    "and males ages 2 and above. Exploitation fraction is total catch ",
    "divided by total age-2$+$ biomass. Relative fishing intensity is ",
    rel_fishing_intensity_for_latex_table, " such that values below 100\\% ",
    "represent fishing below ", f_40_for_latex_table, ". In the last row, ",
    "dashes (--) indicate quantities requiring ", end_yr, " catch which has ",
    "not taken place yet."),
  font_size = 8,
  header_font_size = 9,
  longtable = TRUE)
```

```{r main-ci-posterior-tab, results = "asis", echo = FALSE}
table_ci_posteriors(
  base_model,
  start_yr = start_yr,
  end_yr = end_yr,
  digits = 1,
  caption = paste0(
    "Time-series of 95\\% posterior credibility intervals for the quantities ",
    "shown in Table \\@ref(tab:main-median-posterior-tab). In the last ",
    "row, dashes (--) indicate quantities requiring ", end_yr, " catch which ",
    "has not taken place yet."),
  font_size = 8,
  header_font_size = 9,
  longtable = TRUE)
```

```{r main-parameter-estimates-tab, results = "asis", echo = FALSE}

table_param_est(
  models = list(base_model, last_yr_base_model),
  model_nms = c(base_model_name, last_yr_base_model_name),
  section_bold = TRUE,
  section_italics = TRUE,
  section_underline = TRUE,
  section_line_above = FALSE,
  section_line_below = FALSE,
  digits = 3,
  caption = paste0(
    "Select parameters, derived quantities, and reference point posterior ",
    "median estimates for the (", end_yr, ") base model compared to the ",
    "previous assessment's (", end_yr - 1, ") base model. Dashes (--) in ",
    "column for the previous assessment indicate quantities that were ",
    " not available in that assessment"),
  font_size = 9,
  header_font_size = 9,
  longtable = TRUE)
```

\clearpage

```{r main-reference-points-tab, results = "asis", echo = FALSE}
table_reference_points(
  base_model,
  category_bold = TRUE,
  category_italics = TRUE,
  category_underline = TRUE,
  category_line_above = FALSE,
  category_line_below = FALSE,
  caption = paste0(
    "Summary of median and 95\\% credibility intervals of equilibrium ",
    "conceptual reference points for the base assessment model. ",
    "Equilibrium reference points were computed using ", start_yr_age_comps,
    "--", end_yr - 1, " averages for mean weight-at-age and baseline ",
    "selectivity-at-age (1966--1990; prior to time-varying deviations). ",
    "Dashes (--) indicate values that are static at one value and do not ",
    "have a credible interval associated with them."),
  font_size = 10,
  header_font_size = 11,
  longtable = TRUE)
```

\clearpage

```{r main-decisions-biomass-tab, results = "asis", echo = FALSE, eval = !is.null(base_model$forecasts)}

table_decision(
  base_model,
  type = "biomass",
  forecast_inds =
    seq_along(base_model$forecasts[[length(base_model$forecasts)]]),
  inc_fi_stable_catch = length(base_model$forecasts[[1]]) == 13,
  caption = paste0(
      "Forecast quantiles of Pacific Hake relative spawning biomass at the ",
      "beginning of the year. Catch alternatives are defined by letters a-o ",
      "and are a constant value across all forecasted years unless ",
      "otherwise defined in the first column. Acronyms are defined in the ",
      "glossary (Appendix~\\@ref(sec:app-glossary))."),
  bold_letters = TRUE,
  digits = 2,
  # Font values higher than 8 and 11 for table and header respectively
  # will cause the table to wrap to a second page
  font_size = 8,
  header_font_size = 11,
  # If the font is changed it is almost guaranteed that `left_col_cm` and
  # `right_cols_cm` will have to be changed, especially if the font is made
  # larger. You will have to check this with trial-and-error, building the
  # document, checking the table and adjusting, over and over until it looks
  # right
  left_col_cm = 3,
  right_cols_cm = 1.2,
  longtable = TRUE)
```

\clearpage

```{r main-decisions-spr-tab, results = "asis", echo = FALSE, eval = !is.null(base_model$forecasts)}

table_decision(
  base_model,
  type = "spr",
  forecast_inds =
    seq_along(base_model$forecasts[[length(base_model$forecasts)]]),
  inc_fi_stable_catch = length(base_model$forecasts[[1]]) == 13,
  caption = paste0(
      "Forecast quantiles of Pacific Hake relative fishing intensity ",
      rel_fishing_intensity_for_latex_table, ", expressed as a proportion. ",
      "Catch alternatives are defined by letters a-o and are a constant ",
      "value across all forecasted years unless otherwise defined in the ",
      "first column. Acronyms are defined in the glossary ",
      "(Appendix~\\@ref(sec:app-glossary))."),
  bold_letters = TRUE,
  digits = 2,
  # Font values higher than 8 and 11 for table and header respectively
  # will cause the table to wrap to a second page
  font_size = 8,
  header_font_size = 11,
  # If the font is changed it is almost guaranteed that `left_col_cm` and
  # `right_cols_cm` will have to be changed, especially if the font is made
  # larger
  left_col_cm = 3,
  right_cols_cm = 1.2,
  longtable = TRUE)
```

```{r main-risk-year-1-tab, results = "asis", echo = FALSE, eval = !is.null(base_model$risks)}
# Index in model$risks to use, e.g. 1 means forecast year 2 compared to
# forecast year 1
table_risk(
  base_model,
  forecast_yrs,
  index = 1,
  type = "probability",
  digits = 2,
  caption = paste0(
    "Probabilities related to spawning biomass, relative fishing intensity, ",
    "and the ", end_yr + 1, " default harvest policy catch for alternative ",
    end_yr, " catch options (catch options explained in ",
    "Table~\\@ref(tab:main-decisions-biomass-tab))."),
  font_size = 10,
  header_font_size = 10,
  longtable = TRUE)
```
```{r main-risk-year-2-tab, results = "asis", echo = FALSE, eval = !is.null(base_model$risks)}
# Index in model$risks to use, e.g. 1 means forecast year 2 compared to
# forecast year 1
table_risk(
  base_model,
  forecast_yrs,
  index = 2,
  type = "probability",
  digits = 2,
  caption = paste0(
    "Probabilities related to spawning biomass, relative fishing intensity, ",
    "and the ", end_yr + 2, " default harvest policy catch for alternative ",
    end_yr + 1, " catch options, given the ", end_yr, " catch level shown ",
    "in Table~\\@ref(tab:main-risk-year-1-tab) (catch options explained in ",
    "Table~\\@ref(tab:main-decisions-biomass-tab))."),
  font_size = 10,
  header_font_size = 10,
  longtable = TRUE)
```

<!--```{r main-risk-year-3-tab, results = "asis", echo = FALSE, eval = !is.null(base_model$risks)}-->
<!--# Index in model$risks to use, e.g. 1 means forecast year 2 compared to-->
<!--# forecast year 1-->
<!--table_risk(-->
<!--  base_model,-->
<!--  forecast_yrs,-->
<!--  index = 3,-->
<!--  type = "probability",-->
<!--  digits = 2,-->
<!--  caption = paste0(-->
<!--    "Probabilities related to spawning biomass, relative fishing intensity, ",-->
<!--    "and the ", end_yr + 3, " default harvest policy catch for alternative ",-->
<!--    end_yr + 2, " catch options, given the ", end_yr, " and ", end_yr + 1,-->
<!--    " catch levels shown in Tables~\\@ref(tab:main-risk-year-1-tab) and~",-->
<!--    "\\@ref(tab:main-risk-year-2-tab) (catch options explained in Table~",
<!--    "\\@ref(tab:main-decisions-biomass-tab))."),-->
<!--  font_size = 10,-->
<!--  header_font_size = 10,-->
<!--  longtable = TRUE)-->
<!--```-->

<!-- The following ADJUST TABLE macro is used by the post-processor to shift
the table left by this many inches. The margins are modified for this
page only -->
ADJUST TABLE 0.5
```{r main-parameter-estimates-sens-1-tab, results = "asis", echo = FALSE}
if(!all(is.na(sens_models[[1]]))){
  table_param_est(
    models = sens_models[[1]],
    model_nms = sens_models_names[[1]],
    section_bold = TRUE,
    section_italics = TRUE,
    section_underline = TRUE,
    section_line_above = TRUE,
    section_line_below = FALSE,
    digits = 3,
    caption = paste0(
      "Posterior medians for select parameters, derived quantities, reference ",
      "points, and negative log likelihoods for the base model and some ",
      "sensitivity runs (described in ",
      "Section~\\@ref(sec:assessment-sensitivity-analyses)). A dash (--) ",
      "indicates that the parameter or derived quantity was not estimated in ",
      "the model."),
    right_cols_cm = 1.8,
    font_size = 8,
    header_font_size = 9,
    longtable = TRUE,
    show_loglike = FALSE) |>
    landscape()
}
```

```{r main-parameter-estimates-sens-2-tab, results = "asis", echo = FALSE}

if(!all(is.na(sens_models[[1]]))){
  table_param_est(
    models = sens_models[[2]],
    model_nms = sens_models_names[[2]],
    section_bold = TRUE,
    section_italics = TRUE,
    section_underline = TRUE,
    section_line_above = TRUE,
    section_line_below = FALSE,
    digits = 3,
    caption = paste0(
      "Posterior medians for select parameters, derived quantities, reference ",
      "points, and negative log likelihoods for the base model and further ",
      "sensitivity runs (described in ",
      "Section~\\@ref(sec:assessment-sensitivity-analyses)). A dash (--) ",
      "indicates that the parameter or derived quantity was not estimated in ",
      "the model."),
    right_cols_cm = 2,
    font_size = 9,
    header_font_size = 9,
    longtable = TRUE,
    show_loglike = FALSE) |>
    landscape()
}
```

```{r main-parameter-estimates-sens-3-tab, results = "asis", echo = FALSE}

if(!all(is.na(sens_models[[1]]))){
  table_param_est(
    models = sens_models[[3]],
    model_nms = sens_models_names[[3]],
    section_bold = TRUE,
    section_italics = TRUE,
    section_underline = TRUE,
    section_line_above = TRUE,
    section_line_below = FALSE,
    digits = 3,
    caption = paste0(
      "Posterior medians for select parameters, derived quantities, reference ",
      "points, and negative log likelihoods for the base model and further ",
      "sensitivity runs (described in ",
      "Section~\\@ref(sec:assessment-sensitivity-analyses)). A dash (--) ",
      "indicates that the parameter or derived quantity was not estimated in ",
      "the model."),
    right_cols_cm = 1.8,
    font_size = 9,
    header_font_size = 9,
    longtable = TRUE,
    show_loglike = FALSE) |>
    landscape()
}
```

```{r main-parameter-estimates-retro-tab, results = "asis", echo = FALSE}

table_param_est(
  base_model$retrospectives$retro_param_est,
  section_bold = TRUE,
  section_italics = TRUE,
  section_underline = TRUE,
  section_line_above = TRUE,
  section_line_below = FALSE,
  digits = 3,
  caption = paste0(
    "Posterior medians from the base model for select parameters, derived ",
    "quantities, reference point estimates, and negative log likelihoods ",
    "for retrospective analyses. Some values are implied since they occur ",
    "after the ending year of the respective retrospective analysis. A ",
    "dash (--) indicates that the parameter or derived quantity was not ",
    "output by the model."),
  right_cols_cm = 1.8,
  font_size = 9,
  header_font_size = 9,
  longtable = TRUE,
  show_loglike = FALSE) |>
  landscape()
```
