\newpage

\rfoot{Tables}

# Tables {#sec:tables}

```{r catches-us, results = "asis", echo = FALSE}
table_catch(
  ct,
  inc_foreign_jv = TRUE,
  start_yr = start_yr,
  end_yr = end_yr - 1,
  country = "us",
  caption = paste0(
    "Annual catches of ", sp, " (t) in U.S. waters by fleet, ", start_yr,
    "-", last_data_yr, ". Tribal catches are included in the fleet totals. ",
    "Research catch includes landed catch associated with research-related ",
    "activities. Catch associated with surveys and discarded bycatch in ",
    "fisheries not targeting hake is not currently included in the table or ",
    "model."),
  font_size = 12,
  header_font_size = 10,
  longtable = TRUE)
```

\clearpage

```{r catches-can, results = "asis", echo = FALSE}
table_catch(
  ct,
  inc_foreign_jv = TRUE,
  start_yr = start_yr,
  end_yr = end_yr - 1,
  country = "can",
  caption = paste0(
    "Annual catches of ", sp, " (t) in Canadian  waters by fleet, ",
    start_yr, "-", last_data_yr, "."),
  font_size = 10,
  header_font_size = 8,
  longtable = TRUE)
```


```{r main-landings-tac-table, results = "asis", echo = FALSE}
table_landings_tac(
  ct,
  start_yr = start_yr,
  end_yr = end_yr - 1,
  caption = paste0(
    sp,
    "landings and management decisions. A dash (--)  indicates the ",
    "management decision was either not specified or was unknown to the ",
    "authors at the time of this assessment."),
  font_size = 10,
  header_font_size = 8,
  longtable = TRUE) |> 
  landscape()
```

```{r main-sampling-history-table, results = "asis", echo = FALSE}
table_sampling_history(
  sampling_history_df,
  start_yr = start_yr_age_comps,
  end_yr = last_data_yr,
  caption = paste0(
    "Annual summary of U.S. and Canadian fishery sampling included in this ",
    "stock assessment by fleet. Majority of values are reported as number of ",
    "hauls but U.S. shore-based and Canadian shoreside fleets are reported ",
    "as the number of trips. A dash (--) indicates there was no sampled ",
    "catch. The number of fish with otoliths sampled per haul has varied ",
    "over time but is typically small."),
  font_size = 10,
  header_font_size = 8,
  longtable = TRUE)
```

\clearpage

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-us-cp-age-data-table, results = "asis", echo = FALSE} -->
<!-- make.us.age.data.table( -->
<!--   us_cp_age_df, -->
<!--   fleet = 1, -->
<!--   start_yr = end_yr - num_recent_yrs, -->
<!--   end_yr = last_data_yr, -->
<!--   xcaption = paste0( -->
<!--     "Recent age-proportion data used in the assessment for the U.S. ", -->
<!--     "Catcher-Processor fleet. Proportions are calculated from numbers of ", -->
<!--     "individuals in each age group. Age 15 is an accumulator group."), -->
<!--   xlabel = "tab:main-us-cp-age-data", -->
<!--   font.size = 10, -->
<!--   space.size = 11, -->
<!--   decimals = 2) -->
<!-- ``` -->

<!-- ```{r main-us-ms-data-table, results = "asis", echo = FALSE} -->
<!-- make.us.age.data.table( -->
<!--   us_ms_age_df, -->
<!--   fleet = 2, -->
<!--   start_yr = end_yr - num_recent_yrs, -->
<!--   end_yr = last_data_yr, -->
<!--   xcaption = paste0( -->
<!--     "Recent age-proportion data used in the assessment for the U.S. ", -->
<!--     "Mothership fleet. Proportions are calculated from numbers of ", -->
<!--     "individuals in each age group. Age 15 is an accumulator group."), -->
<!--   xlabel = "tab:main-us-ms-age-data", -->
<!--   font.size = 10, -->
<!--   space.size = 11, -->
<!--   decimals = 2) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-us-shore-age-data-table, results = "asis", echo = FALSE} -->
<!-- make.us.age.data.table( -->
<!--   us_ss_age_df, -->
<!--   fleet = 3, -->
<!--   start_yr = end_yr - num_recent_yrs, -->
<!--   end_yr = last_data_yr, -->
<!--   xcaption = paste0( -->
<!--     "Recent age-proportion data used in the assessment for the U.S. ", -->
<!--     "Shore-Based fleet. Proportions are calculated from numbers of ", -->
<!--     "individuals in each age group. Age 15 is an accumulator group."), -->
<!--   xlabel = "tab:main-us-shore-age-data", -->
<!--   font.size = 10, -->
<!--   space.size = 11, -->
<!--   decimals = 2) -->
<!-- ``` -->

<!-- ```{r main-can-shore-age-data-table, results = "asis", echo = FALSE} -->
<!-- make.can.age.data.table( -->
<!--   can_ages_lst, -->
<!--   can_ss_num_fish, -->
<!--   fleet = 1, -->
<!--   start_yr = end_yr - num_recent_yrs, -->
<!--   end_yr = last_data_yr, -->
<!--   xcaption = paste0( -->
<!--     "Recent age-proportion data used in the assessment for the Canadian ", -->
<!--     "Shoreside fleet. Proportions are calculated from numbers of individuals ", -->
<!--     "in each age group. Age 15 is an accumulator group."), -->
<!--   xlabel = "tab:main-can-shore-age-data", -->
<!--   font.size = 10, -->
<!--   space.size = 11, -->
<!--   decimals = 2) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-can-ft-age-data-table, results = "asis", echo = FALSE} -->
<!-- make.can.age.data.table( -->
<!--   can_ages_lst, -->
<!--   can_ft_num_fish, -->
<!--   fleet = 2, -->
<!--   start_yr = end_yr - num_recent_yrs, -->
<!--   end_yr = last_data_yr, -->
<!--   xcaption = paste0( -->
<!--     "Recent age-proportion data used in the assessment for the Canadian ", -->
<!--     "freezer-trawler fleet. Proportions are calculated from numbers of ", -->
<!--     "individuals in each age group. Age 15 is an accumulator group."), -->
<!--   xlabel = "tab:main-can-ft-age-data", -->
<!--   font.size = 10, -->
<!--   space.size = 11, -->
<!--   decimals = 2) -->
<!-- ``` -->

<!-- \clearpage -->

<!-- ```{r main-all-age-data-fishery-table, results = "asis", echo = FALSE} -->
<!-- make.input.age.data.table( -->
<!--   base_model, -->
<!--   fleet = 1, -->
<!--   start_yr = start_yr_age_comps, -->
<!--   end_yr = last_data_yr, -->
<!--   csv.dir = output_csv_dir, -->
<!--   xcaption = paste0( -->
<!--     "Aggregated fishery age-proportion data used in the base model. ", -->
<!--     "Proportions are calculated from numbers of individuals in each age ", -->
<!--     "group where the contributions from each fleet are weighted by the ", -->
<!--     "catch in that fleet. Sample sizes are sum of hauls and trips from ", -->
<!--     "individual fleets (shown in preceding tables) as described in ", -->
<!--     "Section~\\@ref(sec:data-fishery-biological-data). Age 15 is an ", -->
<!--     "accumulator group for comparing observed and expected proportions."), -->
<!--   xlabel = "tab:main-all-age-data-fishery", -->
<!--   font.size = 10, -->
<!--   space.size = 11, -->
<!--   decimals = 2) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->
<!-- \clearpage -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-all-age-survey-table, results = "asis", echo = FALSE} -->
<!-- make.input.age.data.table( -->
<!--   base_model, -->
<!--   fleet = 2, -->
<!--   start_yr = survey_start_yr, -->
<!--   end_yr = survey_end_yr, -->
<!--   csv.dir = output_csv_dir, -->
<!--   xcaption = paste0( -->
<!--     "Survey age-proportion data used in the base model. Proportions are ", -->
<!--     "calculated from numbers of individuals in each age group. Age 15 is an ", -->
<!--     "accumulator group."), -->
<!--   xlabel = "tab:main-all-age-data-survey", -->
<!--   font.size = 10, -->
<!--   space.size = 11, -->
<!--   decimals = 2) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->

<!-- ```{r main-survey-history-table, results = "asis", echo = FALSE} -->
<!-- make.survey.history.table( -->
<!--   survey_history_df, -->
<!--   base_model$dat$CPUE, -->
<!--   digits = 3, -->
<!--   xcaption = paste0( -->
<!--     "Summary of the acoustic surveys from ", survey_start_yr, " to ", -->
<!--     survey_end_yr, "."), -->
<!--   xlabel = "tab:main-survey-history", -->
<!--   font.size = 10, -->
<!--   space.size = 11) -->
<!-- ``` -->

<!-- ```{r main-survey-by-country-table, results = "asis", echo = FALSE} -->
<!-- make.survey.by.country.table( -->
<!--   survey_by_country_df, -->
<!--   digits = 3, -->
<!--   xcaption = paste0( -->
<!--     "Summary of the acoustic survey age-2+ biomass attributed to each ", -->
<!--     "country."), -->
<!--   xlabel = "tab:main-survey-by-country", -->
<!--   font.size = 10, -->
<!--   space.size = 12) -->
<!-- ``` -->


<!-- ```{r main-maturity-ogives-table, results = "asis", echo = FALSE} -->
<!-- make.maturity.ogives.table( -->
<!--   maturity.ogives, -->
<!--   xcaption = paste0( -->
<!--     "Information on maturity and fecundity used in this assessment as shown ", -->
<!--     "in Figure~\\@ref(fig:main-maturity). The sample sizes refer to the ", -->
<!--     "subset of samples in Table~\\@ref(tab:main-ovaries) for which age ", -->
<!--     "readings and histological estimates of maturity have been completed. ", -->
<!--     "The mean weight (kg) is based on a much larger set of samples. Mean ", -->
<!--     "fecundity is the product of maturity and mean weight but note that ", -->
<!--     "year-specific fecundities from ", start_yr_age_comps, "--", last_data_yr, -->
<!--     " were used in the stock assessment. The values reported for ages 15 ", -->
<!--     "and above represent the average across all samples in this range."), -->
<!--   xlabel = "tab:main-ogives", -->
<!--   font.size = 10, -->
<!--   space.size = 11) -->
<!-- ``` -->

<!-- ```{r main-ovaries-table, results = "asis", echo = FALSE} -->
<!-- make.maturity.samples.table( -->
<!--   ovary_samples_df, -->
<!--   xcaption = paste0( -->
<!--     "Number of ", sp, " ovaries collected for histological analysis. The ", -->
<!--     "maturity ogive was determined from a subset of these samples (up to ", -->
<!--     "and including 2017; @JTC2018).", -->
<!--   xlabel = "tab:main-ovaries", -->
<!--   font.size = 10, -->
<!--   space.size = 11) -->
<!-- ``` -->
<!-- \clearpage -->

<!-- ```{r main-parameters-estimated-summary-table, results = "asis", echo = FALSE} -->
<!-- table_param_est_bounds( -->
<!--   base_model, -->
<!--   start.rec.dev.yr = recruit_dev_start_yr, -->
<!--   end.rec.dev.yr = end_yr - 1, -->
<!--   digits = 2, -->
<!--   xcaption = paste0( -->
<!--     "Summary of estimated model parameters and priors in the base model. ", -->
<!--     "The beta prior is parameterized with a mean and standard deviation. ", -->
<!--     "The lognormal prior is parameterized with the median and standard ", -->
<!--     "deviation in log space."), -->
<!--   xlabel = "tab:main-params-est-summary", -->
<!--   font.size = 10, -->
<!--   space.size = 11) -->
<!-- ``` -->

<!-- \clearpage -->

<!-- ```{r main-assessment-changes-table, results = "asis", echo = FALSE} -->
<!-- make.assessment.changes.table( -->
<!--   assess_changes_df, -->
<!--   xcaption = paste0( -->
<!--     "Annual changes in the modeling framework used to assess ", sp, " since ", -->
<!--     "2011. Methods used to weight the age-composition data (Comp Method), ", -->
<!--     "i.e., McAllister-Ianelli (MI) and Dirichlet-multinomial (D-M) ", -->
<!--     "approaches, are explained in the main text. The MCMC column gives the ", -->
<!--     "number of Markov chain Monte Carlo samples used to describe model ", -->
<!--     "results and produce statistical inference."), -->
<!--   xlabel = "tab:main-assessment-changes", -->
<!--   font.size = 10, -->
<!--   space.size = 11) -->
<!-- ``` -->
<!-- \clearpage -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-est-numbers-at-age-table, results = "asis", echo = FALSE} -->
<!-- atage_table( -->
<!--   base_model, -->
<!--   table_type = 1, -->
<!--   end_yr = end_yr, -->
<!--   xcaption = paste0( -->
<!--     "Estimated numbers-at-age at the beginning of the year from the base ", -->
<!--     "model (posterior medians; million)."), -->
<!--   xlabel = "tab:main-est-numbers-at-age", -->
<!--   font_size = 9, -->
<!--   space_size = 10) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->
<!-- \clearpage -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-est-biomass-at-age-table, results = "asis", echo = FALSE} -->
<!-- atage_table( -->
<!--   base_model, -->
<!--   table_type = 5, -->
<!--   end_yr = end_yr, -->
<!--   xcaption = paste0( -->
<!--     "Estimated total biomass-at-age at the beginning of the year from the ", -->
<!--     "base model (posterior medians; thousand t)."), -->
<!--   xlabel = "tab:main-est-biomass-at-age", -->
<!--   font_size = 9, -->
<!--   space_size = 10) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-est-exp-rate-at-age-table, results = "asis", echo = FALSE} -->
<!-- atage_table( -->
<!--   base_model, -->
<!--   table_type = 2, -->
<!--   end_yr = end_yr - 1, -->
<!--   digits = 2, -->
<!--   xcaption = paste0( -->
<!--     "Estimated exploitation-fraction-at-age (catch-at-age divided by ", -->
<!--     "biomass-at-age at the beginning of the year) presented as a percentage ", -->
<!--     "for each year from the base model (posterior medians; percentage of ", -->
<!--     "age class removed by fishing)."), -->
<!--   xlabel = "tab:main-est-exp-rate-at-age", -->
<!--   font_size = 9, -->
<!--   space_size = 10) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-est-catch-at-age-table, results = "asis", echo = FALSE} -->
<!-- atage_table( -->
<!--   base_model, -->
<!--   table_type = 3, -->
<!--   end_yr = end_yr - 1, -->
<!--   xcaption = paste0( -->
<!--     "Estimated catch-at-age in numbers for each year from the base model ", -->
<!--     "(posterior medians; thousands)."), -->
<!--   xlabel = "tab:main-est-catch-at-age", -->
<!--   font_size = 6, -->
<!--   space_size = 7) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-est-catch-at-age-biomass-table, results = "asis", echo = FALSE} -->
<!-- atage_table( -->
<!--   base_model, -->
<!--   table_type = 4, -->
<!--   end_yr = end_yr - 1, -->
<!--   xcaption = paste0( -->
<!--     "Estimated catch-at-age in total biomass for each year from the base ", -->
<!--     "model (posterior medians; t)."), -->
<!--   xlabel = "tab:main-est-catch-at-age-biomass", -->
<!--   font_size = 6, -->
<!--   space_size = 7) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-cohort-effects-table, results = "asis", echo = FALSE} -->
<!-- cohort_table( -->
<!--   base_model, -->
<!--   end_yr = end_yr, -->
<!--   cohorts = c(1999, 2010, 2014, 2016), -->
<!--   # csv_dir = output_csv_dir, -->
<!--   xcaption = paste0( -->
<!--     "Calculations showing changes in biomass at each age due to natural ", -->
<!--     "mortality and fishing for recent strong cohorts. Start Biomass is the ", -->
<!--     "biomass at the beginning of the year, Catch Weight is the catch for ", -->
<!--     "the cohort for the year, M is the biomass attributed to natural ", -->
<!--     "mortality, and Surviving Biomass is what survives to the end of the ", -->
<!--     "year. Surviving Biomass does not equal the Start Biomass in the ", -->
<!--     "following year because the empirical weights-at-age change ", -->
<!--     "between years. Estimated quantities are posterior medians."), -->
<!--   xlabel = "tab:main-cohort-effects", -->
<!--   font_size = 7, -->
<!--   space_size = 8) -->
<!-- ``` -->
<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->
<!-- \clearpage -->

<!-- ```{r main-median-posterior-table, results = "asis", echo = FALSE} -->
<!-- make.median.posterior.table( -->
<!--   base_model, -->
<!--   start_yr = start_yr, -->
<!--   end_yr = end_yr, -->
<!--   digits = 1, -->
<!--   csv.dir = output_csv_dir, -->
<!--   xcaption = paste0( -->
<!--     "Time series of median posterior population estimates from the base ", -->
<!--     "model. Relative spawning biomass is spawning biomass relative to the ", -->
<!--     "unfished equilibrium ($\\Bzero$). Total biomass includes females and ", -->
<!--     "males of ages 0 and above. Age-2+ biomass includes females and males ", -->
<!--     "ages 2 and above. Exploitation fraction is total catch divided by ", -->
<!--     "total age-2+ biomass. Relative fishing intensity is ", -->
<!--     "(1-SPR)/(1-SPR\\subscr{40\\%}) such that values below 100\\% ", -->
<!--     "represent fishing below $\\Fforty$. A dash (--) indicates a quantity ", -->
<!--     "requiring ", end_yr, " catch which has not taken place yet."), -->
<!--   xlabel = "tab:main-median-posterior", -->
<!--   font.size = 9, -->
<!--   space.size = 10) -->
<!-- ``` -->

<!-- \clearpage -->

<!-- ```{r main-ci-posterior-table, results = "asis", echo = FALSE} -->
<!-- make.ci.posterior.table( -->
<!--   base_model, -->
<!--   start_yr = start_yr, -->
<!--   end_yr = end_yr, -->
<!--   digits = 1, -->
<!--   xcaption = paste0( -->
<!--     "Time-series of 95\\% posterior credibility intervals for the quantities ", -->
<!--     "shown in Table \\@ref(tab:main-median-posterior). A dash (--) indicates ", -->
<!--     "a quantity requiring ", end_yr, " catch which has not taken place yet."), -->
<!--   xlabel = "tab:main-ci-posterior", -->
<!--   font.size = 8, -->
<!--   space.size = 9, -->
<!--   lower_col = "2.5%", -->
<!--   upper_col = "97.5%") -->
<!-- ``` -->

<!-- ```{r main-parameter-estimates, results = "asis", echo = FALSE} -->
<!-- table_param_est( -->
<!--   list(base_model, last_yr_base_model), -->
<!--   model_nms = c(base_model_name, last_yr_base_model_name), -->
<!--   end_yr = end_yr, -->
<!--   digits = 3, -->
<!--   rec_yrs = c(2010, 2014, 2016, 2020), -->
<!--   show_like = FALSE, -->
<!--   xcaption = -->
<!--     paste0( -->
<!--       "Select parameters, derived quantities, and reference point posterior ", -->
<!--       "median estimates for the (", end_yr, ") base model compared to the ", -->
<!--       "previous assessment's (", end_yr - 1, ") base model."), -->
<!--   xlabel = "tab:main-parameter-estimates", -->
<!--   font_size = 10, -->
<!--   space_size = 11) -->
<!-- ``` -->

<!-- ```{r main-reference-points-table, results = "asis", echo = FALSE} -->
<!-- table_reference_points.old( -->
<!--   base_model, -->
<!--   xcaption = paste0( -->
<!--     "Summary of median and 95\\% credibility intervals of equilibrium ", -->
<!--     "conceptual reference points for the base assessment model. ", -->
<!--     "Equilibrium reference points were computed using 1975--", end_yr - 1, -->
<!--     " averages for mean weight-at-age and baseline selectivity-at-age ", -->
<!--     "(1966--1990; prior to time-varying deviations.)"), -->
<!--   xlabel = "tab:main-reference-points", -->
<!--   font.size = 10, -->
<!--   space.size = 11, -->
<!--   placement = "h") -->
<!-- ``` -->

<!-- \clearpage -->

<!-- ```{r main-biomass-table, results = "asis", echo = FALSE} -->
<!-- table_decision( -->
<!--   base_model, -->
<!--   xcaption = paste0( -->
<!--       "Forecast quantiles of ", sp, "relative spawning biomass at the ", -->
<!--       "beginning of the year. Catch alternatives are based on: constant ", -->
<!--       "catches (rows ", ct_constant_str, "), including catch similar to ", -->
<!--       min(forecast_yrs_extra) - 1," (row~", letters[ct_actual_ind], -->
<!--       ") and to the TAC from ", min(forecast_yrs_extra) - 1," (row~", -->
<!--       letters[ct_tac_ind], "); and non-constant catches that result in ", -->
<!--       "annual 10\\% declines in catch (rows ", ct_reduction_str, -->
<!--       "), median relative fishing intensity of 100\\% (row ", -->
<!--       letters[ct_spr100_ind], "), median catch estimated via the default ", -->
<!--       "harvest policy (\\Ffortyten, row~", letters[ct_default_policy_ind], -->
<!--       "), and the fishing intensity that results in the median projected ", -->
<!--       "catch remaining the same in ", min(forecast_yrs_extra), " and ", -->
<!--       min(forecast_yrs_extra) + 1, " (row~", letters[ct_stable_ind], ")."), -->
<!--   xlabel = "tab:main-decisions-biomass", -->
<!--   font.size = 11, -->
<!--   space.size = 12, -->
<!--   type = "biomass", -->
<!--   placement = "tbp") -->
<!-- ``` -->

<!-- \clearpage -->

<!-- ```{r main-decisions-spr-table, results = "asis", echo = FALSE} -->
<!-- table_decision( -->
<!--   base_model, -->
<!--   xcaption = paste0( -->
<!--     "Forecast quantiles of ", sp, " relative fishing intensity ", -->
<!--     "(1-SPR)/(1-SPR\\subscr{40\\%}), expressed as a proportion, for the ", -->
<!--     min(forecast_yrs), "--", max(forecast_yrs) - 1, " catch alternatives ", -->
<!--     "presented in Table~\\@ref(tab:main-decisions-biomass). Values greater ", -->
<!--     "than 1 indicate relative fishing intensities greater than the ", -->
<!--     "$\\Fforty$ harvest policy calculated using baseline selectivity."), -->
<!--   xlabel = "tab:main-decisions-spr", -->
<!--   font.size = 11, -->
<!--   space.size = 12, -->
<!--   type = "spr", -->
<!--   placement = "tbp") -->
<!-- ``` -->

<!-- \clearpage -->

<!-- ```{r main-risk-forecast-year-1-table, results = "asis", echo = FALSE} -->
<!-- # Index in model$risks to use, e.g. 1 means forecast year 2 compared to -->
<!-- # forecast year 1 -->
<!-- table_risk( -->
<!--   base_model, -->
<!--   forecast_yrs, -->
<!--   index = 1, -->
<!--   xcaption = paste0( -->
<!--     "Probabilities related to spawning biomass, relative fishing intensity, " -->
<!--     "and the ", end_yr + 1, " default harvest policy catch for alternative ", -->
<!--     end_yr, " catch options (catch options explained in ", -->
<!--     "Table~\\@ref(tab:main-decisions-biomass))."), -->
<!--   xlabel = "tab:main-risk-year-1", -->
<!--   font.size = 11, -->
<!--   space.size = 13, -->
<!--   catch_col_width_cm = 1.9) -->
<!-- ``` -->

<!-- ```{r main-risk-forecast-year-2-table, results = "asis", echo = FALSE} -->
<!-- # Index in model$risks to use, e.g. 1 means forecast year 2 compared to -->
<!-- # forecast year 1 -->
<!-- table_risk( -->
<!--   base_model, -->
<!--   forecast_yrs, -->
<!--   index = 2, -->
<!--   xcaption = paste0( -->
<!--     "Probabilities related to spawning biomass, relative fishing intensity, ", -->
<!--     "and the ", end_yr + 2, " default harvest policy catch for alternative ", -->
<!--     end_yr + 1, " catch options, given the ", end_yr, " catch level shown ", -->
<!--     "in Table~\\@ref(tab:main-risk-year-1) (catch options explained in ", -->
<!--     "Table~\\@ref(tab:main-decisions-biomass))."), -->
<!--   xlabel = "tab:main-risk-year-2", -->
<!--   font.size = 11, -->
<!--   space.size = 13, -->
<!--   catch_col_width_cm = 1.9) -->
<!-- ``` -->

<!-- ```{r main-risk-forecast-year-3-table, results = "asis", echo = FALSE} -->
<!-- # Index in model$risks to use, e.g. 1 means forecast year 2 compared to -->
<!-- # forecast year 1 -->
<!-- table_risk( -->
<!--   base_model, -->
<!--   forecast_yrs, -->
<!--   index = 3, -->
<!--   xcaption = paste0( -->
<!--     "Probabilities related to spawning biomass, relative fishing intensity, ", -->
<!--     "and the ", end_yr + 3, " default harvest policy catch for alternative ", -->
<!--     end_yr + 2, " catch options, given the ", end_yr, " and ", end_yr + 1, -->
<!--     " catch levels shown in Tables~\\@ref(tab:main-risk-year-1) and~", -->
<!--     "\\@ref(tab:main-risk-year-2) (catch options explained in Table~", -->
<!--     "\\@ref(tab:main-decisions-biomass))."), -->
<!--   xlabel = "tab:main-risk-year-3", -->
<!--   font.size = 11, -->
<!--   space.size = 13, -->
<!--   catch_col_width_cm = 1.9) -->
<!-- ``` -->

<!-- \clearpage -->

<!-- \begin{landscape} -->
<!-- \pagestyle{mylandscape} -->
<!-- \centering -->
<!-- ```{r main-parameter-estimates-sens-1, results = "asis", echo = FALSE} -->
<!-- table_param_est( -->
<!--   sens_models[[1]], -->
<!--   model_nms = sens_models_names[[1]], -->
<!--   end_yr = end_yr, -->
<!--   digits = 3, -->
<!--   xcaption = paste0( -->
<!--     "Posterior medians for select parameters, derived quantities, reference ", -->
<!--     "points, and negative log likelihoods for the base model and some ", -->
<!--     "sensitivity runs (described in ", -->
<!--     "Section~\\@ref(sec:assessment-sensitivity-analyses)). A dash (--) ", -->
<!--     "indicates that the parameter or derived quantity was not estimated in ", -->
<!--     "the model."), -->
<!--   xlabel = "tab:main-parameter-estimates-sens-1", -->
<!--   font_size = 9, -->
<!--   space_size = 10, -->
<!--   rec_yrs = c(2010, 2014, 2016, 2020)) -->
<!-- ``` -->

<!-- ```{r main-parameter-estimates-sens-2, results = "asis", echo = FALSE} -->
<!-- table_param_est( -->
<!--   sens_models[[2]], -->
<!--   model_nms = sens_models_names[[2]], -->
<!--   end_yr = end_yr, -->
<!--   digits = 3, -->
<!--   xcaption = paste0( -->
<!--     "Posterior medians for select parameters, derived quantities, reference ", -->
<!--     "points, and negative log likelihoods for the base model and further ", -->
<!--     "sensitivity runs (described in ", -->
<!--     "Section~\\@ref(sec:assessment-sensitivity-analyses)). A dash (--) ", -->
<!--     "indicates that the parameter or derived quantity was not estimated in ", -->
<!--     "the model."), -->
<!--   xlabel = "tab:main-parameter-estimates-sens-2", -->
<!--   font_size = 9, -->
<!--   space_size = 11, -->
<!--   rec_yrs = c(2010, 2014, 2016, 2020)) -->
<!-- ``` -->

<!-- ```{r main-parameter-estimates-sens-3, results = "asis", echo = FALSE} -->
<!-- table_param_est( -->
<!--   sens_models[[3]], -->
<!--   model_nms = sens_models_names[[3]], -->
<!--   end_yr = end_yr, -->
<!--   digits = 3, -->
<!--   xcaption = paste0( -->
<!--     "Posterior medians for select parameters, derived quantities, reference ", -->
<!--     "points, and negative log likelihoods for the base model and further ", -->
<!--     "sensitivity runs (described in ", -->
<!--     "Section~\\@ref(sec:assessment-sensitivity-analyses)). A dash (--) ", -->
<!--     "indicates that the parameter or derived quantity was not estimated in ", -->
<!--     "the model."), -->
<!--   xlabel = "tab:main-parameter-estimates-sens-3", -->
<!--   font_size = 9, -->
<!--   space_size = 11, -->
<!--   rec_yrs = c(2010, 2014, 2016, 2020)) -->
<!-- ``` -->

<!-- \end{landscape} -->
<!-- \pagestyle{fancy} -->

<!-- \clearpage -->

<!-- ```{r main-parameter-estimates-retro, results = "asis", echo = FALSE} -->
<!-- table_param_est( -->
<!--   retro_lst, -->
<!--   model_nms = retro_model_nms, -->
<!--   end_yr = end_yr, -->
<!--   digits = 3, -->
<!--   rec_yrs = c(2010, 2014, 2016, 2020), -->
<!--   xcaption = paste0( -->
<!--     "Posterior medians from the base model for select parameters, derived ", -->
<!--     "quantities, reference point estimates, and negative log likelihoods ", -->
<!--     "for retrospective analyses. Some values are implied since they occur ", -->
<!--     "after the ending year of the respective retrospective analysis. A ", -->
<!--     "dash (--) indicates that the parameter or derived quantity was not ", -->
<!--     "output by the model."), -->
<!--   xlabel = "tab:main-parameter-estimates-retro", -->
<!--   font_size = 10, -->
<!--   space_size = 11) -->
<!-- ``` -->

<!-- \clearpage -->
