\newpage

\rfoot{Canadian fishery report}

# Report of the `r assess_yr - 1` `r sp` fishery in Canada {#sec:app-canada-fishery-report}

**Prepared by the Canadian Advisory Panel and submitted on January 21, 2025 for inclusion in this assessment document.**

The Canadian Offshore `r sp` fishery catch was by far the lowest recorded
since the fishery began in the late 1970s, with slightly more than 3,103
tonnes caught, or 3.3% of the 93,450 tonnes TAC set by the Canadian Industry.
This was down from the 22,000 tonnes caught in 2023 when 21% of the 105,000
tonne TAC was harvested. The reports from the fishermen were consistent,
fishing was very poor as evident in the extremely low catch. The fleet
reported no body of Hake on the Canadian Zone that allowed for a fishery to
take place. What little catch occurred was around Finger Bank and south into
San Juan.

The Freezer Vessel Fleet searched the traditional area off Winter
Harbour in shallow and off the edge, but no fish was found. The fish that
were encountered were mostly larger older fish (greater than 1,000 grams).
There were some small fish were seen by the Canadian Fleet. The bycatch was
primarily pollock, and herring. The market for the Hake was strong again in
2024 but the catches were just not there to supply the plants or the Freezer
Vessels. The Freezer Vessels accounted for 88% of the catch in 2024.

\clearpage
