#!/bin/bash

rm *.aux 2> /dev/null
rm *.bbl 2> /dev/null
rm *.blg 2> /dev/null
rm *.dvi 2> /dev/null
rm *.log 2> /dev/null
rm *.lof 2> /dev/null
rm *.lot 2> /dev/null
rm *.ps 2> /dev/null
rm *.toc 2> /dev/null
rm *.txt 2> /dev/null
rm *.out 2> /dev/null
rm *.upa 2> /dev/null
rm *.upb 2> /dev/null
rm index.pdf 2> /dev/null
rm index.tex 2> /dev/null
rm index.md 2> /dev/null

rm hake-assessment.tex 2> /dev/null
rm hake.tex 2> /dev/null
rm hake-assessment-es-only.tex 2> /dev/null

rm -rf knitr-cache 2> /dev/null
rm -rf out-csv 2> /dev/null
rm -rf _book 2> /dev/null
