SELECT DISTINCTROW
YEAR(TRIP_END_DATE) AS Year, TRIP.TRIP_ID, TRIP.VESSEL_ID, VESSEL.VESSEL_NAME,
TRIP.TRIP_END_DATE, TRIP_SUB_TYPE.TRIP_SUB_TYPE_DESC,
FISHING_EVENT.MAJOR_STAT_AREA_CODE, FISHING_EVENT.MINOR_STAT_AREA_CODE,
FISHING_EVENT.FE_MAJOR_LEVEL_ID AS setnumber, SPECIMEN.SAMPLE_ID,
SPECIMEN.SPECIMEN_ID, SPECIMEN.SPECIMEN_AGE, SPECIMEN.SPECIMEN_SERIAL_PREFIX,
MIN(SPECIMEN.SPECIMEN_SERIAL_NUMBER) AS MinOfSPECIMEN_SERIAL_NUMBER,
MAX(SPECIMEN.SPECIMEN_SERIAL_NUMBER) AS MaxOfSPECIMEN_SERIAL_NUMBER,
MAJOR_STAT_AREA.MAJOR_STAT_AREA_NAME, SAMPLE.SAMPLE_WEIGHT,
CATCH.CATCH_WEIGHT, SAMPLE.SAMPLE_DATE,
SpecLen_cm(MORPHOMETRICS_ATTRIBUTE_CODE,SPECIMEN_MORPHOMETRICS_VALUE,MORPHOMETRICS_UNIT_CODE) AS Length_cm,
SPECIMEN.SPECIMEN_SEX_CODE AS sex, CATCH.SPECIES_CATEGORY_CODE,
TRAWL_SPECS.USABILITY_CODE INTO hake_domestic_obs_len_age
FROM TRAWL_SPECS
  INNER JOIN
  (SPECIMEN_MORPHOMETRICS
    INNER JOIN
    (
     (
      (
       (
        (
         (
          (
            TRIP
            INNER JOIN FISHING_EVENT ON TRIP.TRIP_ID = FISHING_EVENT.TRIP_ID
          )
          INNER JOIN FISHING_EVENT_CATCH ON (TRIP.TRIP_ID = FISHING_EVENT_CATCH.TRIP_ID)
            AND (FISHING_EVENT.FISHING_EVENT_ID = FISHING_EVENT_CATCH.FISHING_EVENT_ID)
         )
         INNER JOIN
         (
          (
           (
            CATCH_SAMPLE
            INNER JOIN CATCH ON CATCH_SAMPLE.CATCH_ID = CATCH.CATCH_ID
           )
           INNER JOIN SAMPLE ON CATCH_SAMPLE.SAMPLE_ID = SAMPLE.SAMPLE_ID
          )
          INNER JOIN SPECIMEN ON SAMPLE.SAMPLE_ID = SPECIMEN.SAMPLE_ID
         )
         ON FISHING_EVENT_CATCH.CATCH_ID = CATCH.CATCH_ID
        )
        INNER JOIN TRIP_SUB_TYPE
          ON TRIP.TRIP_SUB_TYPE_CODE = TRIP_SUB_TYPE.TRIP_SUB_TYPE_CODE
       )
       INNER JOIN VESSEL ON (TRIP.SUFFIX = VESSEL.SUFFIX)
         AND (TRIP.VESSEL_ID = VESSEL.VESSEL_ID)
      )
      LEFT JOIN SAMPLE_COLLECTED
        ON SAMPLE.SAMPLE_ID = SAMPLE_COLLECTED.SAMPLE_ID
     )
     INNER JOIN MAJOR_STAT_AREA
       ON FISHING_EVENT.MAJOR_STAT_AREA_CODE = MAJOR_STAT_AREA.MAJOR_STAT_AREA_CODE
    )
    ON (SPECIMEN_MORPHOMETRICS.SAMPLE_ID = SPECIMEN.SAMPLE_ID)
      AND (SPECIMEN_MORPHOMETRICS.SPECIMEN_ID = SPECIMEN.SPECIMEN_ID)
  )
  ON TRAWL_SPECS.FISHING_EVENT_ID = FISHING_EVENT.FISHING_EVENT_ID
WHERE
(
 (
  (
  TRIP.TRIP_SUB_TYPE_CODE)=1 OR (TRIP.TRIP_SUB_TYPE_CODE)=4
 )
 AND (CATCH.SPECIES_CODE='225')
)
GROUP BY
  YEAR(TRIP_END_DATE), TRIP.TRIP_ID, TRIP.VESSEL_ID, VESSEL.VESSEL_NAME,
  TRIP.TRIP_END_DATE, TRIP_SUB_TYPE.TRIP_SUB_TYPE_DESC,
  FISHING_EVENT.MAJOR_STAT_AREA_CODE, FISHING_EVENT.MINOR_STAT_AREA_CODE,
  FISHING_EVENT.FE_MAJOR_LEVEL_ID, SPECIMEN.SAMPLE_ID, SPECIMEN.SPECIMEN_ID,
  SPECIMEN.SPECIMEN_AGE, SPECIMEN.SPECIMEN_SERIAL_PREFIX,
  MAJOR_STAT_AREA.MAJOR_STAT_AREA_NAME, SAMPLE.SAMPLE_WEIGHT,
  CATCH.CATCH_WEIGHT, SAMPLE.SAMPLE_DATE,
  SpecLen_cm(MORPHOMETRICS_ATTRIBUTE_CODE,SPECIMEN_MORPHOMETRICS_VALUE,MORPHOMETRICS_UNIT_CODE),
  SPECIMEN.SPECIMEN_SEX_CODE, CATCH.SPECIES_CATEGORY_CODE,
  TRAWL_SPECS.USABILITY_CODE
HAVING
(
 (
  (
    FIRST(SPECIMEN_MORPHOMETRICS.MORPHOMETRICS_ATTRIBUTE_CODE)
  )=1
  OR
  (
    FIRST(SPECIMEN_MORPHOMETRICS.MORPHOMETRICS_ATTRIBUTE_CODE)
  )=2 OR
  (
    FIRST(SPECIMEN_MORPHOMETRICS.MORPHOMETRICS_ATTRIBUTE_CODE)
  )=4
 )
)
ORDER BY TRIP.TRIP_END_DATE, SPECIMEN.SAMPLE_ID;