SELECT 
  FOREIGN_HAUL.HAUL_JOIN,
  FOREIGN_HAUL.CRUISE,
  FOREIGN_HAUL.YEAR,
  FOREIGN_HAUL.LATITUDE LATDD_END,
  FOREIGN_HAUL.LONGITUDE LONDD_END,
  FOREIGN_HAUL.BOTTOM_DEPTH BOTTOM_DEPTH_FATHOMS,
  FOREIGN_AGE.AGE,
  FOREIGN_AGE.LENGTH,
  FOREIGN_AGE.INDIV_WEIGHT WEIGHT,
  FOREIGN_AGE.SEX
FROM FOREIGN_HAUL
INNER JOIN FOREIGN_AGE
ON FOREIGN_HAUL.HAUL_JOIN = FOREIGN_AGE.HAUL_JOIN
WHERE 
  FOREIGN_HAUL.LATITUDE < 4900 AND
  -- FOREIGN_AGE.AGE IS NOT NULL AND
  FOREIGN_AGE.SPECIES = 206;
