REM ***********************************************************************
REM
REM  Queries obsint tables for calculating domestic catch.
REM  From Vanessa Tuttle
REM
REM ***********************************************************************

(
  SELECT
    obsint.DEBRIEFED_HAUL.HAUL_JOIN HAULJOIN,
    obsint.DEBRIEFED_HAUL.CRUISE,
    obsint.DEBRIEFED_HAUL.PERMIT,
    obsint.DEBRIEFED_HAUL.VESSEL,
    obsint.DEBRIEFED_HAUL.VESSEL_TYPE,
    obsint.DEBRIEFED_HAUL.HAUL_DATE,
    obsint.DEBRIEFED_HAUL.HAUL,
    obsint.DEBRIEFED_HAUL.DEPLOYMENT_DATE,
    obsint.DEBRIEFED_HAUL.RETRIEVAL_DATE,
    (obsint.DEBRIEFED_HAUL.DURATION_IN_MIN / 60) hrs,
    obsint.DEBRIEFED_HAUL.CDQ_CODE,
    obsint.DEBRIEFED_HAUL.OFFICIAL_TOTAL_CATCH,
    obsint.DEBRIEFED_HAUL.HAUL_SAMPLED_BY,
    obsint.DEBRIEFED_HAUL.LATDD_START,
    obsint.DEBRIEFED_HAUL.LONDD_START,
    obsint.DEBRIEFED_HAUL.LATDD_END,
    obsint.DEBRIEFED_HAUL.LONDD_END,
    obsint.DEBRIEFED_HAUL.FISHING_DEPTH_FATHOMS,
    obsint.DEBRIEFED_HAUL.BOTTOM_DEPTH_FATHOMS,
    obsint.DEBRIEFED_HAUL.CATCHER_BOAT_ADFG,
    obsint.DEBRIEFED_SPCOMP.SPECIES,
    obsint.DEBRIEFED_SPCOMP.EXTRAPOLATED_WEIGHT
  FROM
    obsint.DEBRIEFED_HAUL
  LEFT JOIN
    obsint.DEBRIEFED_SPCOMP
  ON
    obsint.DEBRIEFED_HAUL.HAUL_JOIN = obsint.DEBRIEFED_SPCOMP.HAUL_JOIN
  WHERE
    obsint.DEBRIEFED_HAUL.RETRV_LATITUDE < 4900
    AND obsint.DEBRIEFED_HAUL.HAUL_DATE >=  to_date('01-01-&beginyr','dd-mm-yyyy')
    AND obsint.DEBRIEFED_HAUL.HAUL_DATE <= to_date('31-12-&endyr','dd-mm-yyyy')
)
UNION
(
SELECT
  CUR_NOTIN_DEB.*,
  CUR_SP.SPECIES,
  CUR_SP.EXTRAPOLATED_WEIGHT
  FROM (
    SELECT
    obsint.CURRENT_HAUL.HAUL_JOIN,
    obsint.CURRENT_HAUL.CRUISE,
    obsint.CURRENT_HAUL.PERMIT,
    obsint.CURRENT_HAUL.VESSEL,
    obsint.CURRENT_HAUL.VESSEL_TYPE,
    obsint.CURRENT_HAUL.HAUL_DATE,
    obsint.CURRENT_HAUL.HAUL,
    obsint.CURRENT_HAUL.DEPLOYMENT_DATE,
    obsint.CURRENT_HAUL.RETRIEVAL_DATE,
  ((obsint.CURRENT_HAUL.RETRIEVAL_DATE - obsint.CURRENT_HAUL.DEPLOYMENT_DATE) * 24) hrs,
    obsint.CURRENT_HAUL.CDQ_CODE,
    obsint.CURRENT_HAUL.OFFICIAL_TOTAL_CATCH,
    obsint.CURRENT_HAUL.HAUL_SAMPLED_BY,
    obsint.CURRENT_HAUL.LATDD_START,
    obsint.CURRENT_HAUL.LONDD_START,
    obsint.CURRENT_HAUL.LATDD_END,
    obsint.CURRENT_HAUL.LONDD_END,
    obsint.CURRENT_HAUL.FISHING_DEPTH_FATHOMS,
    obsint.CURRENT_HAUL.BOTTOM_DEPTH_FATHOMS,
    obsint.CURRENT_HAUL.CATCHER_BOAT_ADFG
    FROM obsint.CURRENT_HAUL
    LEFT JOIN obsint.DEBRIEFED_HAUL
    ON obsint.CURRENT_HAUL.HAUL_JOIN = obsint.DEBRIEFED_HAUL.HAUL_JOIN
    REM AND o.RETRIEVAL_DATE BETWEEN to_date('01-01-&endyr','dd-mm-yyyy') AND to_date('31-12-&endyr','dd-mm-yyyy')
    WHERE
    obsint.DEBRIEFED_HAUL.DURATION_IN_MIN is NULL
    AND obsint.CURRENT_HAUL.LATITUDE < 4900
    AND obsint.CURRENT_HAUL.RETRIEVAL_DATE >=  to_date('01-01-&endyr','dd-mm-yyyy')
    AND obsint.CURRENT_HAUL.RETRIEVAL_DATE <= to_date('31-12-&endyr','dd-mm-yyyy')
  ) CUR_NOTIN_DEB
  LEFT JOIN
  (
    SELECT
    obsint.CURRENT_SPCOMP.SPECIES,
    obsint.CURRENT_SPCOMP.WEIGHT EXTRAPOLATED_WEIGHT,
    obsint.CURRENT_SPCOMP.HAUL_JOIN
    FROM obsint.CURRENT_SPCOMP
  ) CUR_SP
  ON (CUR_NOTIN_DEB.HAUL_JOIN = CUR_SP.HAUL_JOIN)
)
;
