SELECT YEAR, FINAL_SPECIFICATION_DETAIL_ID,
  FISHERY_HARVEST_GUIDELINE, ACCEPTABLE_BIO_CATCH,
  ANNUAL_CATCH_LIMIT, TRAWL_METRIC_TONS,
  TRIBAL_SET_ASIDE, EFP_SET_ASIDE, RESEARCH_SET_ASIDE,
  OA_SET_ASIDE, BUFFER_SET_ASIDE, SET_ASIDE_TOTAL,
  SHOREBASED_IFQ, CATCHER_PROCESSOR, MOTHERSHIP
FROM
  PACFIN_MARTS.RPT_SPEX_FINAL_SPECIFICATION_DETAIL_V
WHERE
  ACL_CODE like upper(&sp) AND
  YEAR between &beginyr and &endyr
ORDER BY YEAR, FINAL_SPECIFICATION_DETAIL_ID
