\newpage

\rfoot{Introduction}

# Introduction {#sec:introduction}

This assessment reports the status of the coastal `r sp` (or `r common_name`,
*`r science_name`*) stock off the west coast of the United States (U.S.) and Canada
at the start of `r assess_yr`. This stock exhibits seasonal migratory
behavior, ranging from offshore and generally southern waters during the
winter spawning season to coastal areas between northern California and
northern British Columbia during the spring, summer, and fall when the
fishery is conducted. The stock tends to move farther to the north during the
summer in years with warmer water compared to years with colder waters. Older
`r sp` tend to migrate farther north than younger `r sp` in all years, with
catches in Canadian waters typically consisting of fish greater than four years
old. Separate, and much smaller, populations of `r sp` occurring in the major
inlets of the Northeast Pacific Ocean, including the Strait of Georgia, Puget
Sound, and the Gulf of California, are not included in this analysis.

The `r assess_yr` base model structure and data for this Joint Technical Committee (JTC) assessment
is the same as the `r last_data_yr` stock assessment [@JTC2025], projected forward
to the start of `r assess_yr` using the fishery catches from `r last_data_yr`.
This type of stock assessment is often
referred to as a catch-only projection. It is a widespread method used to
provide updated management advice given updates to recent catch history while
using an already approved stock assessment. Available data at the time of this assessment are presented in Appendix~\@ref(sec:app-tables) and
Appendix~\@ref(sec:app-figures) for reference. 

The `r last_data_yr` base model was a statistical catch-at-age population
model fit in a Bayesian context using  Markov chain Monte
Carlo (MCMC) sampling via the efficient No-U-Turn Sampler [@JTC2025].
The model assumed that the `r sp` population is a single coast-wide
stock subject to one aggregated fleet with combined male and female
population dynamics. <!-- The `r assess_yr` base model therefore has the
same data through `r last_data_yr-1`, model structure, and assumptions and is then run forward to the start of `r assess_yr`
using the known fishery catch for `r last_data_yr`.--> The `r assess_yr` model was
re-fit in MCMC to adapt projections and the stochastic nature of finite MCMC sampling across runs when
chains are run in parallel produced similar, but not identical, parameter estimates between the
`r last_data_yr` and `r assess_yr` models. However, all parameter estimates are effectively the same as given
in @JTC2025 in terms of population estimates. 
<!-- The re-fit MCMC runs produced population parameters, resulting population
dynamics, and reference points used for management between the
`r last_data_yr` and `r assess_yr` models. --> The `r assess_yr` model is again configured using
Stock Synthesis [@MethotWetzel2013] version `r ss_version`.

A catch-only projection assessment for `r assess_yr` was chosen because the
biomass estimate and age data from the 2025 Joint U.S.-Canada Integrated West
Coast Pelagics Survey
were not available in time to be incorporated into a fully updated assessment,
as a result of the extended U.S. federal government shutdown in `r last_data_yr`. Furthermore, it has yet to be
determined how to incorporate the new biomass estimate and age data into the existing survey time series in a
compatible way, because of changes in survey design in 2025. 
Thus, the JTC decided that conducting the usual fully updated assessment
(i.e. adding fishery catch and age data for `r last_data_yr` and estimating all parameters) without complete survey information
would not be appropriate. Such an assessment would be based solely on
fishery-age composition data for two 
consecutive years, whereas usually this only occurs for a single year
(in-between the biannual survey). The absence of new survey information to inform
the model could considerably increase the risk of inaccurate assessment
results being used to inform management decisions.
While quantities of interest could still have been calculated and presented,
this could be potentially misleading because numerical estimates of uncertainty
would ignore the major structural uncertainty of having no recent survey biomass and age data.

In this document we present catch data, figures and tables related to results
from the `r assess_yr` base model projections, a Glossary, U.S. and Canadian
Advisory Panel reports summarizing the `r last_data_yr` fishery, and an
updated `r sp`-specific ecosystem summary. We refer readers to @JTC2025 for
details regarding other data summaries, parameter estimates, model
diagnostics, sensitivity analyses, etc.~that have effectively not changed
from the `r last_data_yr` assessment.