\newpage

\rfoot{U.S. fishery report}

# Report of the `r assess_yr - 1` `r sp` fishery in the United States {#sec:app-us-fishery-report}

**Prepared by the United States Advisory Panel on January 23, 2026 for inclusion in this assessment document.**

**2025 U.S. Sector Allocations and Catch**

Based on information provided by U.S. Advisory Panel members and data from
the Pacific Fisheries Information Network (PacFIN), total U.S. harvest in the
2025 whiting fishery was **239,206~t** (see Table \@ref(tab:us-ap-catch-tab)),
which is about 81% of the U.S. allocation of 295,520~t. Compared to the 2024 season
(165,582~t), total U.S. catch was down 45% in 2025.

```{r us-ap-catch-tab, results = "asis", echo = FALSE}

font_size <- 10
header_font_size <- 10
header_vert_spacing <- 12
header_vert_scale <- 1.2

d <- tibble(c("Tribal",
              "Research",
              "Shoreside (SS)",
              "Mothership (MS)",
              "Catcher-Processor (CP)",
              "Total"),
            f(c(51716,
                750,
                102083,
                58333,
                82638,
                295520)),
            f(c(10000,
                750,
                119603,
                68345,
                96822,
                295520)),
            c(f(526),
              "--",
              f(107185),
              f(48938),
              f(82557),
              f(239206)),
            c(f(5),
              "--",
              f(90),
              f(72),
              f(85),
              f(81)))

col_names <- c("U.S. Sector",
               "Initial\nAllocation",
               "Allocation\nAfter\nReapportionment",
               "Catch (t)",
               "Utilization (\\%)")

  # Insert custom header fontsize before linebreaker
  if(is.null(header_font_size)){
    header_font_size <- font_size
  }
  hdr_font_str <- create_fontsize_str(header_font_size,
                                      header_vert_spacing,
                                      header_vert_scale)

  col_names <- gsub("\\n", paste0("\n", hdr_font_str$quad), col_names)
  col_names <- paste0(hdr_font_str$dbl, col_names)
  # Add \\makecell{} latex command to headers with newlines
  col_names <- linebreaker(col_names, align = "c")

kbl(d,
    col.names = col_names,
    align = c("l", "r", "r", "r", "r"),
    format = "latex",
    escape = FALSE,
    linesep = "",
    booktabs = TRUE,
    caption = paste0("2025 U.S. whiting allocations and catch (tonnes, ",
                     "t). Tribal catch is estimated (SS sector), and MS ",
                     "catch was provided by the MS cooperative. Dashes ",
                     "represent unknown values.Tribal reapportionment occurred twice,",
                     "one September 16 and September 29, 2025."),
    longtable = TRUE) |> 
    row_spec(0, bold = TRUE) |>
    row_spec(nrow(d), bold = TRUE) |> 
    kable_styling(font_size = font_size,
                  latex_options = c("repeat_header"))

```

Sources for Table \@ref(tab:us-ap-catch-tab) are from the [Federal register](https://www.govinfo.gov/content/pkg/FR-2024-10-22/pdf/2024-24361.pdf) and
[PacFIN Whiting Report](https://reports.psmfc.org/pacfin/f?p=501:202::INITIAL:NO:::).

**Shoreside (SS)""
Similar to 2024, the 2025 shoreside fishery started out slow (no fish caught in the
first two weeks of May). Fishing steadily picked up as the season progressed and
continued all the way until the end of November, although effort began to drop off
in late October due to weather and some boats heading to shipyard. Summer fishing
for the SS sector was reported to be very good, as boats saw large schools of approximately
500g fish and were able to fill up quickly. In the fall SS fishery, (Sept. through Nov.),
fish were caught from Coos Bay all the way up to Juan de Fuca. Fish size increased
over the season and was reported by shoreside processors to average 510-550g across
the year.

Total catch in the 2025 SS Fishery was 107,185~t, which was about 90% of the total SS
allocation. Several SS catcher boats did run up against their 2025 individual allocation
and were either forced to quit early in the season or lease additional hake quota to
continue fishing. 

**Mothership (MS)**
The 2025 mothership fishery was much improved compared to previous years. The MS
fishery began mid-June and ended October 23, 2025. Fish availability was better and
generally consistent throughout the year. Over the course of the year, MS fishing
activity was distributed primarily south of Newport, OR. Improved utilization by the
MS sector in 2025 is largely due to the consistent availability of MS platforms
on the fishing grounds throughout the fishing year, as the two MS platforms that
participated in the 2025 fishery remained on the grounds throughout the summer. The
MS catcher boats were able to turn several trips with good, clean fishing, good fish
size (avgeraging about 417g), and great catch per unit effort (CPUE).

Total catch in the 2025 MS fishery was 48,938~t, which was about 72% of the MS
allocation. Several MS catcher boats did run up against their 2025 individual
allocation and were either forced to quit early in the season or lease additional
hake quota to continue fishing. 

**Catcher Processor (CP)**

Overall fishing conditions for the CP sector were improved compared to last year, with
better fish availability north of the California/Oregon border. Nearly all fishing
activity took place off the Oregon Coast, distributed from the Columbia River to the
California border. The CP fishery began in mid-May, and all CPs completed fishing
operations by early November.

Total catch in the 2025 CP fishery was 82,557~t, which was about 85% of the CP allocation.
The primary reason the CP sector did not catch 100% of its allocation is due to a loss
of two CP vessels from one company over the past several years. Its important to note
two of the three CP companies that participated in the 2025 CP fishery caught nearly
all of their allocations.

\clearpage