#!/bin/bash

rm *.log 2> /dev/null
rm *.out 2> /dev/null
rm *.tex 2> /dev/null
rm *.aux 2> /dev/null
rm *.aux 2> /dev/null
rm *.snm 2> /dev/null
rm *.nav 2> /dev/null
rm *.toc 2> /dev/null
rm *.pdf 2> /dev/null

rm -rf figures
rm -rf knitr-cache
