#!/bin/bash

rm beamer-hake-assessment.log 2> /dev/null
rm beamer-hake-assessment.out 2> /dev/null
rm beamer-hake-assessment.tex 2> /dev/null
rm beamer-hake-assessment.aux 2> /dev/null
rm beamer-hake-assessment.aux 2> /dev/null
rm beamer-hake-assessment.snm 2> /dev/null
rm beamer-hake-assessment.nav 2> /dev/null
rm beamer-hake-assessment.toc 2> /dev/null
rm *.pdf 2> /dev/null
rm -rf knitr-figs
rm -rf knitr-cache
