# Age-1 index

## Removing the age-1 relative index
```{r age1-biomass-fig, fig.height = 4, out.height = "85%"}
plot_biomass(model_lst = list(base_model,
                              sens_models[[2]][[2]]),
             model_names = c(base_model_name,
                             sens_models_desc[[2]][1]),
               x_expansion = 4,
               ylim = c(0, 5),
               y_breaks = seq(0, 5, 1),
               tick_prop = 1.5,
               vjust_x_labels = 0,
               leg_font_size = 5,
               leg_pos = c(0.7, 0.85),
               rev_colors = TRUE,
               ribbon_line_type = 0) +
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.key.size = unit(0.5, units = "cm"),
        legend.text = element_text(size = 10))
```

## Removing the age-1 relative index
```{r age1-rec-devs-fig, fig.height = 4, out.height = "85%"}
plot_recdevs(model_lst = list(base_model,
                              sens_models[[2]][[2]]),
             model_names = c(base_model_name,
                             sens_models_desc[[2]][1]),
               x_expansion = 2,
               #vjust_x_labels = -0.25,
               leg_font_size = 9,
               xlim = c(1990, 2025),
               leg_pos = c(0.80, 0.90),
               x_labs_mod = 10,
               #tick_prop = 2,
               line_width = 0.3,
               rev_colors = TRUE) +
  theme_bw() + 
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = "none",
        plot.background = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        legend.key.size = unit(0.5, units = "cm"),
        legend.text = element_text(size = 10))
```

<!--
## Removing the age-1 index
```{r age1-par-table, results = "asis"}
table_param_est(models = list(sens_models[[2]][[1]],
                              sens_models[[2]][[2]]),
                model_nms = sens_models_names[[2]][1:2],
                show_loglike = FALSE,
                digits = 3,
                font_size = 5,
                right_cols_cm = 1.25,
                header_font_size = 6,
                section_line_above = FALSE,
                section_line_below = FALSE) |>
  # Highlight some rows
  row_spec(c(3, 18),
           bold = table_highlight_bold,
           background = table_highlight_color)

```
-->