# M

## Natural mortality, *M* (base has prior median 0.2, SD 0.1)
```{r m-biomass-fig, fig.height = 4, out.height = "85%"}
plot_biomass(model_lst = list(base_model,
                              sens_models[[1]][[6]],
                              sens_models[[1]][[7]],
                              sens_models[[1]][[8]]),
             model_names = c(base_model_name,
                             sens_models_desc[[1]][5],
                             sens_models_desc[[1]][6],
                             sens_models_desc[[1]][7]),
             x_expansion = 4,
             ylim = c(0, 20),
             y_breaks = seq(0, 20, 5),
             tick_prop = 1.25,
             vjust_x_labels = -0.25,
             leg_font_size = leg_font_size,
             leg_pos = leg_locs,
             rev_colors = TRUE,
             ribbon_line_type = ribbon_line_type) +
  theme(legend.key.size = unit(0.5, units = "cm"),
        legend.text = element_text(size = 10))
```

## Natural mortality, *M* (base has prior median 0.2, SD 0.1)
```{r m-biomass-fig-rel, fig.height = 4, out.height = "85%"}
plot_rel_biomass(model_lst = list(base_model,
                                  sens_models[[1]][[6]],
                                  sens_models[[1]][[7]],
                                  sens_models[[1]][[8]]),
                 model_names = c(base_model_name,
                                 sens_models_desc[[1]][5],
                                 sens_models_desc[[1]][6],
                                 sens_models_desc[[1]][7]),
             x_expansion = 4,
             ylim = c(0, 4),
             y_breaks = seq(0, 4, 1),
             tick_prop = 1.5,
             vjust_x_labels = -2.75,
             hjust_y_labels = 1,
             leg_font_size = leg_font_size,
             leg_pos = leg_locs,
             rev_colors = TRUE,
             ribbon_line_type = ribbon_line_type) +
  theme(legend.key.size = unit(0.5, units = "cm"),
        legend.text = element_text(size = 10))
```

## Natural mortality, *M* (base has prior median 0.2, SD 0.1)
```{r m-par-table, results = "asis"}
table_param_est(models = list(base_model,
                              sens_models[[1]][[6]],  # [[1]] is base model
                              sens_models[[1]][[7]],
                              sens_models[[1]][[8]]),
                model_nms = c(base_model_name,
                              sens_models_names[[1]][6],
                              sens_models_names[[1]][7],
                              sens_models_names[[1]][8]),
                show_loglike = FALSE,
                digits = 3,
                font_size = 5,
                right_cols_cm = 1.25,
                header_font_size = 6,
                section_line_above = FALSE,
                section_line_below = FALSE) |>
  # Highlight some rows
  row_spec(c(2, 3, 18),
           bold = table_highlight_bold,
           background = table_highlight_color)
```


## Natural mortality at age (0-1, 2, 3, 4, 5+)


```{r matage-sensitivity-biomass-fig, fig.height = 4, out.height = "85%"}

leg_font_size <- 5
leg_locs <- c(0.7, 0.85)
ribbon_line_type <- 0

plot_biomass(model_lst = list(base_model,
                              sens_models[[4]][[2]],
                              sens_models[[4]][[3]]),
             model_names = c(base_model_name,
                             sens_models_desc[[4]][1],
                             sens_models_desc[[4]][2]),
             x_expansion = 4,
             ylim = c(0, 5),
             y_breaks = seq(0, 5, 1),
             tick_prop = 1.5,
             vjust_x_labels = -0.25,
             leg_font_size = leg_font_size,
             leg_pos = leg_locs,
             rev_colors = TRUE,
             ribbon_line_type = ribbon_line_type) +
  theme(legend.key.size = unit(0.5, units = "cm"),
        legend.text = element_text(size = 10))
```


## Natural mortality at age (0-1, 2, 3, 4, 5+)

```{r matage-sensitivity-biomass-rel, fig.height = 4, out.height = "85%"}
plot_rel_biomass(model_lst = list(base_model,
                                  sens_models[[4]][[2]],
                                  sens_models[[4]][[3]]),
                 model_names = c(base_model_name,
                             sens_models_desc[[4]][1],
                             sens_models_desc[[4]][2]),
                 x_expansion = 4,
                 ylim = c(0, 2.5),
                 y_breaks = seq(0, 2.5, 0.5),
                 tick_prop = 1.25,
                 vjust_x_labels = -1.5,
                 hjust_y_labels = 1,
                 leg_font_size = 5,
                 leg_pos = c(0.7, 0.85),
                 rev_colors = TRUE,
                 ribbon_line_type = 0) +
  theme(legend.key.size = unit(0.5, units = "cm"),
        legend.text = element_text(size = 10))
```
