# Retrospectives

## Base model retrospectives -- Spawning biomass
```{r retro-biomass-1, fig.height = 3, out.height = "85%"}

plot_biomass(d_obj = retros_biomass_incremental[[1]],
             leg_font_size = 5,
             x_expansion = 4,
             tick_prop = 1.5,
             vjust_x_labels = 0,
             leg_pos = c(0.7, 0.85),
             leg_ncol = 1,
             alpha = 0.1,
             rev_colors = TRUE,
             ribbon_line_type = 0) +
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.key.size = unit(0.1, units = "cm"),
        legend.text = element_text(size = 8))
```

## Base model retrospectives -- Spawning biomass
```{r retro-biomass-2, fig.height = 3, out.height = "85%"}

plot_biomass(d_obj = retros_biomass_incremental[[2]],
             leg_font_size = 5,
             x_expansion = 4,
             tick_prop = 1.5,
             vjust_x_labels = 0,
             leg_pos = c(0.7, 0.85),
             leg_ncol = 1,
             alpha = 0.1,
             rev_colors = TRUE,
             ribbon_line_type = 0) +
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.key.size = unit(0.1, units = "cm"),
        legend.text = element_text(size = 8))
```

## Base model retrospectives -- Spawning biomass
```{r retro-biomass-3, fig.height = 3, out.height = "85%"}

plot_biomass(d_obj = retros_biomass_incremental[[3]],
             leg_font_size = 5,
             x_expansion = 4,
             tick_prop = 1.5,
             vjust_x_labels = 0,
             leg_pos = c(0.7, 0.85),
             leg_ncol = 1,
             alpha = 0.1,
             rev_colors = TRUE,
             ribbon_line_type = 0) +
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.key.size = unit(0.1, units = "cm"),
        legend.text = element_text(size = 8))
```

## Base model retrospectives -- Spawning biomass
```{r retro-biomass-4, fig.height = 3, out.height = "85%"}

plot_biomass(d_obj = retros_biomass_incremental[[4]],
             leg_font_size = 5,
             x_expansion = 4,
             tick_prop = 1.5,
             vjust_x_labels = 0,
             leg_pos = c(0.7, 0.85),
             leg_ncol = 1,
             alpha = 0.1,
             rev_colors = TRUE,
             ribbon_line_type = 0) +
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.key.size = unit(0.1, units = "cm"),
        legend.text = element_text(size = 8))
```


## Base model retrospectives -- spawning biomass
```{r retro-biomass-5, fig.height = 3, out.height = "85%"}

plot_biomass(d_obj = retros_biomass_incremental[[5]],
             leg_font_size = 5,
             x_expansion = 4,
             tick_prop = 1.5,
             vjust_x_labels = 0,
             leg_pos = c(0.7, 0.85),
             leg_ncol = 1,
             alpha = 0.1,
             rev_colors = TRUE,
             ribbon_line_type = 0) +
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.key.size = unit(0.1, units = "cm"),
        legend.text = element_text(size = 8))
```


## Base model retrospectives -- recruitment
```{r retro-recr-2, fig.height = 3, out.height = "85%"}
leg_font_size <- 5
leg_locs <- c(0.7, 0.85)
ribbon_line_type <- 0

plot_recruitment(d_obj = base_model$retrospectives$recr_df  ,
                 tick_prop = 1.5,
                 vjust_x_labels = 0,
                 leg_font_size = 5,
                 leg_pos = c(0.10, 0.75),
                 inc_means = FALSE,
                 rev_colors = TRUE,
                 xlim = c(2007, 2024),
                 x_expansion = 1) +
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.key.size = unit(0.5, units = "cm"),
        legend.text = element_text(size = 10))
```


```{r retro-fix-axis, echo=FALSE}
y_lim_squid <- c(-3.6, 4.2)    # Fix across plots.
```

## Base model retrospective -- squid plot
```{r retro-3e, fig.height = 3, out.height = "85%"}

plot_squid(base_model,
           show_ci = TRUE,
           ci_yrs = c(2020,2021),
           y_lim = y_lim_squid) +
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12))
```
