# Summary

## Summary of management outcomes (1)

* Uncertainty is large, but stock currently has a `r probs_curr_below_b40`%
  chance of being below `r b_40` and a `r probs_curr_rel_fish_intens_above_1`%
  chance of relative fishing intensity being above 100% (slide 4) TODO

* Based on the default harvest rule, the estimated median catch limit
  for `r min(forecast_yrs)` is `r ct_limit_quantiles["median"]` t
  (with 95% interval from `r ct_limit_quantiles["lower"]` to
  `r ct_limit_quantiles["upper"]` t

* There is `r prob_decl_yr1_zero_catch`% chance that spawning biomass will
  decline from `r forecast_yrs[1]` to `r forecast_yrs[2]` with zero catch and
  $\geqslant$ `r prob_decl_yr1_other_catch`% chance of decline for all other catch
  streams

* There is `r prob_decl_yr2_zero_catch`% chance that spawning biomass will
  decline from `r forecast_yrs[2]` to `r forecast_yrs[3]` with zero catch and
  $\geqslant$ `r prob_decl_yr2_other_catch`% chance of decline for all other catch
  streams

* Maintaining a constant catch of `r f(last_yr_catch_fore)` t (the approximate
  `r last_data_yr` catch) results in a `r prob_below_b40_yr1_last_yr_catch`%
  chance of falling below `r b_40` in 1 year, and
  `r prob_below_b40_yr2_last_yr_catch`% in 2 years

* Projections strongly influenced by size of the above-average 2021 cohort,
  which is still highly uncertain at this point

## Uncertainty around 2021 cohort is large

```{r recruitment, out.height = "85%"}
plot_recruitment(list(base_model),
                 list(base_model_name),
                 inc_means = TRUE,
                 leg_pos = "none") +
  geom_rect(aes(xmin = 2020.5,
                xmax = 2021.5,
                ymin = 3,
                ymax = 28),
            color = "red",
            fill = "transparent")
```

