# Catch

## Catch, TAC, and Attainment for `r last_data_yr`

```{r catch-tac-attain-table, results = "asis"}

table_catch_tac_summary(last_data_yr, font_size = 6)
```

## Catch by month and sector

```{r catch-by-month-fig}

plot_catch_by_month(list(us_ss_catch_by_month_df,
                         can_ss_catch_by_month_df,
                         us_cp_catch_by_month_df,
                         can_ft_catch_by_month_df,
                         us_ms_catch_by_month_df),
                    list("U.S. Shore-Based",
                         "Canadian Shoreside",
                         "U.S. Catcher-Processor",
                         "Canadian Freezer-Trawlers",
                         "U.S. Mothership"),
                    type = "catch",
                    disclaimer_text = paste0(
                      "These plots have different y-axis ranges\n",
                      "and are not directly comparable\n",
                      "with each other."),
                    yrs = c(last_data_yr - 4, last_data_yr),
                    leg_font_size = 8,
                    title_font_size = 10,
                    ax_text_x = 8,
                    ax_text_y = 8)
```

## Cumulative catch by month and sector
```{r cumulative-catch-by-month-fig}

plot_catch_by_month(list(us_ss_catch_by_month_df,
                         can_ss_catch_by_month_df,
                         us_cp_catch_by_month_df,
                         can_ft_catch_by_month_df,
                         us_ms_catch_by_month_df),
                    list("U.S. Shore-Based",
                         "Canadian Shoreside",
                         "U.S. Catcher-Processor",
                         "Canadian Freezer-Trawlers",
                         "U.S. Mothership"),
                    type = "cumulative",
                    yrs = c(last_data_yr - 4, last_data_yr),
                    leg_font_size = 8,
                    title_font_size = 10,
                    ax_text_x = 8,
                    ax_text_y = 8)
```

## Proportion of total catch by month and sector
```{r proportion-catch-by-month-fig}

plot_catch_by_month(list(us_ss_catch_by_month_df,
                         can_ss_catch_by_month_df,
                         us_cp_catch_by_month_df,
                         can_ft_catch_by_month_df,
                         us_ms_catch_by_month_df),
                    list("U.S. Shore-Based",
                         "Canadian Shoreside",
                         "U.S. Catcher-Processor",
                         "Canadian Freezer-Trawlers",
                         "U.S. Mothership"),
                    type = "proportion",
                    yrs = c(last_data_yr - 4, last_data_yr),
                    y_breaks = seq(0, 1, 0.25),
                    leg_font_size = 8,
                    title_font_size = 10,
                    ax_text_x = 8,
                    ax_text_y = 8)
```

## U.S. Proportion of Sector quota caught
```{r proportion-of-quota-catch-by-month-fig}

plot_catch_by_month(list(us_ss_catch_by_month_df,
                         us_cp_catch_by_month_df,
                         us_ms_catch_by_month_df),
                    list("U.S. Shore-Based",
                         "U.S. Catcher-Processor",
                         "U.S. Mothership"),
                    type = "quota",
                    quota_lst = list(select(further_tac_df,
                                            Year,
                                            us_shore_reallocated),
                                     select(further_tac_df,
                                            Year,
                                            us_cp_reallocated),
                                     select(further_tac_df,
                                            Year,
                                            us_ms_reallocated)),
                    disclaimer_text = paste0(
                      "Canada does not have fleet-specific\n",
                      "quotas so only U.S. sectors are\n",
                      "shown here"),
                    yrs = c(last_data_yr - 4, last_data_yr),
                    y_breaks = seq(0, 1, 0.25),
                    leg_font_size = 8,
                    title_font_size = 10,
                    ax_text_x = 8,
                    ax_text_y = 8)
```
