# Sampling summaries

## Monthly sampling summary for Canada in `r last_data_yr`

```{r age-comp-comparison, results = "asis"}

sample_df <- canada_load_sample_data() |> 
  dplyr::filter(sex %in% c(1, 2))

samples_fleet_lst <- canada_get_fleet_samples(sample_df)
# Remove JV for this table
samples_fleet_lst <- samples_fleet_lst[names(samples_fleet_lst) != "jv"]

samples_summary_tbls_lst <- canada_extract_sampling_by_month(
  samples_fleet_lst,
  yr = last_data_yr)

```

:::::: {.columns}
::: {.column width="45%"}
\begin{center}\textbf{Freezer trawlers}\end{center}
```{r canada-sample-summary-ft, results = "asis"}
table_sampling_by_month(
  samples_summary_tbls_lst$ft,
  font_size = 8,
  header_font_size = 9)
```
:::

::: {.column width="45%"}
\begin{center}\textbf{Shoreside}\end{center}
```{r canada-sample-summary-ss, results = "asis"}
table_sampling_by_month(
  samples_summary_tbls_lst$ss,
  font_size = 8,
  header_font_size = 9)
```
:::
::::::

## Monthly sampling summary for U.S. in `r last_data_yr`

```{r calc-numread, echo = FALSE, eval = FALSE}
load("page.Rdat")
load("atsea.ages.Rdat")
```

```{r us-sample-summary-atsea, results = "asis", eval = FALSE}
# TODO: use this code rather than the pre-made tables below
table_sampling_by_month(
  us_extract_sampling_by_month(c("AGE", "LENGTH", "WEIGHT"), nages),
  font_size = 8,
  header_font_size = 9)
```


```{r us-sample-summary-sb, results = "asis", eval = FALSE}
# TODO: use this code rather than the pre-made tables below
table_sampling_by_month(
  us_sb_age_df, #us_extract_sampling_by_month(c("AGE", "FISH_LENGTH", "FISH_WEIGHT"), page),
  font_size = 8,
  header_font_size = 9)
```

:::::: {.columns}
::: {.column width="45%"}
\begin{center}\textbf{At-Sea}\end{center}
```{r us-atsea-sampling-summary, results = "asis"}
d <- tibble(month = c("May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Total"),
            num_age = c(215, 1, 0, 72, 178, 157, 0, 623),
            num_length = c(429, 4, 28, 250, 715, 455, 0, 1881),
            num_weight = c(429, 4, 28, 250, 715, 455, 0, 1881))
table_sampling_by_month(d,
                        font_size = 8,
                        header_font_size = 9)
```
:::

::: {.column width="45%"}
\begin{center}\textbf{Shore-based}\end{center}
```{r us-sb-sampling-summary, results = "asis"}
d <- tibble(month = c("May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Total"),
            num_age = c(119, 240, 330, 240, 219, 140, 0, 1288),
            num_length = c(360, 600, 800, 620, 510, 360, 0, 3250),
            num_weight = c(240, 480, 650, 500, 380, 300, 0, 2550))
table_sampling_by_month(d,
                        font_size = 8,
                        header_font_size = 9)
```
:::
::::::
