# Pacific Hake Joint Technical Committee
# This is the master file - it loads all packages and sources all
#  other R source code files.
#
# To debug in an R session, run these 3 commands first:
# source(file.path(here::here(), "R/all.r"));load.models.into.parent.env();source(file.path(here::here(), "R/custom-knitr-variables.r"))

library(coda)
library(cowplot)
library(date)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(grid)
library(gridExtra)
library(gtools)
library(here)
library(kableExtra)
library(knitr)
library(lubridate)
library(maps)
library(maptools)
library(purrr)
library(r4ss)
library(reshape2)
library(rgeos)
library(rnaturalearth)
library(rnaturalearthhires)  # devtools::install_github("ropensci/rnaturalearthhires")
library(sf)
library(tidyverse)
library(xtable)

rootd <- here::here()
rootd.R <- file.path(rootd, "R")
rootd.admin <- file.path(rootd, "admin")
rootd.data <- file.path(rootd, "data")
rootd.map.data <- file.path(rootd.data, "map-data")
rootd.data.prep <- file.path(rootd, "data-prep")
rootd.doc <- file.path(rootd, "doc")
rootd.extra.calcs <- file.path(rootd, "extra-calculations")
rootd.models <- file.path(rootd, "models")
rootd.pres <- file.path(rootd, "beamer")

source(file.path(rootd.R, "utilities.R"))
source(file.path(rootd.R, "catches.R"))
source(file.path(rootd.R, "run-catch-levels.R"))
source(file.path(rootd.R, "create-rdata-file.R"))
source(file.path(rootd.R, "delete-files.R"))
source(file.path(rootd.R, "extra-mcmc.R"))
source(file.path(rootd.R, "retrospectives.R"))
source(file.path(rootd.R, "forecasts.R"))
source(file.path(rootd.R, "load-models.R"))
source(file.path(rootd.R, "survey.R"))
source(file.path(rootd.R, "load-data.R"))
source(file.path(rootd.R, "read-list.R"))
source(file.path(rootd.R, "figures-timeseries.R"))
source(file.path(rootd.R, "figures-compare-forecasts.R"))
source(file.path(rootd.R, "figures-mcmc-diagnostics.R"))
source(file.path(rootd.R, "figures-age-comps.R"))
source(file.path(rootd.R, "figures-selex.R"))
source(file.path(rootd.R, "figures-stock-recruitment.R"))
source(file.path(rootd.R, "figures-mle-mcmc.R"))
source(file.path(rootd.R, "figures-overview-map.R"))
source(file.path(rootd.R, "figures-data.R"))
source(file.path(rootd.R, "figures-assessment-history.R"))
source(file.path(rootd.R, "figures-age-comp-forecast.R"))
source(file.path(rootd.R, "figures-SPR-illustration-appendix.R"))
source(file.path(rootd.R, "figures-selectivity-parameterizations.R"))
source(file.path(rootd.R, "figures-size-at-age.R"))
source(file.path(rootd.R, "figures-maturity-ogive.R"))
source(file.path(rootd.R, "figures-R0-vs-meanRecruitment.R"))
source(file.path(rootd.R, "figures-makebox.R"))
source(file.path(rootd.R, "plotcolour.R"))
source(file.path(rootd.R, "tables-timeseries.R"))
source(file.path(rootd.R, "tables-reference-points.R"))
source(file.path(rootd.R, "tables-decisions.R"))
source(file.path(rootd.R, "tables-age.R"))
source(file.path(rootd.R, "tables-assessmentchanges.R"))
source(file.path(rootd.R, "tables-parameters.R"))
source(file.path(rootd.R, "tables-sampling.R"))
source(file.path(rootd.R, "tables-squid.R"))
source(file.path(rootd.R, "tables-maturity.R"))
source(file.path(rootd.R, "theme.R"))
source(file.path(rootd.R, "model-setup.R"))
source(file.path(rootd.R, "forecast-catch-levels.R"))
source(file.path(rootd.R, "retrospective-setup.R"))
source(file.path(rootd.R, "data-tables.R"))
source(file.path(rootd.R, "useful-quantities.R"))

theme_set(hake_theme())
