# Pacific Hake Joint Technical Committee
# This is the master file - it loads all packages and sources all
#  other R source code files.
#
# To debug in an R session, run these 3 commands first:
# source(file.path(here::here(), "R/all.r"));load.models.into.parent.env();source(file.path(here::here(), "R/custom-knitr-variables.r"))

library(nwfscSurvey)
library(nwfscMapping)
library(date)
library(r4ss)
library(xtable)
library(PBSmapping)
library(PBSmodelling)
library(maps)
library(dplyr)
library(coda)
library(gtools)
library(maptools)
library(lubridate)
library(knitr)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(purrr)
library(cowplot)
library(kableExtra)
## library(parallel)
## library(doParallel)

rootd <- here::here()
rootd.R <- file.path(rootd, "R")
rootd.admin <- file.path(rootd, "admin")
rootd.data <- file.path(rootd, "data")
rootd.map.data <- file.path(rootd.data, "map-data")
rootd.data.prep <- file.path(rootd, "data-prep")
rootd.doc <- file.path(rootd, "doc")
rootd.extra.calcs <- file.path(rootd, "extra-calculations")
rootd.models <- file.path(rootd, "models")
rootd.pres <- file.path(rootd, "beamer")

source(file.path(rootd.R, "utilities.R"))
source(file.path(rootd.R, "catches.R"))
source(file.path(rootd.R, "load-models.R"))
source(file.path(rootd.R, "survey.R"))
source(file.path(rootd.R, "load-data.R"))
source(file.path(rootd.R, "read-list.R"))
source(file.path(rootd.R, "figures-timeseries.R"))
source(file.path(rootd.R, "figures-compare-forecasts.R"))
source(file.path(rootd.R, "figures-mcmc-diagnostics.R"))
source(file.path(rootd.R, "figures-age-comps.R"))
source(file.path(rootd.R, "figures-selex.R"))
source(file.path(rootd.R, "figures-stock-recruitment.R"))
source(file.path(rootd.R, "figures-mle-mcmc.R"))
source(file.path(rootd.R, "figures-overview-map.R"))
source(file.path(rootd.R, "figures-data.R"))
source(file.path(rootd.R, "figures-assessment-history.R"))
source(file.path(rootd.R, "figures-age-comp-forecast.R"))
source(file.path(rootd.R, "figures-SPR-illustration-appendix.R"))
source(file.path(rootd.R, "figures-selectivity-parameterizations.R"))
source(file.path(rootd.R, "figures-size-at-age.R"))
source(file.path(rootd.R, "figures-maturity-ogive.R"))
source(file.path(rootd.R, "figures-R0-vs-meanRecruitment.R"))
source(file.path(rootd.R, "tables-timeseries.R"))
source(file.path(rootd.R, "tables-reference-points.R"))
source(file.path(rootd.R, "tables-decisions.R"))
source(file.path(rootd.R, "tables-age.R"))
source(file.path(rootd.R, "tables-parameters.R"))
source(file.path(rootd.R, "tables-sampling.R"))
source(file.path(rootd.R, "tables-maturity.R"))
source(file.path(rootd.R, "model-setup.R"))
source(file.path(rootd.R, "forecast-catch-levels.R"))
source(file.path(rootd.R, "retrospective-setup.R"))
source(file.path(rootd.R, "data-tables.R"))
source(file.path(rootd.R, "SS_output.R"))
## source(file.path(rootd.R, "SS_readdat.R"))
## source(file.path(rootd.R, "SSgetMCMC.R"))
## source(file.path(rootd.R, "SSplotSelex.R"))

## ggplot globals for project
##ggplot2::theme_set(gfplot::theme_pbs())
scale_colour_continuous <- scale_colour_viridis_c
scale_fill_continuous <- scale_fill_viridis_c

sensitivity_colors <- c("#000000", RColorBrewer::brewer.pal(8L, "Dark2"))
scale_colour_discrete <- function(...) scale_colour_manual(..., values = sensitivity_colors)
scale_fill_discrete <- function(...) scale_fill_manual(... , values = sensitivity_colors)
