#' Make a box plot from a data frame of quantiles
#'
#' Use [graphics::bxp], which is normally called by
#' [graphics::boxplot] to create a boxplot. Given the data
#' are provided directly in `data` there is no need to use
#' the wrapper and [graphics::bxp] is called directly.
#'
#' @md
#' @param data A data frame of quantiles by year. The function
#' assumes that the depth data are in meters.
#' @param col The default is to use gray for all boxes, but
#' one can change to "colour" which will use custom colours
#' per year that are generated by [plotcolour].
#' @param lty To change the line type, where the default is
#' `1` and leads to solid lines, where `2` would produce dashed
#' lines, etc. These lines are both for the whiskers and the
#' median that cuts the center of the box.
#' @param labels Character values for the horizontal and
#' vertical axes labels.
#' @param ... Items passed to [graphics::bxp]. Typically this will
#' include things such as `main`.
#' @author Kelli Faye Johnson
#' @return A boxplot is printed to the screen. If you save the object
#' you will be disappointed because is just a vector of integers
#' the same length as the number of boxes in the figure; though
#' the figure is still generated.
#'
makebox <- function(data, col = c("gray", "colour"), lty = 1,
  labels = c("Year", "Depth (m)"), ...) {
  colnames(data) <- tolower(colnames(data))
  keepcols <- c("lower95", "lowerhinge", "median",
    "upperhinge", "upper95")
  x <- list(
    "stats" = t(data[, keepcols]),
    "out" = NULL, "group" = NULL, "conf" = NULL,
    "names" = data$year)
  col <- match.arg(col, several.ok = FALSE)
  if (col == "colour") {
    col <- plotcolour(nrow(x$stats))
  }
  pars <- list(boxfill = col, boxlty = 1,
    ylim = c(0, max(x[["stats"]]) * 1.05))
  if (any(c("black", "#000000") %in% col) &&
    !"border" %in% names(pars)) {
    par("fg" = "gray")
  }
  bxp(x, pars = pars, lty = lty, border = "gray", las = 1,
    xlab = labels[1], ylab = labels[2], ...)
}