#' Render a PDF for the Hake Rmarkdown project
#'
#' @param input The name of the launching `rmd` file. This should be the
#' same as the first `rmd` file named in the `_bookdown.yml` file.
#' See `input` argument for [bookdown::render_book()]
#' @param output_dir Which directory to build the PDF in.
#' See `output_dir` argument for [bookdown::render_book()]
#' @param tex_fn The filename of the TeX file generated by
#' [bookdown::render_book()] to send to the post processing function.
#' See `fn` argument for [post_process()]
#' @param tag_pdf Logical. Tag the PDF for accessibility or not.
#' See `tag` argument for [post_process()]
#' @param ... Arguments to pass to the [bookdown::render_book()] and
#' [post_process()] functions
#'
#' @return Nothing
#' @export
render <- function(input = "000-launcher.rmd",
                   output_dir = ".",
                   tex_fn = "hake.tex",
                   tag_pdf = FALSE,
                   ...){

  bookdown::render_book(input = input,
                        output_dir = output_dir,
                        ...)
  post_process(fn = tex_fn,
               tag = tag_pdf,
               ...)
}
