#' Calculate the standard deviation of recruitment deviations in an MCMC
#' data frame
#'
#' @param posteriors The MCMC data frame as generated by [r4ss::SSgetMCMC()]
#' @param pattern The regular expression used to match the columns
#'
#' @return A formatted string representing the standard deviation of the
#' recruitment deviations
#' @export
calc_sd_of_devs <- function(posteriors, pattern = "Main") {
  posteriors |>
    select(matches(pattern)) |>
    apply(MARGIN = 1, FUN = sd) |>
    median() |>
    f(2)
}
